### PR TITLE
Fiix getArray mistake in CondIsTagged, add runtime error for bad namespace keys in ExprTag

### LINKED ISSUE #7471: CondIsTagged uses getArray instead of getAll
### Skript/Server Version

```markdown
[17:37:45 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:37:45 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[17:37:45 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:37:45 INFO]: [Skript] Server Version: 1.21.3-2358-16ce24a (MC: 1.21.3)
[17:37:45 INFO]: [Skript] Skript Version: 2.10.0 (skriptlang-github)
[17:37:45 INFO]: [Skript] Installed Skript Addons: 
[17:37:45 INFO]: [Skript]  - SkBee v3.8.1 (https://github.com/ShaneBeee/SkBee)
[17:37:45 INFO]: [Skript]  - SkQuery v4.1.10
[17:37:45 INFO]: [Skript]  - skript-placeholders v1.7.0 (https://github.com/APickledWalrus/skript-placeholders)
[17:37:45 INFO]: [Skript]  - skript-db v1.3.9
[17:37:45 INFO]: [Skript] Installed dependencies: 
[17:37:45 INFO]: [Skript]  - Vault v1.7.3-b131
[17:37:45 INFO]: [Skript]  - WorldGuard v7.0.13-beta-1+2f13ae0
```

### Bug Description

There is like 10% chance that message will be sent to player.
Skript doesnt recognize item tags every time.
It never happened with "any shulker box" or "any trapdoor".

### Expected Behavior

Recognize item tag every time.

### Steps to Reproduce

```
on rightclick:
	player's world = "spawn"
	#player doesn't have permission "*"
	if event-block is item frame or glow item frame or armor stand or brewing stand or hopper or barrel:
		send "test a" to player
		cancel event
	if event-block is tagged as item tag "shulker_boxes" or "doors" or "trapdoors" or "pots" or "gates" or "furnaces":
		send "test b" to player
		cancel event
```

### Errors or Screenshots

_No response_

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by sovdeeth**
### Description

changes getArray to getAnd in CondIsTagged to fix #7471
adds runtime error to catch invalid tags in ExprTag

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7471

### CODE REVIEW

**Review by UnderscoreTud — APPROVED** [review]

**Review by Efnilite — APPROVED** [review]

File: src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTag.java [hunk 1]
```diff
@@ -87,14 +92,21 @@ public boolean init(Expression<?>[] expressions, int matchedPattern, Kleenean is
...
+					// populate namespace if not provided
+					key = new NamespacedKey(namespace, name);
+				}
+			} catch (IllegalArgumentException e) {
+				error("Invalid tag key: '" + name + "'. Tags may only contain a-z, 0-9, _, ., or - characters.");
+				continue;
 			}
-			if (key == null)
+			if (key == null) {
+				error("Invalid tag key: '" + name + "'. Tags may only contain a-z, 0-9, _, ., or - characters.");
```
Comment (ShaneBeee) [inline src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTag.java:107]: NamespacedKeys can also contain `/`

File: src/test/skript/tests/regressions/7471-is tagged or list.sk [hunk 2]
```diff
@@ -0,0 +1,6 @@
+test "is tagged or list":
+	register a custom item tag named "or_list_tag_1" using oak log
+	register a custom item tag named "or_list_tag_2" using spruce log
+
+	loop 10 times:
+		assert oak log is tagged as custom tag "or_list_tag_1" or custom tag "or_list_tag_2"
```
Comment (ShaneBeee) [inline src/test/skript/tests/regressions/7471-is tagged or list.sk:6]: I believe the original issue was relating to `tag A or B`?!?!
Maybe add another check:
`assert oak log is tagged as custom tag "or_list_tag_1" or  "or_list_tag_2"`

I could be totally wrong here.

**Review by ShaneBeee — CHANGES_REQUESTED** [review]
Just a couple small things.

File: src/test/skript/tests/regressions/7471-is tagged or list.sk (hunk 2 above)
Comment (sovdeeth) [reply src/test/skript/tests/regressions/7471-is tagged or list.sk:6]: Well that code works as intended, they should be using tag a or tag b if there want to compare multiple tags

Comment (ShaneBeee) [reply src/test/skript/tests/regressions/7471-is tagged or list.sk:6]: That's fair yeah.

File: src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTag.java [hunk 3]
```diff
@@ -87,14 +92,21 @@ public boolean init(Expression<?>[] expressions, int matchedPattern, Kleenean is
...
+			try {
+				if (name.contains(":")) {
+					key = NamespacedKey.fromString(name);
+				} else {
+					// populate namespace if not provided
+					key = new NamespacedKey(namespace, name);
+				}
+			} catch (IllegalArgumentException e) {
+				error("Invalid tag key: '" + name + "'. Tags may only contain a-z, 0-9, _, ., /, or - characters.");
+				continue;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTag.java:104]:
```suggestion
				key = null;
```
Could we do something like this to avoid duplicating the `error` call?

**Review by APickledWalrus — APPROVED** [review]
