### PR TITLE
Attempt to estimate world in teleport when it's not specified.

### LINKED ISSUE #6610: Skript world changing error
### Skript/Server Version

```markdown
[08:10:31 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[08:10:31 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[08:10:31 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[08:10:31 INFO]: [Skript] Server Version: git-Paper-196 (MC: 1.20.1)
[08:10:31 INFO]: [Skript] Skript Version: 2.8.4 (skriptlang-github)
[08:10:31 INFO]: [Skript] Installed Skript Addons:
[08:10:31 INFO]: [Skript]  - SkBee v3.4.3 (https://github.com/ShaneBeee/SkBee)
[08:10:31 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

Player not teleporting and error in the console (It's not SkBee issue)

### Expected Behavior

The player teleports to the location

### Steps to Reproduce

command /bedwarsadmin [<text>] [<text>] [<text>] [<text>]:
	permission: bedwars.setup
	permission message: You can't do that.
	trigger:
		if arg-1 is not set:
			send "&c/bedwars"
		if arg-1 is "teleportplayer":
			teleport arg-2 parsed as player to {map%arg-3%.team.%arg-4%}

### Errors or Screenshots

https://paste.gg/p/anonymous/35b81dc185244f019564433a5b7d7964

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by Moderocky**
### Description

I previously tried to fix this issue in the Entity utils teleport method, by estimating their target world from their source world if it wasn't specified.

Unfortunately, `EffTeleport` does a lot of stuff that isn't teleporting (like setting the move event target, loading the chunk), so the last patch didn't fix that.

This time I do my best to estimate a location in all cases if I can, or just return if I can't.
It's not ideal, but it's the best we can do to avoid an error while not just failing silently with no feedback for the user about why their teleport did nothing.

## Are there any more of these?

Probably, but the only way to find them would be to check every single usage of `Location` across all 500 and so files, and it's very hit-or-miss whether Bukkit requires a location or not.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** fixes #6610

### CODE REVIEW

File: src/main/java/ch/njol/skript/effects/EffTeleport.java [hunk 1]
```diff
@@ -125,14 +128,26 @@ protected TriggerItem walk(Event e) {
...
+		if (unknownWorld) { // we can't fetch the chunk without a world
+			for (Entity entity : entityArray) {
+				if (entity == null)
+					continue;
+				// assume it's a local teleport, use the first entity we find as a reference
+				loc = new Location(entity.getWorld(), loc.getX(), loc.getY(), loc.getZ(), loc.getYaw(), loc.getPitch());
+				break find_a_world;
+			}
+			return next; // no entities = no chunk = nobody teleporting
+		}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/effects/EffTeleport.java:141]: I'm not 100% convinced this is great, but it seems like a very good assumption most of the time so whatever

**Review by sovdeeth — APPROVED** [review]

File: src/main/java/ch/njol/skript/effects/EffTeleport.java [hunk 2]
```diff
@@ -101,18 +99,23 @@ protected TriggerItem walk(Event e) {
...
 			if (e instanceof PlayerRespawnEvent && entityArray.length == 1 && entityArray[0].equals(((PlayerRespawnEvent) e).getPlayer())) {
+				if (unknownWorld)
+					return next;
 				((PlayerRespawnEvent) e).setRespawnLocation(loc);
 				return next;
 			}
 
 			if (e instanceof PlayerMoveEvent && entityArray.length == 1 && entityArray[0].equals(((PlayerMoveEvent) e).getPlayer())) {
+				if (unknownWorld) // we can approximate the world
+					loc = new Location(((PlayerMoveEvent) e).getFrom().getWorld(), loc.getX(), loc.getY(), loc.getZ(), loc.getYaw(), loc.getPitch());
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/effects/EffTeleport.java:118]: It seems like we would be better off cloning `loc` and setting the world.

File: src/main/java/ch/njol/skript/effects/EffTeleport.java [hunk 3]
```diff
@@ -125,14 +128,26 @@ protected TriggerItem walk(Event e) {
 			return next;
 		}
 
+		find_a_world:
+		if (unknownWorld) { // we can't fetch the chunk without a world
+			for (Entity entity : entityArray) {
+				if (entity == null)
+					continue;
+				// assume it's a local teleport, use the first entity we find as a reference
+				loc = new Location(entity.getWorld(), loc.getX(), loc.getY(), loc.getZ(), loc.getYaw(), loc.getPitch());
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/effects/EffTeleport.java:137]:
```suggestion
				loc = loc.clone();
				loc.setWorld(entity.getWorld());
```

File: src/main/java/ch/njol/skript/effects/EffTeleport.java [hunk 4]
```diff
@@ -101,18 +99,23 @@ protected TriggerItem walk(Event e) {
...
+		boolean unknownWorld = !loc.isWorldLoaded();
 
 		Entity[] entityArray = entities.getArray(e); // We have to fetch this before possible async execution to avoid async local variable access.
 		if (entityArray.length == 0)
 			return next;
 
 		if (!delayed) {
 			if (e instanceof PlayerRespawnEvent && entityArray.length == 1 && entityArray[0].equals(((PlayerRespawnEvent) e).getPlayer())) {
+				if (unknownWorld)
+					return next;
```
[the remark this answers is not in the document]
Comment (Moderocky) [reply src/main/java/ch/njol/skript/effects/EffTeleport.java:111]: I don't like that, in all other places we infer the world *from where they are now* because that's a reasonable assumption, but with respawning it isn't and I don't know if it's okay to substitute a different assumption, since it could mean people get stuck in like a wall in the wrong world in an infinite death loop.

File: src/main/java/ch/njol/skript/effects/EffTeleport.java (hunk 2 above)
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/effects/EffTeleport.java:118]:
```suggestion
				if (unknownWorld) { // we can approximate the world
					loc = loc.clone();
					loc.setWorld(((PlayerMoveEvent) e).getFrom().getWorld());
				}
```

File: src/main/java/ch/njol/skript/effects/EffTeleport.java [hunk 5]
```diff
@@ -125,14 +128,27 @@ protected TriggerItem walk(Event e) {
...
 		}
 
+		if (unknownWorld) { // we can't fetch the chunk without a world
+			if (entityArray.length == 1) { // if there's 1 thing we can borrow its world
+				Entity entity = entityArray[0];
+				if (entity == null)
+					return next;
+				// assume it's a local teleport, use the first entity we find as a reference
+				loc = new Location(entity.getWorld(), loc.getX(), loc.getY(), loc.getZ(), loc.getYaw(),
+								   loc.getPitch());
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/effects/EffTeleport.java:138]:
```suggestion
				loc = loc.clone();
				loc.setWorld(entity.getWorld());
```

**Review by APickledWalrus — APPROVED** [review]
