### PR TITLE
Fix exception when no world available to explode effect.

### LINKED ISSUE #6481: createExplosion with no world in location throws exception
### Skript/Server Version

```markdown
2.8.3
Spigot Paper 1.20.1
```

### Bug Description

```
[14:41:47] [Server thread/ERROR]: #!#! Stack trace:
[14:41:47] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.World.createExplosion(org.bukkit.Location, float, boolean)" because the return value of "org.bukkit.Location.getWorld()" is null
[14:41:47] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffExplosion.execute(EffExplosion.java:85)
[14:41:47] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[14:41:47] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:41:47] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[14:41:47] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[14:41:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:41:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[14:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[14:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[14:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[14:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[14:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:41:47] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:41:47] [Server thread/ERROR]: #!#! 
[14:41:47] [Server thread/ERROR]: #!#! Version Information:
[14:41:47] [Server thread/ERROR]: #!#!   Skript: (custom version)
[14:41:47] [Server thread/ERROR]: #!#!     Flavor: selfbuilt-unknown
[14:41:47] [Server thread/ERROR]: #!#!     Date: unknown
[14:41:47] [Server thread/ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[14:41:47] [Server thread/ERROR]: #!#!   Minecraft: 1.20.1
[14:41:47] [Server thread/ERROR]: #!#!   Java: 17.0.8.1 (OpenJDK 64-Bit Server VM 17.0.8.1+8-LTS)
[14:41:47] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.10.0-24-amd64
[14:41:47] [Server thread/ERROR]: #!#! 
[14:41:47] [Server thread/ERROR]: #!#! Server platform: Paper
[14:41:47] [Server thread/ERROR]: #!#! 
[14:41:47] [Server thread/ERROR]: #!#! Current node: null
[14:41:47] [Server thread/ERROR]: #!#! Current item: create explosion effect {_vector} (as ch.njol.skript.util.Direction) {5::dam} offset by vector(0, 20, 0)
[14:41:47] [Server thread/ERROR]: #!#! Current trigger: function breakDam (simple event) (5/5.sk, line 21)
```

### Expected Behavior

To not throw an exception

### Steps to Reproduce

Run the EffExplosion effect with a location that has no world.

### PR DESCRIPTION
**Pull request by Moderocky**
### Description

Adds a check for the location having a world in the create explosion effect.
If there is no world present then the effect will not occur (since we do not know where it should take place!)

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** closes #6481

### CODE REVIEW

File: src/main/java/ch/njol/skript/effects/EffExplosion.java [hunk 1]
```diff
@@ -78,11 +78,13 @@ public void execute(final Event e) {
 		final Number power = force != null ? force.getSingle(e) : 0;
 		if (power == null)
 			return;
-		for (final Location l : locations.getArray(e)) {
+		for (Location location : locations.getArray(e)) {
+			if (location.getWorld() == null)
```
Comment (Moderocky) [inline src/main/java/ch/njol/skript/effects/EffExplosion.java:82]: It's technically *possible* we could extract a location by checking whether only one world exists or looking for the default entity in the current event or whatever, but that feels like a really patchwork solution and in all other similar syntax we just skip it/return null when the world's null.

**Review by sovdeeth — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]
