### PR TITLE
Fix event data pollution for event priority

### LINKED ISSUE #6288: event priority fails
### Skript/Server Version

```markdown
> sk info
[17:18:44 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:18:44 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[17:18:44 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:18:44 INFO]: [Skript] Server Version: git-Paper-365 (MC: 1.20.4)
[17:18:44 INFO]: [Skript] Skript Version: 2.8.0-pre1 (skriptlang-github)
[17:18:44 INFO]: [Skript] Installed Skript Addons: None
[17:18:44 INFO]: [Skript] Installed dependencies: 
[17:18:44 INFO]: [Skript]  - Vault v1.7.3-b131
[17:18:44 INFO]: [Skript]  - WorldGuard v7.0.10-SNAPSHOT+2260-c7319f1
[17:18:44 INFO]: [Skript]  - Residence v5.1.4.1
```

### Bug Description

Scripts containing various time events fails to load. Examples may be found below.

### Expected Behavior

Clean parsing and execution

### Steps to Reproduce

- Update to Skript 2.8.0-pre1
- Start server
- Reload scripts
- Read console/log

### Errors or Screenshots

```
> sk reload scripts
[17:17:25 INFO]: [Skript] Reloading all scripts...
[17:17:25 INFO]: Line 19: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: at 06:00 in world "world_blackdog":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 21: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: at 18:00 in world "world_blackdog":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 24: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: at 06:00 in world "world_city":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 26: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: at 18:00 in world "world_city":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 29: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: at 06:00 in world "world_yellowdog":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 31: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: at 18:00 in world "world_yellowdog":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 68: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: every 1 minutes in "world_lobby":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 132: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: every 2 minutes in "world":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 178: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: every 2 minutes in "world_yellowdog":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 218: (periodicals.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: every 10 minutes in "world_lobby":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 55: (start-acid-rain.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: every 127 seconds in "world_whitedog":
[17:17:25 INFO]:  
[17:17:25 INFO]: Line 86: (start-acid-rain.sk)
[17:17:25 INFO]:     This event doesn't support event priority
[17:17:25 INFO]:     Line: every 107 seconds in "world_yellowdog":
```

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by sovdeeth**
### Description

Sets priority to null if not specified. Fixes #6288 

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6288

### CODE REVIEW

**Review by UnderscoreTud — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
Shouldn't the event be parsed first, then use the priority given from the EventData rather than setting it to null. This way any SkriptEvent can set priority in it's init method by setting the EventData. This could be used by add-ons (skript-reflect).

**Comment by sovdeeth** [comment]
> Shouldn't the event be parsed first, then use the priority given from the EventData rather than setting it to null. This way any SkriptEvent can set priority in it's init method by setting the EventData. This could be used by add-ons (skript-reflect).

Currently, the SkriptEvent can set the priority in its init method, by setting its own `eventPriority` field.

**Comment by TheLimeGlass** [comment]
> > Shouldn't the event be parsed first, then use the priority given from the EventData rather than setting it to null. This way any SkriptEvent can set priority in it's init method by setting the EventData. This could be used by add-ons (skript-reflect).
> 
> Currently, the SkriptEvent can set the priority in its init method, by setting its own `eventPriority` field.

So then shouldn't it respect the existing priority rather than clearing it and using the user input? If an add-on goes out of it's way to set the priority, it needs that priority. Like reading an event that another plugin may cancel before Skript.

**Comment by sovdeeth** [comment]
> > > Shouldn't the event be parsed first, then use the priority given from the EventData rather than setting it to null. This way any SkriptEvent can set priority in it's init method by setting the EventData. This could be used by add-ons (skript-reflect).
> > 
> > 
> > Currently, the SkriptEvent can set the priority in its init method, by setting its own `eventPriority` field.
> 
> So then shouldn't it respect the existing priority rather than clearing it and using the user input? If an add-on goes out of it's way to set the priority, it needs that priority. Like reading an event that another plugin may cancel before Skript.

EventData is simply used to transfer data from StructEvent to SkriptEvent. The data begins at StructEvent, when the written code is parsed to see if the user defined a priority. We first clear any old data that was there from other events (set to null), then set it to whatever the user inputted, or leave it null if they didn't input anything.

Then we move the `SkriptEvent#init()`, where that value is read into `eventPriority` and checked against the event's setting for supporting user-defined event priorities. Finally, the SkriptEvent's other `init()`, the one defined by the specific syntax. This method has free reign to see the existing priority, overwrite it with their own priority, or do nothing. 

Let me know if that makes sense or if I'm missing something that you're saying.

**Review by AyhamAl-Ali — APPROVED** [review]

File: src/main/java/ch/njol/skript/structures/StructEvent.java [hunk 1]
```diff
@@ -46,8 +46,10 @@ public class StructEvent extends Structure {
 	@SuppressWarnings("ConstantConditions")
 	public boolean init(Literal<?>[] args, int matchedPattern, ParseResult parseResult, EntryContainer entryContainer) {
 		String expr = parseResult.regexes.get(0).group();
+		EventData data = getParser().getData(EventData.class);
+		data.priority = null;
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/structures/StructEvent.java:50]: it might be better to set it to null when we are done with parsing the SkriptEvent rather than before?

Comment (sovdeeth) [reply src/main/java/ch/njol/skript/structures/StructEvent.java:50]: I mean it might be good to set null on both sides, but I think it's more defensive to set it to null before.

**Review by APickledWalrus — APPROVED** [review]
