### PR TITLE
Fix plural identification for class infos in patterns.

### LINKED ISSUE #7253: ClassInfo CodeName
### Skript/Server Version

```markdown
Any/All
```

### Bug Description

When registering a ClassInfo with the singular codename ending with an `i`, `Utils#getEnglishPlural()` improperly marks it as plural and returns the codename with an `us` ending, even though it should be singular and not return with a different ending.
Causing `Classes#getClassInfo()` to throw a SkriptAPIException for an invalid/unregistered codename

### Expected Behavior

The singular codename ending with an `i` not to be marked as plural.

### Steps to Reproduce

Register a new  ClassInfo with the singular codename ending in an `i`,
Make an element using the codename in the pattern as an expression,
Call the element and look at console

### Errors or Screenshots

_No response_

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by Moderocky**
### Description

A follow-up to [this fix](<https://github.com/SkriptLang/Skript/pull/6982>).
This makes plural detection first check if the word could be singular.

Words like `gui` already had correct plural forms (`-ui` -> `-uis`), but when plurality was checked, the singular was identified as a plural because it matched the `-i` plural ending.

Now, it will check if it matches a singular pattern _before_ checking if it matches a plural pattern.
**Note**: it is possible this may break some obscure word (that looks like the singular form of another word) but none of the existing class infos break, so I'm assuming it's probably fine.

This also adds a special method for addons to register specific word overrides, so if there _are_ any future problems, they can be fixed specifically with `Utils.addPluralOverride("foot", "feet")` (for example).
This uses a special 'complete word' mode to make sure that specific overrides won't interfere with any existing plural endings.

I also made some corrections to annoying `-ves` endings (wolves, shelves, calves etc.).

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6982, fixes #7253

### CODE REVIEW

File: src/main/java/ch/njol/skript/util/Utils.java [hunk 1]
```diff
@@ -285,14 +293,55 @@ public static File getFile(Plugin plugin) {
...
-				return new NonNullPair<>(word.substring(0, word.length() - ending.plural().length()) + ending.singular().toUpperCase(Locale.ENGLISH), Boolean.TRUE);
+			if (ending.singular().isBlank())
+				continue;
+			if (ending.isCompleteWord() && ending.singular().length() != word.length())
+				continue; // Skip complete words
+
+			if (word.endsWith(ending.singular()) || word.toLowerCase().endsWith(ending.singular())) {
+				return true;
+			}
 		}
```
Comment (Moderocky) [inline src/main/java/ch/njol/skript/util/Utils.java]: Git chose an insane way to diff this. It's two separate methods, in case that isn't clear.

**Review by TheAbsolutionism — APPROVED** [review]

**Comment by TheAbsolutionism** [comment]
Though it looks good, iirc when I did my testing, it only actually threw the exception/error when calling the element and not just by registering it.

**Review by Efnilite — APPROVED** [review]

**Review by sovdeeth — APPROVED** [review]
