### PR TITLE
Fix ExprXOf CCE

### LINKED ISSUE #1747: Issue with Returning Items from a Function
### Description
Functions that return multiple items (e.g. 2 diamonds) in reality return ```<none>```

### Steps to Reproduce
```
function test(c: number) :: item:
    set {_gem} to diamond
    return {_c} of {_gem}
    
function test2(c: number) :: item:
    return {_c} of diamond

command /testfunction:
    trigger:
        give player test(1) #Should give the command sender 1 diamond
        send "test(): Attempting to give %player% %test(1)%"
        give player test(2) #Should give the command sender 2 diamonds
        send "test(): Attempting to give %player% %test(2)%"
        give player test2(1) #Should give the command sender 1 diamond
        send "test2(): Attempting to give %player% %test2(1)%"
        give player test2(2) #Should give the command sender 2 diamonds
        send "test2(): Attempting to give %player% %test2(2)%"
        #In total, the command sender should recieve 6 diamonds, 3 from test() and 3 from test2()
```

### Expected Behavior
The player should receive 6 diamonds

### Errors / Screenshots

image

Note: After executing /testfunction, the player only recieves 3 diamonds (from test2())

### Server Information
* **Server version/platform:**       1.12.2 (Paper)
* **Skript version:**                2.3-beta4

### Additional Context
This issue didn't occur in Skript 2.2-dev37c, and only occurred when I updated the version of Skript (2.3-beta4)

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
The code removed (`getConvertedExpression`) was originally meant to fix #1747, see [commit](https://github.com/SkriptLang/Skript/commit/43e1d26ac38bb816c410dbd1174c96264e5b20d8). However, removing this code no longer produces this issue, so I presume the main cause was fixed at some point.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3814

### CODE REVIEW

File: src/main/java/ch/njol/skript/expressions/ExprXOf.java [hunk 1]
```diff
@@ -45,75 +43,53 @@
...
 	}
-	
-	@SuppressWarnings("null")
-	Expression<Number> amount;
-	
-	@SuppressWarnings({"unchecked", "null"})
+
+	private Expression<Number> amount;
+
+	@SuppressWarnings("unchecked")
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/expressions/ExprXOf.java:53]: Should come after Override. Not sure why but it won't let me make a suggestion.

File: src/main/java/ch/njol/skript/expressions/ExprXOf.java [hunk 2]
```diff
@@ -45,75 +43,53 @@
...
-					final EntityType t = ((EntityType) o).clone();
-					t.amount = a.intValue();
-					return t;
-				}
+	protected Object[] get(Event e, Object[] source) {
+		Number a = amount.getSingle(e);
+
+		return get(source, o -> {
+			if (a == null)
+				return null;
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/expressions/ExprXOf.java:68]: Will this check be ran for every source object? If so, should it just be down outside of get?

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
Two little things. Other than that, looks good to me as long as this all still works error free 😎😎

**Review by APickledWalrus — APPROVED** [review]
