### PR TITLE
Apply new line (`%nr%`) in item lore correctly

### LINKED ISSUE #3544: Make newline work in lore and tellraw
I always loved SkQuery's new line feature, it just works everywhere with no problem at all.

I was happy when skript added their own but after trying it I found out that it doesn't work with `/tellraw` command nor item lore.

As for item lore there will be someone that will say use `with lore "" and ""` but that is just not functional nor nice, it is not just about `few more chars` many people just like the simplicity of `||` or `%nl%` when making new lines in lore.

and it is even better to have multiple ways to make new lines in item lore
I hope you got my point.

For `item lore` the second line and all lines below just doesn't appear and for `tellraw` it says `Expected whitespace to end one argument, but found trailing data`

Thank you.

### PR DESCRIPTION
**Pull request by Monchi**
### Description
Apply new line (`%nr%`) in item lore. It seems that #2505 forgot this.

e.g.
`1 of stone with lore "first line%nl%second line"`

[The test case](https://github.com/SkriptLang/Skript/pull/3636/files#diff-840322c377d70914e2d9a5072c844f83cbf7155c5ba9b3caaa60ee37d3b4cf5a) describes the behavior well.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3544.

### CODE REVIEW

File: src/main/java/ch/njol/skript/expressions/ExprItemWithLore.java [hunk 1]
```diff
@@ -62,10 +64,13 @@ public boolean init(Expression<?>[] exprs, int matchedPattern, Kleenean kleenean
 
 	@Override
 	protected ItemType[] get(Event e, ItemType[] source) {
-		String[] lore = this.lore.getArray(e);
+		List<String> lore = Arrays.stream(this.lore.getArray(e))
```
Comment (Pikachu920) [inline src/main/java/ch/njol/skript/expressions/ExprItemWithLore.java:67]: stream looks nice, but you should be able to replace the Arrays#stream call with `this.lore.stream(e)`

**Review by Pikachu920 — CHANGES_REQUESTED** [review]

File: src/main/java/ch/njol/skript/expressions/ExprItemWithLore.java (hunk 1 above)
Comment (Monchi) [reply src/main/java/ch/njol/skript/expressions/ExprItemWithLore.java]: Thanks. I didn't know about such a nice method!

**Review by Pikachu920 — DISMISSED** [review]

**Review by ShaneBeee — DISMISSED** [review]

**Review by ShaneBeee — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]
