### PR TITLE
Resolve ResourceKeyInvalidException

### LINKED ISSUE #2412: Non [a-z0-9/._-] sound name causes severe error
### Description
Trying to play a sound with a non [a-z0-9/._-] name results in a severe error

### Steps to Reproduce
Run this piece of code in any trigger:
`play sound "sound name with a space" at all players`

### Expected Behavior
The sound shouldn't play and no error should be given.

### Errors / Screenshots
```
#!#!
#!#! [Skript] Severe Error:
#!#!
#!#! Something went horribly wrong with Skript.
#!#! This issue is NOT your fault! You probably can't fix it yourself, either.
#!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
#!#! Here is full list of them:
#!#! skript-mirror (https://github.com/btk5h/skript-mirror)
#!#! We could not identify which of those are specially related, so this might also be Skript issue.
#!#! You should try disabling those plugins one by one, trying to find which one causes it.
#!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
#!#! In that case, you will be given instruction on how should you report it.
#!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
#!#! Only if the author tells you to do so, report it to Skript's issue tracker.
#!#!
#!#! Stack trace:
#!#! net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:nonexistent sound here
#!#! at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38)
#!#! at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43)
#!#! at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.playSound(CraftWorld.java:2079)
#!#! at ch.njol.skript.effects.EffPlaySound.playSound(EffPlaySound.java:187)
#!#! at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:153)
#!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
#!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
#!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
#!#! at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:278)
#!#! at ch.njol.skript.command.Commands$3$1.call(Commands.java:211)
#!#! at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
#!#! at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
#!#! at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
#!#! at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147)
#!#! at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
#!#! at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
#!#! at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
#!#! at java.lang.Thread.run(Thread.java:748)
#!#!
#!#! Version Information:
#!#! Skript: 2.4-beta5 (latest)
#!#! Flavor: skriptlang-github
#!#! Date: 2019-08-04
#!#! Bukkit: 1.14.4-R0.1-SNAPSHOT
#!#! Minecraft: 1.14.4
#!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
#!#! OS: Linux amd64 4.4.0-143-generic
#!#!
#!#! Server platform: Paper
#!#!
#!#! Current node: null
#!#! Current item: play sound "nonexistent sound here" at (me >> ch.njol.skript.classes.Converter$ConverterUtils$1@348ca083: commandsender -> location)
#!#!
#!#! Thread: Server thread
#!#!
#!#! Language: english
#!#! Link parse mode: DISABLED
#!#!
#!#! End of Error.
#!#!
```

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description

Fixes #2412 by adding a regex check each iteration of the sound array

---
**Target Minecraft Versions:**     Any
**Requirements:**     None
**Related Issues:**     #2412

### CODE REVIEW

**Comment by Wealthyturtle** [comment]
> 1. The regex forces the sound name to be only one character
> 2. The `/` character needs to be escaped using `\` in regex, and this also needs to be escaped using another `\` because java.
> 3. The check should only be done if soundEnum is null
> 4. The sound name should be converted to lower case before the check
> 5. **`if(`** -> **`if (`** (code style)
> 6. Add a white space after `//` (code style)
> 
> Final regex: `[a-z0-9\/._-]+` in a java string: `[a-z0-9\\/._-]+`
> https://regex101.com

Thanks for the feedback. I've modified the regex string and placed it in ``SOUND_VALID_CHARACTERS`` to reduce duplication of the regex string (in case Mojang ever decides to change the rule), and I've also converted the individual ``sound`` Strings to lowercase beforehand in addition to following the code style.

**Comment by Blueyescat** [comment]
But you done it wrong, why would it convert to lower case and then to upper case again
image

---
However, actually just adding a try catch should be faster, because no additional regex:
```java
// It may throw an exception if there are invalid characters in the sound name
try {
	p.playSound(location, sound, category, volume, pitch);
} catch (Exception ignored) {}
```

**Comment by Wealthyturtle** [comment]
So sorry, forgot about the inefficiency of swapping cases twice... I've swapped from the regex checks to the exception catch ahhh

**Comment by Blueyescat** [comment]
@bensku currently there is no an exception by Spigot, but true, if Minecraft didn't throw the exception we couldn't know the problem. But we can't handle that specific exception, also i don't think this is a good reason to add another format check. Can we make it so it will print the exception if debug mode is on?

**Comment by bensku** [comment]
Requirements for sound names are documented in Minecraft Wiki. Validating against them should be enough.

**Comment by Blueyescat** [comment]
I'm talking about unnecessary little performance loss

**Comment by Wealthyturtle** [comment]
Reverted back to Regex as requested

**Comment by FranKusmiruk** [comment]
> I'm talking about unnecessary little performance loss

Exceptions should be handled when possible, catching them is not always ideal. And the performance isn't something to worry about in this specific case, if anything, a compiled pattern could be used.

**Comment by Blueyescat** [comment]
It will run regex every time you play a sound, for no reason. You would not do this in Java, you would store the correct sound name. The exception doesn’t exist in the API anyways, so not Skript’s problem. The try/catch method should be used. Make it print the exception if in debug mode if you want..

**Comment by Wealthyturtle** [comment]
How about this, it catches all Exceptions, but once it catches an Exception, it gets the class of the Exception, and converts the class into a String. If it contains “ResourceKeyInvalidException” with the exact error message, then it’ll ignore it, else it will throw it back out? That way, no use of NMS, while still handling only the ResourceKeyInvalidException and not messing around with any other exceptions?

**Comment by Matocolotoe** [comment]
Why converting the class name into a string

**Comment by Wealthyturtle** [comment]
In my original code (the first commit), I only swapped cases once - for the enum parsing, but otherwise whatever sound name the user provides will be used. The issue was that’s Skript would display the error of ResourceKeyInvalidException when a name was deemed invalid by Minecraft, and that’s not what should occur (Skript should suppress that exception and that exception only). 

Due to the coding convention rules on no NMS import, and the exception is thrown from Minecraft itself, not Spigot/Paper, there’s no real way to catch only that exception without using Class -> String conversion.

Ultimately, as bensku and FranKusmiruk have mentioned earlier, it is not appropriate for Skript to ignore all exceptions, hence I thought of that Class -> String converter for handling the exception. As for double case conversion, it doesn’t need to be done if we just leave it up to the user to provide the specific sound name that Minecraft expects without any intermediate case changing by Skript

File: src/main/java/ch/njol/skript/effects/EffPlaySound.java [hunk 1]
```diff
@@ -55,7 +55,8 @@
 public class EffPlaySound extends Effect {
 
 	private static final boolean SOUND_CATEGORIES_EXIST = Skript.classExists("org.bukkit.SoundCategory");
-
+	private static final String SOUND_VALID_CHARACTERS = "[a-z0-9\\/._-]+"; // Minecraft only accepts these characters
```
Comment (FranKusmiruk) [inline src/main/java/ch/njol/skript/effects/EffPlaySound.java]: Instead of having it as a String, I'd compile a Pattern here and then use a matcher when needed.
