### PR TITLE
Temporary fix for plural endings error.

### LINKED ISSUE #5879: Addon development: creating a type with "gui" in its name causes a weird error.
### Skript/Server Version

```markdown
Skript 2.6.4
Server version 1.20.1
```

### Bug Description

Hello, I am working on updating my Addon Skript-AnvilGUI.

Whenever I try to rename the type codename to "anvilgui" or "virtualanvilgui", it prints an error in the console, and refers to the type as "virtualanvilguu"

### Expected Behavior

It should find the class "virtualanvilgui"

### Steps to Reproduce

Add the word "anvilgui" or "gui" to any classinfo in your addon.

### Errors or Screenshots

```
: #!#! 
[15:28:54 ERROR]: #!#! [Skript] Severe Error:
[15:28:54 ERROR]: #!#! Could not load testanvil.sk
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! Something went horribly wrong with Skript.
[15:28:54 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:28:54 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:28:54 ERROR]: #!#! Here is full list of them:
[15:28:54 ERROR]: #!#! Skript-AnvilGUI v1.2 
[15:28:54 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:28:54 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:28:54 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:28:54 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:28:54 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:28:54 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! Stack trace:
[15:28:54 ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: org.derewah.skriptanvilgui.effects.EffOpenAnvilGUI
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[15:28:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:28:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:28:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1112)
[15:28:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:28:54 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:28:54 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: open (anvilgui|anvil gui) %virtualanvilgui% to %player%]
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[15:28:54 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[15:28:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:28:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:28:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1112)
[15:28:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:28:54 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:28:54 ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for virtualanvilguus
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[15:28:54 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[15:28:54 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[15:28:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:28:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:28:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1112)
[15:28:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:28:54 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! Version Information:
[15:28:54 ERROR]: #!#!   Skript: 2.6.4 (latest)
[15:28:54 ERROR]: #!#!     Flavor: skriptlang-github
[15:28:54 ERROR]: #!#!     Date: 17:14:25.041218900
[15:28:54 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[15:28:54 ERROR]: #!#!   Minecraft: 1.20.1
[15:28:54 ERROR]: #!#!   Java: 17.0.7 (Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-224)
[15:28:54 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! Server platform: Paper
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! Current node: open anvil gui {_x} to player (testanvil.sk, line 4)
[15:28:54 ERROR]: #!#! Current item: null
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! Thread: Server thread
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! Language: english
[15:28:54 ERROR]: #!#! Link parse mode: DISABLED
[15:28:54 ERROR]: #!#! 
[15:28:54 ERROR]: #!#! End of Error.
[15:28:54 ERROR]: #!#! 
```

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### LINKED ISSUE #6981: Plural issue
### Skript/Server Version

```markdown
[21:42:31 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:42:31 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:42:31 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:42:31 INFO]: [Skript] Server Version: 1.21-109-5a5035b (MC: 1.21)
[21:42:31 INFO]: [Skript] Skript Version: 2.9.1 (skriptlang-github)
[21:42:31 INFO]: [Skript] Installed Skript Addons:
[21:42:31 INFO]: [Skript]  - skript-reflect v2.5.1 (https://github.com/SkriptLang/skript-reflect)
[21:42:31 INFO]: [Skript]  - Lusk v1.3
[21:42:31 INFO]: [Skript]  - Bitshift v1.0
[21:42:31 INFO]: [Skript]  - SkBee v3.6.0 (https://github.com/ShaneBeee/SkBee)
[21:42:31 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

codename ending in "gui" becomes "guus"

### Expected Behavior

should become guis

### Steps to Reproduce

```
        Classes.registerClass(new ClassInfo<>(CLASS.class, "anythinggui")
                .user("anvil ?guis?")
                .name("Anvil Gui")
                .description("An anvil gui.") // add example
                .since("1.3")
                .parser(new Parser<>() {
                    @Override
                    public boolean canParse(final @NotNull ParseContext context) {
                        return false;
                    }

                    @Override
                    public @NotNull String toString(final AnvilGuiWrapper a, final int flags) {
                        return a.toString();
                    }

                    @Override
                    public @NotNull String toVariableNameString(final AnvilGuiWrapper a) {
                        return a.toString();
                    }

                    @Override
                    public @NotNull String getDebugMessage(final AnvilGuiWrapper a) {
                        return toString(a, 0) + " anvil gui (" + a + ")";
                    }
                }));
```

### Errors or Screenshots

[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! [Skript] Severe Error:
[21:10:14 ERROR]: #!#! An error occurred while trying to load a Structure.
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! Something went horribly wrong with Skript.
[21:10:14 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:10:14 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:10:14 ERROR]: #!#! Here is full list of them:
[21:10:14 ERROR]: #!#! skript-reflect v2.5.1 (https://github.com/SkriptLang/skript-reflect) Lusk v1.3 SkBee v3.6.0 (https://github.com/ShaneBeee/SkBee) Bitshift v1.0
[21:10:14 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[21:10:14 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:10:14 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:10:14 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:10:14 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:10:14 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! Stack trace:
[21:10:14 ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: it.jakegblp.lusk.elements.plugins.anvilgui.effects.EffAnvilGuiOpen (provided by Lusk)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:239)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Statement.parse(Statement.java:65)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:967)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.loadCode(Section.java:93)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.loadOptionalCode(Section.java:167)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.sections.SecLoop.init(SecLoop.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.init(Section.java:67)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.parse(Section.java:178)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnHandler.lambda$loadReturnableTrigger$1(ReturnHandler.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnableTrigger.<init>(ReturnableTrigger.java:36)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnHandler.loadReturnableTrigger(ReturnHandler.java:119)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:54)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.structures.StructFunction.load(StructFunction.java:120)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:570)
[21:10:14 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1756)
[21:10:14 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1744)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:561)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:513)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.Skript$1.run(Skript.java:853)
[21:10:14 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[21:10:14 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[21:10:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
[21:10:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:10:14 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[21:10:14 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [lusk] open anvil[(-| )gui] %anvilgui% to %player%]
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:56)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1742)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1322)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:232)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Statement.parse(Statement.java:65)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:967)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.loadCode(Section.java:93)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.loadOptionalCode(Section.java:167)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.sections.SecLoop.init(SecLoop.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.init(Section.java:67)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.parse(Section.java:178)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnHandler.lambda$loadReturnableTrigger$1(ReturnHandler.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnableTrigger.<init>(ReturnableTrigger.java:36)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnHandler.loadReturnableTrigger(ReturnHandler.java:119)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:54)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.structures.StructFunction.load(StructFunction.java:120)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:570)
[21:10:14 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1756)
[21:10:14 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1744)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:561)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:513)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.Skript$1.run(Skript.java:853)
[21:10:14 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[21:10:14 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[21:10:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
[21:10:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:10:14 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[21:10:14 ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for anvilguus
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:270)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:96)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:140)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:51)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1742)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1322)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:232)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Statement.parse(Statement.java:65)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:967)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.loadCode(Section.java:93)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.loadOptionalCode(Section.java:167)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.sections.SecLoop.init(SecLoop.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.init(Section.java:67)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Section.parse(Section.java:178)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnHandler.lambda$loadReturnableTrigger$1(ReturnHandler.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnableTrigger.<init>(ReturnableTrigger.java:36)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.ReturnHandler.loadReturnableTrigger(ReturnHandler.java:119)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:54)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:124)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.structures.StructFunction.load(StructFunction.java:120)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:570)
[21:10:14 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1756)
[21:10:14 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1744)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:561)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[21:10:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:513)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[21:10:14 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.Skript$1.run(Skript.java:853)
[21:10:14 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[21:10:14 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[21:10:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
[21:10:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:10:14 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! Version Information:
[21:10:14 ERROR]: #!#!   Skript: 2.9.1 (latest)
[21:10:14 ERROR]: #!#!     Flavor: skriptlang-github
[21:10:14 ERROR]: #!#!     Date: 14:17:55.682181900
[21:10:14 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[21:10:14 ERROR]: #!#!   Minecraft: 1.21
[21:10:14 ERROR]: #!#!   Java: 22.0.1 (Java HotSpot(TM) 64-Bit Server VM 22.0.1+8-16)
[21:10:14 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! Server platform: Paper
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! Current node: send "&e[STAFF] %{_player}'s prefix% &6%{_player}%: &7%loop-value%" to {_staff::*} (staffchat.sk, line 16)
[21:10:14 ERROR]: #!#! Current item: null
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! Thread: Server thread
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! Language: english
[21:10:14 ERROR]: #!#! Link parse mode: DISABLED
[21:10:14 ERROR]: #!#!
[21:10:14 ERROR]: #!#! End of Error.
[21:10:14 ERROR]: #!#!

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by Moderocky**
### Description

Some plural word endings are incorrectly detected, e.g. `-us` -> `-i` picks up "gui" as being a plural of (the well known word) "guus", and `-fe` -> `-ves` picks up "objectives" as being a plural of "objectife".

This PR patches these two cases _for now_ (by adding an alternative first) and I've moved to a queue and a helper class rather than a fixed-size array to make the follow-up API a little easier: you should be able to add stuff to the beginning or end of the queue without trouble.

I'd like to follow up with a proper system for doing this a little more effectively, and the ability for addons to fix any of their own problematic cases by registering plural overrides.
That's probably out of scope for a patch version so it will likely be a 2.10 feature, maybe using some registrations stuff?

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** fixes #6981, fixes #5879

### CODE REVIEW

**Review by APickledWalrus — APPROVED** [review]

**Comment by Moderocky** [comment]
So the test uses `knife` -> `knives` which was broken by the `ive` -> `ives` change.
It seems like there are significantly more `ive` words than `ife` words, so I chose to add the `ife` words manually.

They all seem to be compounds of `*life`, `*wife` or `*knife` so I just added those three endings. I did not add `*rife` because no compound word is ever a noun that would be pluralised.

File: src/main/java/ch/njol/skript/util/Utils.java [hunk 1]
```diff
@@ -239,80 +278,43 @@ public static File getFile(Plugin plugin) {
...
 	 */
-	public static String toEnglishPlural(final String s) {
-		assert s != null && s.length() != 0;
-		for (final String[] p : plurals) {
-			if (s.endsWith(p[0]))
-				return s.substring(0, s.length() - p[0].length()) + p[1];
+	public static String toEnglishPlural(final String word) {
+		assert word != null && word.length() != 0;
+		for (final WordEnding ending : plurals) {
+			if (word.endsWith(ending.singular()))
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/util/Utils.java:308]:
```suggestion
	public static String toEnglishPlural(String word) {
		assert word != null && word.length() != 0;
		for (WordEnding ending : plurals) {
			if (word.endsWith(ending.singular()))
```

File: src/main/java/ch/njol/skript/util/Utils.java [hunk 2]
```diff
@@ -239,80 +278,43 @@ public static File getFile(Plugin plugin) {
...
 	/**
-	 * @param s trimmed string
+	 * @param word trimmed string
 	 * @return Pair of singular string + boolean whether it was plural
 	 */
 	@SuppressWarnings("null")
-	public static NonNullPair<String, Boolean> getEnglishPlural(final String s) {
-		assert s != null;
-		if (s.isEmpty())
+	public static NonNullPair<String, Boolean> getEnglishPlural(final String word) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/util/Utils.java:286]:
```suggestion
	public static NonNullPair<String, Boolean> getEnglishPlural(String word) {
```

File: src/main/java/ch/njol/skript/util/Utils.java [hunk 3]
```diff
@@ -239,80 +278,43 @@ public static File getFile(Plugin plugin) {
...
-			// general ending
-			{"", "s"},
-	};
-	
 	/**
-	 * @param s trimmed string
+	 * @param word trimmed string
 	 * @return Pair of singular string + boolean whether it was plural
 	 */
 	@SuppressWarnings("null")
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/util/Utils.java:285]: it'd be nice to move this to a noinspection if feasible

**Review by sovdeeth — CHANGES_REQUESTED** [review]

**Review by sovdeeth — APPROVED** [review]
