### PR TITLE
Sub Entity Data Fix

### LINKED ISSUE #7491: Wind charge projectile is fireball
### Skript/Server Version

```markdown
[22:13:57 INFO]: [Skript] Server Version: 1.21.3-2358-16ce24a (MC: 1.21.3)
[22:13:57 INFO]: [Skript] Skript Version: 2.10.0 (skriptlang-github)
[22:13:57 INFO]: [Skript] Installed Skript Addons: 
[22:13:57 INFO]: [Skript]  - ItemsAdder v4.0.7-beta-9 (devs.beer)
[22:13:57 INFO]: [Skript]  - skript-db v1.3.9
[22:13:57 INFO]: [Skript]  - skript-placeholders v1.7.0 (https://github.com/APickledWalrus/skript-placeholders)
[22:13:57 INFO]: [Skript]  - skript-itemsadder v1.6.1
[22:13:57 INFO]: [Skript]  - SkBee v3.8.1 (https://github.com/ShaneBeee/SkBee)
[22:13:57 INFO]: [Skript] Installed dependencies: 
[22:13:57 INFO]: [Skript]  - Vault v1.7.3-b131
[22:13:57 INFO]: [Skript]  - WorldGuard v7.0.13-beta-1+2f13ae0
```

### Bug Description

Wind charge projectile is fireball.
Cant kill wind charge projectile or cancel event

### Expected Behavior

Make wind charge wind charge 

### Steps to Reproduce

```
on projectile hit:
	if projectile is an wind charge or fireball:
		broadcast "%event-projectile%"
		kill projectile
		cancel event
```

### Errors or Screenshots

_No response_

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by TheAbsolutionism**
### Description
This PR aims to:
- Fix #7491 allowing users to detect if a projectile is a wind charge or wither skull
- Future proofing for any other entities that extend another entity
- Adds tests for entities extending another entity, such as: small fireball, large fireball, dragon fireball, wind charge and wither skull
- Adds fireball, wind charge and wither skull to the all entities test within `EffSecSpawn.sk`

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7491

### CODE REVIEW

**Comment by TheAbsolutionism** [comment]
Tests will fail because it requires https://github.com/SkriptLang/skript-aliases/pull/125

**Comment by TheAbsolutionism** [comment]
Proof that the PR in `skript-alias` indeed fixes the issue:

https://github.com/user-attachments/assets/a9c99213-e1cc-4b54-8360-049dce0e15f1

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 1]
```diff
@@ -44,42 +44,33 @@ public abstract class EntityData<E extends Entity> implements SyntaxElement, Ygg
...
 		} catch (NoSuchMethodException | SecurityException ignored) { /* We already checked if the method exists */ }
 	}
 
-	private static final boolean HAS_ENABLED_BY_FEATURE = Skript.methodExists(EntityType.class, "isEnabledByFeature", World.class);
-	public final static String LANGUAGE_NODE = "entities";
+	private static boolean HAS_ENABLED_BY_FEATURE = Skript.methodExists(EntityType.class, "isEnabledByFeature", World.class);
+	public static String LANGUAGE_NODE = "entities";
 
-	public final static Message m_age_pattern = new Message(LANGUAGE_NODE + ".age pattern");
-	public final static Adjective m_baby = new Adjective(LANGUAGE_NODE + ".age adjectives.baby"),
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/EntityData.java:70]: why

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 2]
```diff
@@ -44,42 +44,33 @@ public abstract class EntityData<E extends Entity> implements SyntaxElement, Ygg
...
-	private static final List<EntityData> ALL_ENTITY_DATAS = new ArrayList<>();
+	private static List<EntityData> ALL_ENTITY_DATAS = new ArrayList<>();
 
 	public static Serializer<EntityData> serializer = new Serializer<EntityData>() {
 		@Override
-		public Fields serialize(final EntityData o) throws NotSerializableException {
-			final Fields f = o.serialize();
-			f.putObject("codeName", o.info.codeName);
+		public Fields serialize(EntityData entityData) throws NotSerializableException {
+			Fields f = entityData.serialize();
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/EntityData.java:72]:
```suggestion
			Fields fields = entityData.serialize();
```

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 3]
```diff
@@ -220,21 +207,20 @@ public void onLanguageChange() {
 
 		@Override
 		public int hashCode() {
-			final int prime = 31;
+			int prime = 31;
 			int result = 1;
 			result = prime * result + codeName.hashCode();
 			return result;
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/EntityData.java:213]:
```suggestion
			return Objects.hashCode(codeName);
```

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 4]
```diff
@@ -313,7 +310,7 @@ public final boolean init(final Expression<?>[] exprs, final int matchedPattern,
 	public abstract EntityData getSuperType();
 
 	@Override
-	public final String toString() {
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/EntityData.java:316]: shouldn't be removed

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 5]
```diff
@@ -344,8 +340,8 @@ public Kleenean isBaby() {
 	protected abstract int hashCode_i();
 
 	@Override
-	public final int hashCode() {
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/EntityData.java:347]: shouldn't be removed

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 6]
```diff
@@ -358,14 +354,13 @@ public final int hashCode() {
 	protected abstract boolean equals_i(EntityData<?> obj);
 
 	@Override
-	public final boolean equals(final @Nullable Object obj) {
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/EntityData.java:361]: shouldn't be removed

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 7]
```diff
@@ -565,76 +554,83 @@ public static <E extends Entity> E[] getAll(final EntityData<?>[] types, final C
...
 	}
 
-	public static String toString(final Class<? extends Entity> c, final int flags) {
-		return fromClass(c).getSuperType().toString(flags);
+	public static String toString(Class<? extends Entity> entityClass, int flags) {
+		return fromClass(entityClass).getSuperType().toString(flags);
 	}
 
 	@SuppressWarnings("unchecked")
-	public final boolean isInstance(final @Nullable Entity e) {
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/EntityData.java:616]: shouldn't be removed

File: src/main/java/ch/njol/skript/entity/SimpleEntityData.java [hunk 8]
```diff
@@ -17,7 +17,7 @@
 
 public class SimpleEntityData extends EntityData<Entity> {
 	
-	public final static class SimpleEntityDataInfo {
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/SimpleEntityData.java:20]: probably shouldn't be removed, not sure if static already makes it final tho

File: src/main/java/ch/njol/skript/entity/SimpleEntityData.java [hunk 9]
```diff
@@ -52,7 +51,7 @@ public boolean equals(final @Nullable Object obj) {
 		}
 	}
 	
-	private final static List<SimpleEntityDataInfo> types = new ArrayList<>();
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/entity/SimpleEntityData.java:55]: shouldn't be removed

**Review by Efnilite — CHANGES_REQUESTED** [review]

**Review by Efnilite — APPROVED** [review]

**Review by sovdeeth — CHANGES_REQUESTED** [review]
tests failing

File: src/main/java/ch/njol/skript/entity/EntityData.java [hunk 10]
```diff
@@ -502,13 +485,13 @@ public E spawn(Location location, @Nullable Consumer<E> consumer) {
...
-		final List<E> list = new ArrayList<>();
-		for (final World w : worlds) {
-			for (final E e : w.getEntitiesByClass(getType()))
-				if (match(e))
-					list.add(e);
+		List<E> list = new ArrayList<>();
+		for (World world : worlds) {
+			for (E entity : world.getEntitiesByClass(getType()))
+				if (match(entity))
+					list.add(entity);
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/entity/EntityData.java:494]:
```suggestion
			for (E entity : world.getEntitiesByClass(getType())) {
				if (match(entity))
					list.add(entity);
			}
```

**Review by sovdeeth — APPROVED** [review]
