### PR TITLE
Return type accuracy and usage improvements

### LINKED ISSUE #5060: Some elements don't handle Object return types well
### Skript/Server Version

```markdown
[00:15:53 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[00:15:53 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[00:15:53 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[00:15:53 INFO]: [Skript] Server Version: git-Paper-350 (MC: 1.18.2)
[00:15:53 INFO]: [Skript] Skript Version: 2.6.3
[00:15:53 INFO]: [Skript] Installed Skript Addons:
[00:15:53 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[00:15:53 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

When an element accepts multiple types (`%foo/boo/bar%`), conversion of incorrectly typed expressions can sometimes produce expressions whose return type is Object (or something else not of a supported type). Some classes handle this poorly and emit parse time errors.

As an example, let's take `play hurt on {_thing}`. This produces the error `Entity effects can only be played on entities`. This is because the variable's return type is Object, which makes [this](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffVisualEffect.java#L100) check fail.

Some research shows that the following classes have this issue:
* [EffVisualEffect](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffVisualEffect.java#L100)
* [ExprColorOf (acceptChange method)](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprColorOf.java#L113-L124) 
* [ExprFacing (acceptChange method)](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprFacing.java#L93-L94)

### Expected Behavior

You should be allowed to provide expressions with Object return types, without getting errors. Elements prone to this issue should account for this special case.

### Steps to Reproduce

Does not work:
```
play hurt on {_thing}
set colour of {_thing} to red
set facing of {_thing} to north
```

Works:
```
play hurt on random entity of {_thing}
set colour of random entity of {_thing} to red
set facing of random block of {_thing} to north
```

### Errors or Screenshots

_No response_

### Other

As illustrated above, the `random %*classinfo%` expression is useful for ensuring the return type is of the proper type.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### LINKED ISSUE #7573: Unable to use show resurrection by totem in a function
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: 1.21.3-2358-16ce24a (MC: 1.21.3)
[Skript] Skript Version: 2.10.1 (skriptlang-github)
[Skript] Installed Skript Addons: 
[Skript]  - SkBee v3.8.2 (https://github.com/ShaneBeee/SkBee)
[Skript]  - skript-reflect v2.6 (https://github.com/SkriptLang/skript-reflect)
[Skript]  - DiSky v4.21.1
[Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Skript] Installed dependencies: 
[Skript]  - Vault v2.9.0
[Skript]  - WorldGuard v7.0.13-beta-1+2f13ae0
​
```

### Bug Description

It failed to play resurrection totem animation when used a function.

### Expected Behavior

Expect it to play resurrection totem animation normally.

### Steps to Reproduce

Make a function with ``show resurrection by totem on {_p}`` and done.

### Errors or Screenshots

Image

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by APickledWalrus**
### Problem
Some Expressions/Classes are not taking full advantage of the multiple return types system. Others have return types that are incorrectly setup. Ensuring detailed return types is also important for features like local variable type hints.

### Solution
I aim to integrate usage of `Expression#possibleReturnTypes` and `Expression#canReturn` where possible. I've also cleaned up some classes that were in need of it (to improve their return type logic).

A major change that I made is `Expression#canReturn` will **always** return true if one of the possible return types is Object. This appears to work without issue, but further testing is needed.

ExprTernary and ExprDefaultValue have been rewritten and their generics removed. I do not believe these are necessary anymore. The generic ConvertedExpression implementation is capable of ensuring type safety.

### Testing Completed
There is existing coverage of most of the modified syntax. I have added tests for ExprTernary and ExprDefaultValue since they were rewritten and previously did not have any tests.

### Supporting Information

n/a

---
**Completes:** Fixes https://github.com/SkriptLang/Skript/issues/5060
**Related:** none

### CODE REVIEW

File: src/main/java/ch/njol/skript/lang/Variable.java [hunk 1]
```diff
@@ -261,6 +261,11 @@ public Class<? extends T> getReturnType() {
 		return superType;
 	}
 
+	@Override
+	public Class<? extends T>[] possibleReturnTypes() {
+		return types;
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/Variable.java:266]: note to self: this needs to be copied probably (for safety)

**Review by sovdeeth — APPROVED** [review]

**Review by sovdeeth — APPROVED** [review]

**Review by erenkarakal — APPROVED** [review]
