### PR TITLE
Any X

### LINKED ISSUE #6727: No converter chaining flags don't prevent conversion.
### Skript/Server Version

```markdown
2.9-dev/feature
```

### Bug Description

If you use the `NO_RIGHT_CHAINING` (or no_left...) it doesn't prevent an unchecked cast conversion step being done at the right (or left) of the chain.

This means that converters end up being suggested in nonsensical places, for example `Block -> InventoryHolder|` would actually permit a `Block -> Player` conversion (since players are inventory holders).
This also means you can often compare completely discrete types that ought to fail. (During testing we managed to get from `String` to `Slot` and compare that with a number :pensive: )

### Expected Behavior

No-chaining converters shouldn't upcast at the start or downcast at the end, since this is effectively an unchecked conversion step (and the source of a lot of issues).

### Steps to Reproduce

t

### Errors or Screenshots

_No response_

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by Moderocky**
### Description

This change is mainly aimed at addons (with a little bit of internal clean-up).

This adds 'Any-X' types, which allow Skript and addons to register lots of different types that have a single common property (e.g. `name`), which can use the same property expression.
See [here](<https://github.com/SkriptLang/Skript/issues/6727>) for details.

With this, addons can support their own (common) properties (e.g. `name of <discord channel>`, `name of <file>`) without conflicting with Skript.
This also means that Skript doesn't need 18 different possibilities in the pattern input.

These Any-X types have a bit of special behaviour: they have their own kind of class info (they could probably do with a special note in docs because the use patterns look a bit odd) and their input patterns start `any-...`. This is to help emphasise that they are general acceptors rather than specific things.

### Extra Fix!

This also fixes #6727: an unsafe cast is no longer permitted at the start of a no-left-chain, or at the end of a no-right-chain.
If you want the old behaviour (I know some of us secretly love unsafe casts) then you can re-enable that behaviour with an extra bit flag `ALLOW_UNSAFE_CASTS`.

### Using This

Addons that want to use an Any-X type can just implement the interface with their type (e.g. `MyThing implements AnyNamed`) or, _if_ this isn't possible, register a converter from their type (e.g. `registerConverter(MyThing.class, AnyNamed.class, thing -> thing::getName)` with **no right chaining!!!11!1** <- (this is important because otherwise Skript thinks it can convert between your type and every other type in the galaxy)

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** fixes #6710, fixes #6727

### CODE REVIEW

File: src/main/java/ch/njol/skript/classes/AnyInfo.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ *  Skript is distributed in the hope that it will be useful,
+ *  but WITHOUT ANY WARRANTY; without even the implied warranty of
+ *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ *  GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License
+ *  along with Skript.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ * Copyright Peter Güttinger, SkriptLang team and contributors
+ */
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/classes/AnyInfo.java:18]:
```suggestion
```

File: src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+ *  Skript is distributed in the hope that it will be useful,
+ *  but WITHOUT ANY WARRANTY; without even the implied warranty of
+ *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ *  GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License
+ *  along with Skript.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ * Copyright Peter Güttinger, SkriptLang team and contributors
+ */
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java:18]:
```suggestion
```

File: src/main/java/ch/njol/skript/lang/util/common/AnyContains.java [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+ *  but WITHOUT ANY WARRANTY; without even the implied warranty of
+ *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ *  GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License
+ *  along with Skript.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ * Copyright Peter Güttinger, SkriptLang team and contributors
+ */
+package ch.njol.skript.lang.util.common;
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/util/common/AnyContains.java:19]:
```suggestion
package ch.njol.skript.lang.util.common;
```

File: src/main/java/ch/njol/skript/lang/util/common/AnyNamed.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+ *  Skript is distributed in the hope that it will be useful,
+ *  but WITHOUT ANY WARRANTY; without even the implied warranty of
+ *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ *  GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License
+ *  along with Skript.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ * Copyright Peter Güttinger, SkriptLang team and contributors
+ */
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/util/common/AnyNamed.java:18]:
```suggestion
```

File: src/main/java/ch/njol/skript/lang/util/common/AnyProvider.java [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+ *  Skript is distributed in the hope that it will be useful,
+ *  but WITHOUT ANY WARRANTY; without even the implied warranty of
+ *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ *  GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License
+ *  along with Skript.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ * Copyright Peter Güttinger, SkriptLang team and contributors
+ */
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/util/common/AnyProvider.java:18]:
```suggestion
```

**Review by sovdeeth — APPROVED** [review]
looks great
though i do think we should still work towards a better api like tud suggested of extending syntax or something like that, but you're right about that being a long ways off.

File: src/main/java/org/skriptlang/skript/lang/converter/Converter.java [hunk 6]
```diff
@@ -37,15 +37,36 @@ public interface Converter<F, T> {
...
+	 * An unchecked cast would be {@code Number -> Integer}. (Not all numbers are integers, some are floats!)
+	 * <br/>
+	 * <br/>
+	 * When combined with {@link #NO_RIGHT_CHAINING} the output can be conformed with an unchecked cast,
+	 * e.g. {@code String -> Number (-> cast Integer)}.
+	 * <br/>
+	 * When combined with {@link #NO_RIGHT_CHAINING} the output can be conformed with an unchecked cast,
+	 * e.g. {@code (cast Object ->) Integer -> String}.
+	 */
+	int ALLOW_UNSAFE_CASTS = 4;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/lang/converter/Converter.java:68]: Unfortunately, 4 is already used elsewhere... 
https://github.com/SkriptLang/Skript/blob/474d6f33de744e3e634cbab124ed93f86ff55579/src/main/java/ch/njol/skript/command/Commands.java#L80

It would be better to change Commands to use a higher number (perhaps like 64 or something)
Ideally in the future we could use a different flag system, but that's out of scope for this PR

File: src/main/java/org/skriptlang/skript/lang/converter/Converters.java [hunk 7]
```diff
@@ -304,8 +304,13 @@ private static <F, T extends ParentType, SubType extends F, ParentType> Converte
 
 		// Attempt to find converters that have either 'from' OR 'to' not exactly matching
 		for (ConverterInfo<?, ?> unknownInfo : CONVERTERS) {
+			int flags = unknownInfo.getFlags();
 			if (unknownInfo.getFrom().isAssignableFrom(fromType) && unknownInfo.getTo().isAssignableFrom(toType)) {
 				ConverterInfo<F, ParentType> info = (ConverterInfo<F, ParentType>) unknownInfo;
+				if ((flags & Converter.ALLOW_UNSAFE_CASTS) == 0) {
+					if ((flags & Converter.NO_RIGHT_CHAINING) == Converter.NO_RIGHT_CHAINING
+						&& !toType.isAssignableFrom(unknownInfo.getTo())) continue;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/lang/converter/Converters.java:312]:
```suggestion
						&& !toType.isAssignableFrom(unknownInfo.getTo()))
						continue;
```
`continue` should be on the next line for each

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
some thoughts from a quick look

File: src/main/java/ch/njol/skript/classes/AnyInfo.java [hunk 8]
```diff
@@ -0,0 +1,16 @@
...
+import ch.njol.skript.lang.util.common.AnyProvider;
+
+public class AnyInfo<Type extends AnyProvider> extends ClassInfo<Type> {
+
+	/**
+	 * @param c        The class
+	 * @param codeName The name used in patterns
+	 */
+	public AnyInfo(Class<Type> c, String codeName) {
+		super(c, "any-" + codeName);
```
[the remark this answers is not in the document]
Comment (Moderocky) [reply src/main/java/ch/njol/skript/classes/AnyInfo.java:12]: I wanted some way to differentiate it from regular classinfos so that it's a bit more recognizable in patterns (e.g. `name of %player/entity/any-named%`) and make sure it can't conflict with existing things.

File: src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+	@NotNull
+	Number amount();
+
+	/**
+	 * This is called before {@link #setAmount(Number)}.
+	 * If the result is false, setting the name will never be attempted.
+	 *
+	 * @return Whether this supports being set
+	 */
+	default boolean amountSupportsChange() {
```
[the remark this answers is not in the document]
Comment (Moderocky) [reply src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java:27]: Can't be supportsChange because you could conceivably implement two of these at once and not want one to be changed

**Review by UnderscoreTud — APPROVED** [review]

File: src/main/java/ch/njol/skript/expressions/ExprName.java [hunk 10]
```diff
@@ -117,17 +118,16 @@ public class ExprName extends SimplePropertyExpression<Object, String> {
...
 				Skript.methodExists(Bukkit.class, "createInventory", InventoryHolder.class, int.class, Component.class))
 			serializer = BungeeComponentSerializer.get();
-		HAS_GAMERULES = Skript.classExists("org.bukkit.GameRule");
-		register(ExprName.class, String.class, "(1¦name[s]|2¦(display|nick|chat|custom)[ ]name[s])", "offlineplayers/entities/blocks/itemtypes/inventories/slots/worlds"
-			+ (HAS_GAMERULES ? "/gamerules" : ""));
-		register(ExprName.class, String.class, "(3¦(player|tab)[ ]list name[s])", "players");
+		register(ExprName.class, String.class, "(1:name[s])", "players/entities/inventories/named");
+		register(ExprName.class, String.class, "(2:(display|nick|chat|custom)[ ]name[s])", "players/entities/inventories/named");
+		register(ExprName.class, String.class, "(3:(player|tab)[ ]list name[s])", "players");
+		// we keep the entity input because we want to do something special with entities
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/expressions/ExprName.java:130]: Is there still an AnyNamed converter for it? Might be worth having in case someone wants to use the type in another syntax

File: src/main/java/org/skriptlang/skript/lang/converter/Converters.java [hunk 11]
```diff
@@ -304,8 +304,14 @@ private static <F, T extends ParentType, SubType extends F, ParentType> Converte
 
 		// Attempt to find converters that have either 'from' OR 'to' not exactly matching
 		for (ConverterInfo<?, ?> unknownInfo : CONVERTERS) {
+			int flags = unknownInfo.getFlags();
 			if (unknownInfo.getFrom().isAssignableFrom(fromType) && unknownInfo.getTo().isAssignableFrom(toType)) {
 				ConverterInfo<F, ParentType> info = (ConverterInfo<F, ParentType>) unknownInfo;
+				if ((flags & Converter.ALLOW_UNSAFE_CASTS) == 0) {
+					if ((flags & Converter.NO_RIGHT_CHAINING) == Converter.NO_RIGHT_CHAINING
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/lang/converter/Converters.java:311]: I'm a little confused about the logic here. What are you trying to do?

**Review by APickledWalrus — CHANGES_REQUESTED** [review]

File: src/main/java/ch/njol/skript/classes/data/SkriptClasses.java [hunk 12]
```diff
@@ -691,6 +689,30 @@ public String toVariableNameString(VisualEffect e) {
...
+
+		Classes.registerClass(new AnyInfo<>(AnyAmount.class, "numbered")
+			.name("Any Numbered/Sized Thing")
+			.description("Something that has an amount or size.")
+			.usage("")
+			.examples("the size of {thing}", "the amount of {thing}")
+			.since("INSERT VERSION")
+		);
+
+		Classes.registerClass(new AnyInfo<>(AnyContains.class, "containing")
```
[the remark this answers is not in the document]
Comment (Moderocky) [reply src/main/java/ch/njol/skript/classes/data/SkriptClasses.java:709]: You can't put spaces in class infos, it's a real mess on the parsing side. That's why I had them as `any-...` originally.

File: src/main/java/ch/njol/skript/expressions/ExprName.java (hunk 10 above)
Comment (Moderocky) [reply src/main/java/ch/njol/skript/expressions/ExprName.java:130]: Yes but this pattern has to take entity in preference here because it wants an `Entity` object rather than a converted `AnyNamed` object.

File: src/main/java/org/skriptlang/skript/lang/converter/Converters.java (hunk 11 above)
Comment (Moderocky) [reply src/main/java/org/skriptlang/skript/lang/converter/Converters.java:311]: So this is something called a bitmask, you can read an introduction to them [here](<https://bamblebam.medium.com/unmasking-bit-masks-71421d0eb2fa>) 🙂 

The `flags` variable will be some number representing a combination of flags (e.g. `0101`), and when we use a logic AND operator with a single flag (e.g. `0001`) we will get one of two results: either `0000` (zero) if our flag isn't present, or `0001` (our flag) if it is present.

In this case when we ask if `flags & NO_RIGHT_CHAINING == NO_RIGHT_CHAINING` we're basically asking whether the `NO_RIGHT_CHAINING` flag is present in our flags bitfield.

File: src/main/java/ch/njol/skript/conditions/CondContains.java [hunk 13]
```diff
@@ -115,48 +120,59 @@ public boolean check(Event e) {
...
-						return inventory.containsAtLeast((ItemStack) o1, ((ItemStack) o1).getAmount());
+				return items.check(event, o1 -> {
+					if (o1 instanceof ItemType type)
+						return type.isContainedIn(inventory);
+					else if (o1 instanceof ItemStack stack)
+						return inventory.containsAtLeast(stack, stack.getAmount());
 					else if (o1 instanceof Inventory)
 						return Objects.equals(inventory, o1);
 					else
 						return false;
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/conditions/CondContains.java:135]:
```suggestion
					if (o1 instanceof ItemType type) {
						return type.isContainedIn(inventory);
					} else if (o1 instanceof ItemStack stack) {
						return inventory.containsAtLeast(stack, stack.getAmount());
					} else if (o1 instanceof Inventory) {
						return Objects.equals(inventory, o1);
					}
					return false;
```
formatting

File: src/main/java/ch/njol/skript/conditions/CondContains.java [hunk 14]
```diff
@@ -115,48 +120,59 @@ public boolean check(Event e) {
...
+						}
+					});
+				}, isNegated(), containers.getAnd());
+			}
+			case CONTAINER -> SimpleExpression.check(containerValues, object -> {
+				AnyContains container;
+				if (object instanceof AnyContains<?>)
+					container = (AnyContains) object;
+				else
+					container = Converters.convert(object, AnyContains.class);
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/conditions/CondContains.java:158]:
```suggestion
				if (object instanceof AnyContains<?>) {
					container = (AnyContains) object;
				} else {
					container = Converters.convert(object, AnyContains.class);
				}
```

File: src/main/java/ch/njol/skript/expressions/ExprAmount.java [hunk 15]
```diff
@@ -60,23 +66,30 @@
 		"Please note that getting a list's recursive size can cause lag if the list is large, so only use this expression if you need to!"})
 @Examples({"message \"There are %number of all players% players online!\""})
 @Since("1.0")
-public class ExprAmount extends SimpleExpression<Long> {
+public class ExprAmount extends SimpleExpression<Number> {
 
 	static {
-		Skript.registerExpression(ExprAmount.class, Long.class, ExpressionType.PROPERTY,
+		Skript.registerExpression(ExprAmount.class, Number.class, ExpressionType.PROPERTY,
+			"[the] (amount|number|size) of %numbered%",
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/expressions/ExprAmount.java:73]:
```suggestion
				"[the] (amount|number|size) of %numbered%",
```

File: src/main/java/ch/njol/skript/expressions/ExprAmount.java [hunk 16]
```diff
@@ -109,6 +124,52 @@ protected Long[] get(Event e) {
 		return new Long[]{(long) exprs.getArray(e).length};
 	}
 
+	@Override
+	public @Nullable Class<?>[] acceptChange(Changer.ChangeMode mode) {
+		if (any != null) {
+			switch (mode) {
```
[the remark this answers is not in the document]
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/expressions/ExprAmount.java:130]: bumping

File: src/main/java/ch/njol/skript/expressions/ExprAmount.java [hunk 17]
```diff
@@ -109,6 +124,52 @@ protected Long[] get(Event e) {
...
+			super.change(event, delta, mode);
+			return;
+		}
+		double amount = delta != null ? ((Number) delta[0]).doubleValue() : 0;
+		// It's okay to treat it as a double even if it's a whole number because there's no case in
+		// the set of real numbers where (x->double + y->double)->long != (x+y)
+		switch (mode) {
+			case REMOVE:
+				amount = -amount;
+				// fall through
```
[the remark this answers is not in the document]
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/expressions/ExprAmount.java:155]: bumping

File: src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java [hunk 18]
```diff
@@ -0,0 +1,42 @@
...
+ * Anything implementing this (or convertible to this) can be used by the {@link ch.njol.skript.expressions.ExprAmount}
+ * property expression.
+ *
+ * @see AnyProvider
+ */
+@FunctionalInterface
+public interface AnyAmount extends AnyProvider {
+
+	/**
+     * @return This thing's amount/size
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java:16]:
```suggestion
	 * @return This thing's amount/size
```
Spacing is a bit wonky

File: src/main/java/org/skriptlang/skript/lang/converter/Converter.java [hunk 19]
```diff
@@ -37,15 +37,36 @@ public interface Converter<F, T> {
...
+	 * An unchecked cast would be {@code Number -> Integer}. (Not all numbers are integers, some are floats!)
+	 * <br/>
+	 * <br/>
+	 * When combined with {@link #NO_RIGHT_CHAINING} the output can be conformed with an unchecked cast,
+	 * e.g. {@code String -> Number (-> cast Integer)}.
+	 * <br/>
+	 * When combined with {@link #NO_RIGHT_CHAINING} the output can be conformed with an unchecked cast,
+	 * e.g. {@code (cast Object ->) Integer -> String}.
+	 */
+	int ALLOW_UNSAFE_CASTS = 8;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/lang/converter/Converter.java:68]: I think it would be better for this value to be 4 and to instead update Commands
https://github.com/SkriptLang/Skript/blob/d82667540e5b8381456d87df0a6485c03517bddf/src/main/java/ch/njol/skript/command/Commands.java#L80

File: src/main/java/ch/njol/skript/util/slot/Slot.java [hunk 20]
```diff
@@ -18,38 +18,94 @@
...
+		return true;
+	}
+
+	/**
+	 * @param name The name to change
+	 */
+	@Override
+	public void setName(String name) {
+		ItemStack stack = this.getItem();
+		if (stack != null && !Aliases.javaItemType("air").isOfType(stack)) {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/util/slot/Slot.java:88]: There is a method in ItemUtils to check whether a stack (or material) represents air. I think it would be better to use that.

File: src/main/java/org/skriptlang/skript/lang/converter/Converters.java (hunk 11 above)
Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/lang/converter/Converters.java:311]: I understand the usage of bitflags. I am confused about the way chaining is being checked here (the new flag's documentation unfortunately did not clarify it for me). Can you explain how the flags are intended to work? Or, more specifically, when these "maybe"/casting converters are intended to be allowed?

**Review by APickledWalrus — CHANGES_REQUESTED** [review]

File: src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java [hunk 21]
```diff
@@ -0,0 +1,42 @@
...
+
+/**
+ * A provider for anything with a (number) amount/size.
+ * Anything implementing this (or convertible to this) can be used by the {@link ch.njol.skript.expressions.ExprAmount}
+ * property expression.
+ *
+ * @see AnyProvider
+ */
+@FunctionalInterface
+public interface AnyAmount extends AnyProvider {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java:13]: Just had an idea, what if we implemented this in CondIsEmpty? Could simply check `amount() == 0`, or it might be worth adding a default method to this interface:
```java
default boolean isEmpty() {
	amount() == 0;
}
```

**Comment by Moderocky** [comment]
There is currently a test issue with EasyMock's player substitute not returning its name properly. Since you made the breed test @Efnilite do you have any insights?

File: src/main/java/ch/njol/skript/expressions/ExprAmount.java [hunk 22]
```diff
@@ -109,6 +124,48 @@ protected Long[] get(Event e) {
...
+			return switch (mode) {
+				case SET, ADD, RESET, DELETE, REMOVE -> CollectionUtils.array(Number.class);
+				default -> null;
+			};
+		}
+		return super.acceptChange(mode);
+	}
+
+	@Override
+	public void change(Event event,  Object@Nullable[] delta, Changer.ChangeMode mode) {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/expressions/ExprAmount.java:139]:
```suggestion
	public void change(Event event,  Object @Nullable [] delta, Changer.ChangeMode mode) {
```

File: src/main/java/ch/njol/skript/expressions/ExprAmount.java [hunk 23]
```diff
@@ -109,6 +124,48 @@ protected Long[] get(Event e) {
 		return new Long[]{(long) exprs.getArray(e).length};
 	}
 
+	@Override
+	public @Nullable Class<?>[] acceptChange(Changer.ChangeMode mode) {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/expressions/ExprAmount.java:128]: I would directly import ChangeMode

File: src/main/java/ch/njol/skript/expressions/ExprAmount.java [hunk 24]
```diff
@@ -109,6 +124,48 @@ protected Long[] get(Event e) {
...
+		return super.acceptChange(mode);
+	}
+
+	@Override
+	public void change(Event event,  Object@Nullable[] delta, Changer.ChangeMode mode) {
+		if (any == null) {
+			super.change(event, delta, mode);
+			return;
+		}
+		double amount = delta != null ? ((Number) delta[0]).doubleValue() : 0;
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/expressions/ExprAmount.java:144]: You could use `1` here instead of `0`, and then you would not need the `amount = 1` fall-through case for RESET and DELETE

File: src/main/java/org/skriptlang/skript/lang/converter/Converters.java [hunk 25]
```diff
@@ -319,6 +324,11 @@ private static <F, T extends ParentType, SubType extends F, ParentType> Converte
 
 			} else if (fromType.isAssignableFrom(unknownInfo.getFrom()) && toType.isAssignableFrom(unknownInfo.getTo())) {
 				ConverterInfo<SubType, T> info = (ConverterInfo<SubType, T>) unknownInfo;
+				if ((flags & Converter.ALLOW_UNSAFE_CASTS) == 0) {
+					if ((flags & Converter.NO_LEFT_CHAINING) == Converter.NO_LEFT_CHAINING
+						&& !unknownInfo.getFrom().isAssignableFrom(fromType))
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/lang/converter/Converters.java:329]:
```suggestion
					if ((flags & Converter.NO_LEFT_CHAINING) == Converter.NO_LEFT_CHAINING)
```

File: src/main/java/org/skriptlang/skript/lang/converter/Converters.java [hunk 26]
```diff
@@ -336,6 +346,15 @@ private static <F, T extends ParentType, SubType extends F, ParentType> Converte
...
 			if (fromType.isAssignableFrom(unknownInfo.getFrom()) && unknownInfo.getTo().isAssignableFrom(toType)) {
 				ConverterInfo<SubType, ParentType> info = (ConverterInfo<SubType, ParentType>) unknownInfo;
+				int flags = unknownInfo.getFlags();
+				if ((flags & Converter.ALLOW_UNSAFE_CASTS) == 0) {
+					if ((flags & Converter.NO_LEFT_CHAINING) == Converter.NO_LEFT_CHAINING
+						&& !unknownInfo.getFrom().isAssignableFrom(fromType))
+						continue;
+					if ((flags & Converter.NO_RIGHT_CHAINING) == Converter.NO_RIGHT_CHAINING
+						&& !toType.isAssignableFrom(unknownInfo.getTo()))
+						continue;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/lang/converter/Converters.java:356]:
```suggestion
					if ((flags & Converter.NO_LEFT_CHAINING) == Converter.NO_LEFT_CHAINING)
						continue;
					if ((flags & Converter.NO_RIGHT_CHAINING) == Converter.NO_RIGHT_CHAINING)
						continue;
```

File: src/main/java/ch/njol/skript/util/slot/Slot.java [hunk 27]
```diff
@@ -18,38 +18,95 @@
...
+		return this.getAmount();
+	}
+
+	@Override
+	public boolean supportsAmountChange() {
+		return true;
+	}
+
+	@Override
+	public void setAmount(@Nullable Number amount) throws UnsupportedOperationException {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/util/slot/Slot.java:108]:
```suggestion
	public void setAmount(@Nullable Number amount) {
```
It doesn't, right?

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
A few last things 🙂

**Comment by JakeGBLP** [comment]
Does this PR include some sort of documentation to mention any addon-made changes? I think some annotation/method should be added to do this if not already present.

File: src/main/java/ch/njol/skript/lang/util/common/AnyProvider.java [hunk 28]
```diff
@@ -0,0 +1,27 @@
...
+ * If possible, types should implement an {@link AnyProvider} subtype directly for
+ * the best possible parsing efficiency.
+ * However, implementing the interface may not be possible if:
+ * <ul>
+ *     <li>registering an existing class from a third-party library</li>
+ *     <li>the subtype getter method conflicts with the type's own methods
+ *     or erasure</li>
+ *     <li>the presence of the supertype might confuse the class's design</li>
+ * </ul>
+ * In these cases, a converter from the class to the AnyX type can be registered.
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/lang/util/common/AnyProvider.java:18]: should include that you should disable right chaining

**Review by Efnilite — CHANGES_REQUESTED** [review]

File: src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java [hunk 29]
```diff
@@ -0,0 +1,42 @@
+package ch.njol.skript.lang.util.common;
```
[the remark this answers is not in the document]
Comment (Moderocky) [reply src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java:1]: No, these shouldn't be mixed up with the other utility classes.

[the remark this answers is not in the document]
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java:1]: maybe these can be in `util.any`? i think common is too vague

[the remark this answers is not in the document]
Comment (Moderocky) [reply src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java:1]: They're common properties of things.

**Review by Efnilite — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]
great work!
