### PR TITLE
Adventure Text Component (Chat) Integration

### LINKED ISSUE #770: Fix inconsistent chat colors
- [ ] Brown (dye only) and light blue (chat only) share same color slot, leading to wrong color-to-string conversion
- [ ] Light red is "pink" when converted to text

### LINKED ISSUE #1190: Escaping characters "<" and ">" in messages with json formatting
As is foreseeable, putting the characters "<" and ">" in tags for json formatting (eg. tooltips), makes it buggy, so you can't use it as text.
Which escape could be used to have the possibility to put "<" and ">" in the text of a tag?

### LINKED ISSUE #3112: Expand component support and the ChatCode API
### Description
Since Spigot/Paper is starting to use components in more and more places, we need to add support to use it. Right now, we only support components in chat messages, but this is also supported in the following:
- [ ] item names & lore
- [ ] entity names
- [ ] action bars
- [ ] titles

And over all, we should standarize a way to pass around components in a way addon developers are able to use them as well, it's only possible to access them internally as of now. The best way to do this would be expanding the ChatCode API to allow chat codes be parsed in any string, this way we can also introduce things such as  `<nl>` for new lines in Skript.

### LINKED ISSUE #3212: Invisible color tags are included in "Part Of" expression
### Description
When you use a colored test, i.e: `"&2Test"` or `"<#e81d13>Test"`, the invisible tags, like `&2` are taken into account when using the `part of %string%` expression. So the output can be blank caracters, see belox:

### Steps to Reproduce
`set {test} to colored "&2Test"`
`send part of {test} from character 1 to character 2`
EXPECTED Output: `Te` (in green)
FOUND Output: nothing (blank)
`send part of {test} from character 1 to character 4`
EXPECTED Output: `Test` (in green)
FOUND Output: `Te` (in green)

So it's shifted by the 2 invisible color caracters.
It's exactly the same with or without `colored` before the text

It's ever worse with HEX color tag:
`set {test} to colored "<#566353>Test"`
`send part of {test} from character 1 to character 14`
OUTPUT: blank
`send part of {test} from character 1 to character 15`
OUTPUT: `T` (with the right color)

So with Hex color it's shifted by 14 characters !

### Expected Behavior
The color tags shouldn't be taken into account in the Part Of expression

### Errors / Screenshots
image
image

### Server Information
* **Server version/platform:** Minecraft 1.16.1 running Paper 1.16.1-R0.1-SNAPSHOT
* **Skript version:** 2.5-alpha6(rev1)

### LINKED ISSUE #4853: Font/Hex colour support for titles.
### Suggestion

Include hex colour support for the titles. Example: grabbing "<##ffffff>white hex colours example" for the title. (except an actual hex colour, not white)

Example of current implementation:
https://github.com/SkriptLang/Skript/blob/a45b189ca5bdc601a2dc6e99c74ea429f8c666a4/src/main/java/ch/njol/skript/effects/EffActionBar.java#L68

Any my own implementation:
https://github.com/TheLimeGlass/Skore/blob/de4d186cce945230387fcd46568d958680c9de39/src/main/java/me/limeglass/skore/elements/expressions/ExprTitle.java#L44

Doing this would also automatically add support for font which is a Skript chat value.

### LINKED ISSUE #4952: Message effect can have double evaluation of its message content
### Skript/Server Version

```markdown
Skript 2.6.3, Paper 1.19
```

### Bug Description

Using the message effect with both a player and console as receivers, and the message content being a VariableString (or formatted expression), the VariableString will be evaluted twice, resulting in for example a function in it being called twice.

### Expected Behavior

To only call the VariableString getter once.

### Steps to Reproduce

```
function test() :: number:
	broadcast "func call"
	return 2

command /test:
	trigger:
		message "abc %test()%" to console and all players
```
Run `/test`, with at least one player online. Function is called twice

### Errors or Screenshots

_No response_

### Other

Fixing this would likely require some more API, as we'd need to be able to convert a list of `MessageComponent`s back to text, which we don't have any methods for AFAIK

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

### LINKED ISSUE #5792: Add a way to use paper's `sendRichMessage` method from Audiences in script
### Suggestion

Basically, its a method to be able to send miniMessage formatted components to Audience

### Why?

Its a native method in Paper and imo should be supported

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

### LINKED ISSUE #7724: Link formatting cancels out other formatting.
### Skript/Server Version

```markdown
[Skript] Server Version: 1.21.4-212-bb1beda (MC: 1.21.4)
[Skript] Skript Version: 2.10.2 (skriptlang-github)
[Skript] Installed Skript Addons: 
[Skript]  - PermSk v2.0.0 (https://iplexy.de)
[Skript]  - Lusk v1.3.3 (https://github.com/JakeGBLP/Lusk)
[Skript]  - skript-db v1.3.9
[Skript]  - Skellett v2.0.10-tempfix
(https://forums.skunity.com/resources/skellett.24/)
[Skript]  - Plosk v1.1.1
[Skript]  - RediSkript v1.3.7-tempfix
[Skript]  - SkUniversal v2.13
[Skript]  - SkEssentials v1.1.0
(https://github.com/EquipableMC/SkEssentials)
[Skript]  - SkQuery v4.1.9
[Skript]  - SkCloudnet v1.7.7
(https://github.com/byPixelTV/SkCloudnet)
[Skript]  - SkBee v3.8.2 (https://github.com/ShaneBeee/SkBee)
[Skript]  - skript-placeholders v1.7.0
(https://github.com/APickledWalrus/skript-placeholders)
[Skript] Installed dependencies: 
[Skript]  - Vault v1.7.3-b131
[Skript]  - WorldGuard v7.0.13-beta-2+5c4848b
```

### Bug Description

Hello,

We use Skript for our chat and have the following issue. When a link is automatically displayed as a link, the formatting (such as color) used before the link is reset. This doesn't look very nice in the chat. Is it possible to only reset the formatting at the end of the link so that the link ends, without resetting the rest of the formatting?

### Expected Behavior

Ending the link should not reset the rest of the formatting.

### Steps to Reproduce

1. Enable the link display in the config.
2. Create a script that formats the input in the chat and outputs it as a message.
3. Write a text: &eHallo Welt, https://www.google.de, Ciao
4. You will see that the text before the link and the link are yellow, but the "Ciao" is displayed in white.

### Errors or Screenshots

Image

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### LINKED ISSUE #8515: Make the language config use the mini message format
### Suggestion

Use the mini message format for *.lang files in [theese](https://github.com/SkriptLang/Skript/tree/master/src/main/resources/lang)

### Why?

Its confusing when i found out that when i change 

`prefix: <gray>[<gold>Skript<gray>] <reset>`
to
`prefix: <color:#ff8cde>PINK SKRIPT</color>`

and finding out its not mini message

Also maybe also make it a mini message component so i can sprite atlas to the text

It would also be suitable skript is adding mini message support real soon!

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

### PR DESCRIPTION
**Pull request by APickledWalrus**
### Problem
Skript's existing text formatting system is outdated, buggy at times, and heavily integrated with the deprecated Bungeecord Component System. As a result, Skript is missing many of the modern text rendering features available through Adventure. Further, many syntax elements use deprecated methods (or just cannot be implemented) due to missing Component support.

### Solution
This PR deprecates and replaces all internal usages of the existing text formatting API in favor of Adventure and MiniMessage. I am finalizing the work and testing, but this is generally ready for reviews. I have included a brief walkthrough of the primary changes below.

#### The Parser

The main parser is represented within [TextComponentParser](https://github.com/SkriptLang/Skript/blob/feature/adventure-chat-integration/src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java). This parser contains two MiniMessage instances: one for "safe" parsing (e.g. only color/styling codes) and one for "unsafe" parsing (e.g. hovers, click events). As an example, `colored "text"` uses the former while `formatted "text"` uses the latter.

The parser also includes API methods for registering custom tags. This enables addons to register their own formatting codes with Skript's text parser.

#### Compatibility Efforts

The existing configuration options, `link parse mode` and `colors cause reset` have been fully preserved. The former is nicely implemented using the TextReplacement feature of Components, while the latter is somewhat hacked together due to how resets are implemented in MiniMessage.

Legacy formatting codes/tags have also been preserved. There is a compatibility process built in for mapping them to known tags. There is also a compatibility process for supporting color tags with spaces, e.g. `<dark red>`. One important note is that I have overridden the `<u>` tag, which is normally used for underlines in MiniMessage, to instead continue behaving as a tag for inserting unicode characters.

There are converters registered for moving between Strings and Components, though Components are preferred whenever possible.

I have updated `AnyNamed` to include support for Component based operations. The methods are default so that this is non-breaking.

#### Conversion Efforts

Most, if not all, existing syntax places where Components can be used have been updated to use Components. I took this opportunity to implement several new modules:
- `BlockModule`
  - Contains subpackage `sign`
- `EntityModule`
  - Contains subpackage `misc` and submodule `PlayerModule`
- `ItemModule`
  - Contains subpackages `misc` and `book` 
- `MiscModule`
  - This is in the existing `bukkit.misc` subpackage. Existing syntax there has *not* been converted.
- `TextModule`
  - Contains the `TextComponentParser` and text-related syntax, such as message effects and formatting expressions.

For better compatibility (and readability), I have split up `ExprMessage` into multiple expressions (one per message type/event).

This PR does not implement Component support for chat formatting. That is more complex and will require a dedicated pull request.
 
#### Breaking Changes
Many syntax classes have been relocated. If they were being directly referenced, then there will be breaking. I think we should generally consider syntax classes to be internal though.

#### Other
I have removed the BungeeCord Serializer dependency as it is no longer used.

### Testing Completed
No extensive additional tests have been added yet. I performed basic in-game testing. I plan to implement more extensive testing.

### Supporting Information

---
**Completes:**
- https://github.com/SkriptLang/Skript/issues/770
- https://github.com/SkriptLang/Skript/issues/1190
  - This is resolved by quoting the argument, as in `<ttp:'<test'>`
- https://github.com/SkriptLang/Skript/issues/3112
- https://github.com/SkriptLang/Skript/issues/3212
  - I think the appropriate resolution here is to suggest the usage of `unformatted x`, which returns the plain text content
- https://github.com/SkriptLang/Skript/issues/4853
- https://github.com/SkriptLang/Skript/issues/4952
- https://github.com/SkriptLang/Skript/issues/5792
- https://github.com/SkriptLang/Skript/issues/7724
- https://github.com/SkriptLang/Skript/issues/8515

**Related:** none 
**AI assistance:** none

### CODE REVIEW

File: src/main/java/org/skriptlang/skript/bukkit/misc/expressions/ExprMOTD.java [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+	public Class<? extends Component> getReturnType() {
+		return Component.class;
+	}
+
+	@Override
+	public String toString(@Nullable Event event, boolean debug) {
+		return "the " + (isDefault ? "default " : "") + "MOTD";
+	}
+
+}
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/misc/expressions/ExprMOTD.java]:
```suggestion
}

```

**Review by sovdeeth — CHANGES_REQUESTED** [review]
looking good at 75/108

File: src/main/java/ch/njol/skript/structures/StructAutoReload.java [hunk 2]
```diff
@@ -160,10 +159,11 @@ public String toString(@Nullable Event event, boolean debug) {
 	}
 
 	private void reloading(RedirectingLogHandler logHandler) {
+		// TODO update usages
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructAutoReload.java]: for this pr or later?

File: src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+// TODO SignSide support
+public class ExprSignText extends SimpleExpression<Component> {
+
+	public static void register(SyntaxRegistry syntaxRegistry) {
+		syntaxRegistry.register(SyntaxRegistry.EXPRESSION, SyntaxInfo.Expression.builder(ExprSignText.class, Component.class)
+			.supplier(ExprSignText::new)
+			.priority(PropertyExpression.DEFAULT_PRIORITY)
+			.addPatterns("[the] line %integer% [of %block%]",
+				"[the] (1:1st|1:first|2:2nd|2:second|3:3rd|3:third|4:4th|4:fourth) line [of %block%]")
+			.build());
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java:44]: origin?

File: src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+		Block block = this.block.getSingle(event);
+		if (block == null || !(block.getState() instanceof Sign signState)) {
+			return new Component[0];
+		}
+		return new Component[]{signState.getSide(Side.FRONT).line(line)};
+	}
+
+	@Override
+	public Class<?> @Nullable [] acceptChange(ChangeMode mode) {
+		// TODO allow add, remove, and remove all (see ExprLore)
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java:80]: this pr or later?

File: src/main/java/org/skriptlang/skript/bukkit/entity/misc/ExprDeathMessage.java [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+@Since("2.0")
+@Events("death")
+public class ExprDeathMessage extends SimpleExpression<Component> implements EventRestrictedSyntax {
+
+	public static void register(SyntaxRegistry syntaxRegistry) {
+		syntaxRegistry.register(SyntaxRegistry.EXPRESSION, SyntaxInfo.Expression.builder(ExprDeathMessage.class, Component.class)
+			.supplier(ExprDeathMessage::new)
+			.priority(SyntaxInfo.SIMPLE)
+			.addPattern("[the] death( |-)message")
+			.build());
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/entity/misc/ExprDeathMessage.java:39]: origin

**Review by sovdeeth — CHANGES_REQUESTED** [review]
did not fully review but most new syntax classes need origins

**Review by JakeGBLP — COMMENTED** [review]
Good PR, loving the communication with addon developers, great job @APickledWalrus !

File: src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java (hunk 4 above)
Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java:80]: later

File: src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java [hunk 6]
```diff
@@ -152,48 +154,44 @@ public void change(Entity[] entities, Object @Nullable [] delta, ChangeMode mode
...
+		private final boolean isDisplayName;
 
-		public EntityNameHandler(Property<ExpressionPropertyHandler<?, ?>> property) {
-			this.displayName = switch (property.name()) {
-				case "name" -> false;
-				case "display name" -> true;
-				default -> throw new IllegalArgumentException("Property must be either NAME or DISPLAY_NAME");
-			};
+		public EntityNameHandler(boolean isDisplayName) {
+			this.isDisplayName = isDisplayName;
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java]: Not a big fan of forcing the public api to be limited to display and not display name, in case future name-related properties end up being added.

File: src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/expressions/ExprChatFormat.java [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+import org.skriptlang.skript.registration.SyntaxRegistry;
+
+@Name("Chat Format")
+@Description({
+	"Can be used to modify the chat format.",
+	"The sender of a message is represented by [player] or [sender].",
+	"The message is represented by [message] or [msg].",
+})
+@Example("set the chat format to \"<yellow>[player]<light gray>: <green>[message]\"")
+@Since("2.2-dev31")
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/expressions/ExprChatFormat.java:33]: Recently encountered an issue with a user trying to use [PLAYER] as a prefix and being unable to do that via chat format since it replaces. Can we get something like a `full message` syntax that acts like chat format but without the replacing? Not required in this pr, only if you feel like it.

File: src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/ExprChatRecipients.java [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+	}
+
+	@Override
+	public boolean isSingle() {
+		return false;
+	}
+
+	@Override
+	public Class<Player> getReturnType() {
+		return Player.class;
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/ExprChatRecipients.java]: why isn't this Audience?

File: src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java [hunk 9]
```diff
@@ -0,0 +1,564 @@
...
+		 * @see Component#replaceText(TextReplacementConfig)
+		 */
+		public TextReplacementConfig textReplacementConfig() {
+			return textReplacementConfig;
+		}
+	}
+
+	private static final TextComponentParser INSTANCE;
+
+	private static final Pattern COLOR_PATTERN = Pattern.compile("(\\\\*)<([a-zA-Z]+ [a-zA-Z]+)>");
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java]: I would rename this so it's clearer that it's only meant to match multi-word colours

**Review by sovdeeth — CHANGES_REQUESTED** [review]
looks amazing pickle

File: src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/ExprChatRecipients.java (hunk 8 above)
Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/ExprChatRecipients.java]: oops

File: src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java (hunk 6 above)
Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java]: EntityNameHandler itself is private though, so it should be no trouble if we need to change this in the future, right?

File: src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/expressions/ExprChatFormat.java (hunk 7 above)
Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/expressions/ExprChatFormat.java:33]: I think this is a good idea, but I have some rather conflicting thoughts on how we might want to implement it (especially the syntax). Thus, I would prefer to consider this in a future PR after this one.

File: src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java (hunk 6 above)
Comment (sovdeeth) [reply src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java]: Fair, just would be a little less work

**Review by sovdeeth — APPROVED** [review]

File: src/main/java/ch/njol/skript/effects/EffEnforceWhitelist.java [hunk 10]
```diff
@@ -31,13 +32,17 @@
...
 
 	static {
+		// attempt to obtain whitelist message from server config
+		String whitelistMessage = "You are not whitelisted on this server!";
 		try {
 			YamlConfiguration spigotYml = YamlConfiguration.loadConfiguration(new File("spigot.yml"));
-			NOT_WHITELISTED_MESSAGE = spigotYml.getString("messages.whitelist", NOT_WHITELISTED_MESSAGE);
+			whitelistMessage = spigotYml.getString("messages.whitelist", whitelistMessage);
 		} catch (Exception ignored) {}
+		NOT_WHITELISTED_MESSAGE = TextComponentParser.instance().parse(whitelistMessage);
```
Comment (UnderscoreTud) [inline src/main/java/ch/njol/skript/effects/EffEnforceWhitelist.java]: Not sure if we should parse the config message using minimessage since it's not intended to be parsed that way, could probably check how the server parses it and mimic that? unless paper added support for minimessage to it, which is plausible

File: src/main/java/ch/njol/skript/expressions/ExprChestInventory.java [hunk 11]
```diff
@@ -98,9 +85,15 @@ public Class<? extends Inventory> getReturnType() {
...
-				(name != null ? name.toString(event, debug) : "\"" + DEFAULT_CHEST_TITLE + "\"") +
-				" with " + (rows != null ? rows.toString(event, debug) : "" + DEFAULT_CHEST_ROWS + " rows");
+		SyntaxStringBuilder builder = new SyntaxStringBuilder(event, debug);
+		builder.append("a chest inventory");
+		if (name != null) {
+			builder.append("named", name);
+		}
+		if (rows != null) {
+			builder.append("with", rows, "rows");
+		}
```
Comment (UnderscoreTud) [inline src/main/java/ch/njol/skript/expressions/ExprChestInventory.java]: Could use appendIf instead


```suggestion
		builder.appendIf(name != null, "named", name);
		builder.appendIf(rows != null, "with", rows, "rows");
```
(I believe this is correct)

File: src/main/java/ch/njol/skript/variables/FlatFileStorage.java [hunk 12]
```diff
@@ -139,8 +139,6 @@ protected boolean load_i(SectionNode sectionNode) {
 		Version csvSkriptVersion;
 
 		// Some variables used to allow legacy CSV files to be loaded
-		Version v2_0_beta3 = new Version(2, 0, "beta 3");
-		boolean update2_0_beta3 = false;
 		Version v2_1 = new Version(2, 1);
```
Comment (UnderscoreTud) [inline src/main/java/ch/njol/skript/variables/FlatFileStorage.java:142]: Can you not remove this as well?

File: src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java [hunk 13]
```diff
@@ -152,48 +154,44 @@ public void change(Entity[] entities, Object @Nullable [] delta, ChangeMode mode
...
-		private final boolean displayName;
+		private final boolean isDisplayName;
 
-		public EntityNameHandler(Property<ExpressionPropertyHandler<?, ?>> property) {
-			this.displayName = switch (property.name()) {
-				case "name" -> false;
-				case "display name" -> true;
-				default -> throw new IllegalArgumentException("Property must be either NAME or DISPLAY_NAME");
-			};
+		public EntityNameHandler(boolean isDisplayName) {
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/base/types/EntityClassInfo.java]: This could be split into two static factory methods instead, e.g. `EntityNameHandler.name()` and `EntityNameHandler.displayName()` to avoid ambiguity with boolean parameters

File: src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java [hunk 14]
```diff
@@ -0,0 +1,127 @@
...
+	""")
+@Since("1.3")
+// TODO SignSide support
+public class ExprSignText extends SimpleExpression<Component> {
+
+	public static void register(SyntaxRegistry syntaxRegistry) {
+		syntaxRegistry.register(SyntaxRegistry.EXPRESSION, SyntaxInfo.Expression.builder(ExprSignText.class, Component.class)
+			.supplier(ExprSignText::new)
+			.priority(PropertyExpression.DEFAULT_PRIORITY)
+			.addPatterns("[the] line %integer% [of %block%]",
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/block/sign/ExprSignText.java]:
```suggestion
			.addPatterns("line %integer% [of %block%]",
```
`the line n of x` doesn't really make sense

File: src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/expressions/ExprChatFormat.java (hunk 7 above)
Comment (UnderscoreTud) [reply src/main/java/org/skriptlang/skript/bukkit/entity/player/elements/expressions/ExprChatFormat.java:33]: One possible solution is support escaping brackets with something like backslashes

File: src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java [hunk 15]
```diff
@@ -0,0 +1,569 @@
...
+
+	/**
+	 * Registers a TagResolver with Skript's message parsers.
+	 * @param resolver The TagResolver to register.
+	 * @param safe Whether the placeholder can be used in the safe parser.
+	 */
+	public void registerResolver(TagResolver resolver, boolean safe) {
+		unregisterResolver(resolver); // just to be safe
+		resolvers.add(new SkriptTagResolver(resolver, safe));
+	}
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java:268]: Do you think these register methods could be split into `registerSafeX` and `registerUnsafeX` to avoid the boolean parameter? It's a lot more readable that way

File: src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java [hunk 16]
```diff
@@ -0,0 +1,569 @@
...
+		return parse(message, true);
+	}
+
+	/**
+	 * Parses a string using one of the {@link MiniMessage} parsers.
+	 * @param message The message to parse.
+	 * @param safe Whether only color/decoration/formatting related tags should be parsed.
+	 * @return A component from the parsed message.
+	 */
+	public Component parse(Object message, boolean safe) {
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java]: Same as above

File: src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java [hunk 17]
```diff
@@ -0,0 +1,569 @@
...
+	}
+
+	/**
+	 * Strips all formatting from a string.
+	 * @param string The string to strip formatting from.
+	 * @param all Whether ALL formatting/tags should be stripped.
+	 *  If false, only safe tags like colors and decorations will be stripped.
+	 * @return The stripped string.
+	 */
+	public String stripFormatting(String string, boolean all) {
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/text/TextComponentParser.java]: Same as above (can you tell I'm not a fan of boolean parameters 😭)

**Review by UnderscoreTud — APPROVED** [review]

File: src/main/java/ch/njol/skript/effects/EffEnforceWhitelist.java (hunk 10 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/effects/EffEnforceWhitelist.java]: I took a further look into this, and since it's the Spigot config, it appears to use legacy serialization: <https://github.com/PaperMC/Paper/blob/bd74bf6581ce81e59bdab07eadbfbe5d485eefa7/paper-server/src/main/java/org/spigotmc/SpigotConfig.java#L160-L175>. I'll update this to use the legacy serializer instead.

File: src/main/java/ch/njol/skript/variables/FlatFileStorage.java (hunk 12 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/variables/FlatFileStorage.java:142]: Sure, but I think that would be better in a separate PR. I wanted to touch as little as possible here - just enough to remove the usages of legacy chat API.

**Review by sovdeeth — APPROVED** [review]

**Review by UnderscoreTud — APPROVED** [review]
Great work :)
