### PR TITLE
Local Variable Type Hints

### LINKED ISSUE #1229: Recent function changes break function type safety
```
on script load:
  set {_test} to "a string"
  test({_test})

function test(player: player):
  broadcast "%{_player}% is {_player}"
```
test should never be called, but because null values are now accepted, it will get called with null

### LINKED ISSUE #3864: Local variable type hints. Helps identify local variable return types
Local variable type hints were implemented in 2.2-dev37c, see [dev37c release notes](https://github.com/SkriptLang/Skript/releases/tag/dev37c) and [bug report](https://github.com/SkriptLang/Skript/issues/1379). These were accidentally disabled a couple months later (I think it was accidentally, but I'm not sure tho, GitHub isn't on my side for this one).

**The question is: should these be brought back?**
The implementation will give a warning when loading the script, when the determined type of a simple local variable (a simple local variable is one like `{_a}`, `{_item}`, `{_l::1}`, and not `{_l::%{_i}%}` or `{notLocalVariable}`) doesn't match the required type for its usage. For example, this code would produce such a warning:
```
set {_x} to "Hello, world!"
set {_y} to location of {_x}
```
since `{_x}` is a string, which doesn't have a location.

Another thing to keep in mind is addons, since some addons may change variables in different ways, this is often done when an effect is ran asynchronously, but it has a result that can be stored in a variable, for example:
- [skript-db's execute statement](https://github.com/btk5h/skript-db#effect-execute-statement)
- [skript-mirror/skript-reflect custom syntax (with parse section)](https://tpgamesnl.gitbook.io/skript-reflect/advanced/custom-syntax), because local variables are carried over from the parse section.

These addons would have to be updated, otherwise using them with local variables will produce the warnings.

Any feedback is appreciated (:

### PR DESCRIPTION
**Pull request by APickledWalrus**
### Problem
Local variables are essentially accepted wherever they are used. This results in more potential mistakes and (some) strange syntax behavior that is hard to track. Detailed type information for variables helps in two cases:
#### 1. Mismatched types
It's possible you use the wrong variable somewhere. Detailed type information can catch this and print a warning (or error). Consider:
```applescript
set {_a} to 5
set {_b} to "some string"
... do stuff ...
set {_c} to {_a} in lowercase # oops i used the wrong variable
```
We can catch that `{_a} in lowercase` is likely to be invalid and alert the user.

#### 2. Syntax accepting objects
Consider syntax like ExprArithmetic:
```applescript
set {_a} to "some string"
set {_b} to 1 + {_a}
```
With detailed type information, we can now identify at parse time that this is an invalid operation, instead of failing at runtime and returning none.

### Solution
With systems like ExecutionIntent and multiple return types, we are finally in a position to execute this system well. Type tracking for local variables has been implemented across syntax interacting with variables using a HintManager that is attached to the ParserInstance.

The testing script along with HintManager's documentation provide insight into how hints are managed.

As of now, I believe this system is accurate enough for type issues to be errors rather than warnings. However, there are still scenarios where type hints will fail:
```
loop x times:
  if ...:
    set {_x} to 10
  if ...:
    # will only see {_x} as a number
    set {_x} to x in lowercase
    # do some terminating statement idk
  if ...:
    set {_x} to "hello world"
```
That is, variables in loops whose types are changing across iterations may trigger false-positive errors (in rare cases hidden type changes could cause erroneous runtime failures). To work around this, it is possible to [un]suppress type hints (for a statement or block of code) using a new statement. We may also consider putting this behind an experiment as we continue to improve upon it (maybe whether it's an error?). Variables that cannot have hints and variables that do not have any hints act the same as they do now.

Variables have also been reworked here. When variables are passed to patterns request objects, the possible return types of the variable is simply an array of the known hints. Additionally, when variables are passed to patterns requesting some combination of types, the possible return types of the variable is the intersection of the hints and requested types.

I believe the system is accurate and stable, but further testing is needed. As a result, I have elected to put this behind an experiment. Additionally, it is possible to suppress type hints (in scripts where the experiment is enabled) for specific regions of code.

**Change Explanations**
- Fixed an issue where the `experimentRegistry` (in Skript) was set to null too soon - it could be null even when more script code could run (consider `on stop` triggers)
- Added `getName` to arguments. This is used for providing type hints for named command arguments.
- Fixed an issue where EffReturn would return an incorrect ExecutionIntent for Functions. It needed to be using `StopTrigger` as the `ReturnableTrigger` is stopped in Functions when `return` is executed.
- Added `EntryNode` as a possible return type for ExprNode. This is for ensuring type hints work properly for the syntax.
- Added `beforeChange` runnable for loading sections into triggers. This was necessary for proper type hint implementation for these syntaxes. We need to be able to capture the hints and then merge them in once the trigger is loaded (since we copy variables at runtime).
- Now that some variables may have accurate return types, `Variable#getConvertedExpression` has been updated to restrict what conversions are allowed on those variables.
- Fixed an issue where `Classes#getSuperClassInfo` was not guaranteed to return the exact ClassInfo if one existed.
- I added a new class, `SectionUtils`, which includes a static utility method for loading a section's code into a Trigger. More specifically, it handles the type of behavior that is becoming more common: Loading a section into a Trigger to use different context/events, preventing delays, and copying local variables at runtime. With type hints, the need to copy type hints arose, and the behavior became far more complicated. This method serves to handle that behavior and reduce the effort needed by the increasing number of implementing classes.

#### API Support

Addon developers may need to support this feature if their syntax modifies variables (and results in type changes). First, you can use the HintManager to check if a Variable can use hints:
```java
if (HintManager.canUseHints(variable)) {
    // safe to manage hints
}
```
If so, you can obtain the active HintManager using the ParserInstance:
```java
ParserInstance.get().getHintManager();
```
Then, depending on what type of operation your syntax is performing, you can manage hints as necessary:
```java
HintManager hintManager = ParserInstance.get().getHintManager();
// setting the hints (clears previous hints)
hintManager.set(variable, SomeType.class);
// adding a hint
hintManager.add(variable, SomeType.class);
// clearing hints (e.g. `delete {_var}`)
hintManager.delete(variable);
```

### Testing Completed
I have added a basic `type hints.sk` test (more to come). I plan to implement JUnit testing for HintManager.

### Supporting Information
Depends on:
- https://github.com/SkriptLang/Skript/pull/7891

---
**Completes:**
- #3864
- #1229

**Related:**
- https://github.com/SkriptLang/Skript/pull/7879 (syntax conflicts (due to variables) would benefit from type hints)

### CODE REVIEW

File: src/main/java/ch/njol/skript/ScriptLoader.java [hunk 1]
```diff
@@ -951,6 +951,10 @@ public static ArrayList<TriggerItem> loadItems(SectionNode node) {
 
 		ArrayList<TriggerItem> items = new ArrayList<>();
 
+		// Begin local variable type hints
+		parser.getHintManager().enterScope();
+		boolean freezeHints = false;
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/ScriptLoader.java:956]: some explanation about what 'freezing hints' means would be nice

File: src/main/java/ch/njol/skript/effects/EffChange.java [hunk 2]
```diff
@@ -234,25 +236,45 @@ else if (mode == ChangeMode.SET)
...
+				// special ExprParse handling
+				if (!variable.isSingle() && mode == ChangeMode.SET) {
+					if (ch instanceof ExprParse exprParse) {
+						exprParse.flatten = false;
+					} else if (ch instanceof ExpressionList<?> exprList) {
+						for (Expression<?> expr : exprList.getExpressions()) {
+							if (expr instanceof ExprParse exprParse) {
+								exprParse.flatten = false;
+							}
+						}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/effects/EffChange.java:249]: note that since this is not recursive, it cannot be relied upon to flatter all the possible exprparses
see https://github.com/SkriptLang/Skript/pull/7850

File: src/main/java/ch/njol/skript/ScriptLoader.java [hunk 3]
```diff
@@ -1037,7 +1037,36 @@ public static ArrayList<TriggerItem> loadItems(SectionNode node) {
...
+				// If we are exiting multiple sections, hints should instead be copied to the section we are exiting to
+				// Exiting only one section does not require special behavior
+				if (item.executionIntent() instanceof ExecutionIntent.StopSections intent && intent.levels() > 1) {
+					parser.getHintManager().mergeScope(0, intent.levels());
+					parser.getHintManager().enterScope(); // Enter a new scope to capture all new type hints
+					// Clear scope to prevent duplicate copying
+					// We clear after entering the capturing scope so that the capturing scope still has hints
+					parser.getHintManager().clearScope(1);
+				} else {
+					parser.getHintManager().enterScope(); // Enter a new scope to capture all new type hints
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/ScriptLoader.java:1053]: can you elaborate on why enterScope is used here instead of exitScope?
It seems to me like there are more enters than exits in an arbitrary structure

**Review by sovdeeth — CHANGES_REQUESTED** [review]

File: src/main/java/ch/njol/skript/ScriptLoader.java (hunk 3 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/ScriptLoader.java:1053]: The enter scope call for this condition is to capture type hints. Consider the following code:
```
# do some stuff
exit 3 sections
set {_a} to 5
```
There is type hint information about {_a}, but that code will never actually run, so we don't want to capture those type hints and pass them back up as possible types. So, once we reach a terminating statement (like EffExit), further type hints are ignored. This is accomplished by entering another scope at the beginning (which is what you see here) and at the end of `loadItems`, we clear and exit the scope (clearing it means no hints will be passed back up). This is what the freezeHints variable tracks.

Writing it out though, it might not actually be necessary. Unless the scope is `exit 1 section`, hints on the regular/current scope are already cleared and passed up early (that's what the if of this if/else handles). It's probably fine to do that for `exit 1 section` too and we can avoid this additional scope enter/exit

File: src/main/java/ch/njol/skript/effects/EffChange.java (hunk 2 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/effects/EffChange.java:249]: im fine to change it here, or someone can do a separate PR and ill just integrate it

File: src/main/java/ch/njol/skript/ScriptLoader.java (hunk 3 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/ScriptLoader.java:1053]: I may be misunderstanding but can't you just `mergeScope(0, target)` and freeze on exit x sections and otherwise leave it alone?

File: src/main/java/ch/njol/skript/effects/EffChange.java (hunk 2 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/effects/EffChange.java]: Addressed in https://github.com/SkriptLang/Skript/pull/7915

File: src/main/java/ch/njol/skript/variables/HintManager.java [hunk 4]
```diff
@@ -0,0 +1,468 @@
...
+ * <p>
+ * Type hints are tracked in scopes which are generally equivalent to sections.
+ * However, there may be additional scopes that are not associated with sections.
+ * These scopes may be used for a variety of reasons.
+ * For example, a non-section scope could be used for capturing the hints of a section.
+ * These hints could be filtered before being passed back up.
+ * </p>
+ * <p>
+ * When entering a scope ({@link #enterScope(boolean)}), it is initialized with the hints of the previous top-level scope.
+ * When exiting a scope ({@link #enterScope(boolean)}), remaining hints from that scope are added to the existing hints of the new top-level scope.
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/variables/HintManager.java]:
```suggestion
 * When exiting a scope ({@link #exitScope()}), remaining hints from that scope are added to the existing hints of the new top-level scope.
```

File: src/main/java/ch/njol/skript/sections/EffSecShoot.java [hunk 5]
```diff
@@ -191,12 +195,26 @@ public boolean init(Expression<?>[] exprs, int matchedPattern, Kleenean isDelaye
...
+			Runnable beforeLoading = () -> getParser().getHintManager().enterScope(false);
+			Runnable afterLoading = () -> {
+				delayed.set(!getParser().getHasDelayBefore().isFalse());
+				HintManager hintManager = getParser().getHintManager();
+				hintBackup.set(hintManager.backup());
+				hintManager.exitScope();
+			};
+
+			trigger = loadCode(sectionNode, "shoot", beforeLoading, afterLoading, ShootEvent.class);
+
```
Comment (Absolutionism) [inline src/main/java/ch/njol/skript/sections/EffSecShoot.java]: Just a thought, but could there be a helper method for this? Since `EffSecShoot` , `EffSecSpawn`, `ExprSecCreateWorldBorder` and `ExprSecCreateLootContext` all have this layout?

Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/sections/EffSecShoot.java]: I was thinking about this as well - I'll see if there are any good options

Comment (Absolutionism) [reply src/main/java/ch/njol/skript/sections/EffSecShoot.java]: Alrighty, it would be nice to have, especially with incoming sections from open PRs

**Review by Absolutionism — APPROVED** [review]
Looks good to me. 
also I think EffZombify may be applicable for hint changing

**Review by sovdeeth — APPROVED** [review]
looking good to me

File: src/main/java/ch/njol/skript/lang/parser/ParserInstance.java [hunk 6]
```diff
@@ -533,6 +539,15 @@ public ExperimentSet getExperimentSet() {
 		return set;
 	}
 
+	// Type Hints
+
+	private HintManager hintManager = new HintManager(true);
+
+	@ApiStatus.Experimental
+	public HintManager getHintManager() {
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/lang/parser/ParserInstance.java:550]: could use docs

File: src/main/java/ch/njol/skript/variables/HintManager.java [hunk 7]
```diff
@@ -0,0 +1,468 @@
...
+				break;
+			}
+			currentLevel++;
+		}
+	}
+
+	/**
+	 * Copies hints from one scope to another.
+	 * Scopes are represented as integers, where {@code 0} represents the most recently entered scope
+	 * (i.e. the scope pushed by the most recent {@link #enterScope(boolean)} call).
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/variables/HintManager.java]: this should also explain what int is used for the second most recent scope to establish what the pattern is, as it's not really clear on first read

File: src/main/java/ch/njol/skript/effects/EffSuppressTypeHints.java [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+import ch.njol.util.Kleenean;
+import org.bukkit.event.Event;
+import org.jetbrains.annotations.Nullable;
+import org.skriptlang.skript.lang.experiment.ExperimentData;
+import org.skriptlang.skript.lang.experiment.SimpleExperimentalSyntax;
+
+@Name("Suppress Type Hints (Experimental)")
+@Description({
+	"An effect to suppress local variable type hint errors for the syntax lines that follow this effect.",
+	"NOTE: Suppressing type hints also prevents them from being collected."
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/effects/EffSuppressTypeHints.java]: collected where?

File: src/main/java/ch/njol/skript/variables/HintManager.java [hunk 9]
```diff
@@ -0,0 +1,468 @@
...
+	 * <p>
+	 * <b>Note: This does not overwrite the existing hints of {@code to}. Instead, the hints are merged together.</b>
+	 * @param from The scope to copy hints from.
+ 	 * @param to The scope to copy hints to.
+	 * @param sectionOnly Whether only scopes representing sections should be considered.
+	 */
+	public void mergeScope(int from, int to, boolean sectionOnly) {
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/variables/HintManager.java:208]: i feel like checking whether the ints are in bounds is a good idea here. same goes for the rest of the methods

File: src/main/java/ch/njol/skript/expressions/base/SectionExpression.java [hunk 10]
```diff
@@ -116,15 +125,18 @@ public final Section getAsSection() {
...
+	 * @param beforeLoading A Runnable to execute before the SectionNode has been loaded.
+	 * This occurs after the {@link ParserInstance} context switch.
 	 * @param afterLoading A Runnable to execute after the SectionNode has been loaded.
-	 * This occurs before {@link ParserInstance} states are reset.
+	 * This occurs before {@link ParserInstance} states are reset (context switches back).
 	 * @param events The event(s) during the section's execution.
 	 * @return A trigger containing the loaded section. This should be stored and used
 	 * to run the section one or more times.
 	 */
 	protected Trigger loadCode(SectionNode sectionNode, String name,
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/expressions/base/SectionExpression.java]: should this have @SafeVarargs?

File: src/main/java/ch/njol/skript/lang/ExpressionSection.java [hunk 11]
```diff
@@ -83,8 +83,10 @@ public void setTriggerItems(List<TriggerItem> items) {
 		super.setTriggerItems(items);
 	}
 
-	public Trigger loadCodeTask(SectionNode sectionNode, String name, @Nullable Runnable afterLoading, Class<? extends Event>... events) {
-		return super.loadCode(sectionNode, name, afterLoading, events);
+	public Trigger loadCodeTask(SectionNode sectionNode, String name,
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/lang/ExpressionSection.java]: same varargs here

File: src/main/java/ch/njol/skript/sections/EffSecShoot.java [hunk 12]
```diff
@@ -190,14 +190,11 @@ public boolean init(Expression<?>[] exprs, int matchedPattern, Kleenean isDelaye
...
 
 		if (sectionNode != null) {
-			AtomicBoolean delayed = new AtomicBoolean(false);
-			Runnable afterLoading = () -> delayed.set(!getParser().getHasDelayBefore().isFalse());
-			trigger = loadCode(sectionNode, "shoot", afterLoading, ShootEvent.class);
-			if (delayed.get()) {
-				Skript.error("Delays cannot be used within a 'shoot' effect section");
-				return false;
-			}
+			trigger = SectionUtils.loadLinkedCode("shoot", (beforeLoading, afterLoading)
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/sections/EffSecShoot.java:193]: thoughts about adding a helper method that just has the node, name and event as arguments? that way it ensures nobody will call the wrong method without the runnables

File: src/main/java/ch/njol/skript/ScriptLoader.java [hunk 13]
```diff
@@ -983,11 +992,18 @@ public static ArrayList<TriggerItem> loadItems(SectionNode node) {
 
 				items.add(item);
 			} else if (subNode instanceof SectionNode subSection) {
-				TypeHints.enterScope(); // Begin conditional type hints
 
 				RetainingLogHandler handler = SkriptLogger.startRetainingLog();
 				find_section:
 				try {
+					// enter capturing scope
+					// it is possible that the line may successful parse and initialize (via init), but some other issue
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/ScriptLoader.java]:
```suggestion
					// it is possible that the line may successfully parse and initialize (via init), but some other issue
```

**Review by Efnilite — CHANGES_REQUESTED** [review]

File: src/main/java/ch/njol/skript/expressions/base/SectionExpression.java (hunk 10 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/expressions/base/SectionExpression.java]: Sure, we can do that for the *new* method (I won't touch the existing one however, since it requires making the method final)

File: src/main/java/ch/njol/skript/sections/EffSecShoot.java (hunk 12 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/sections/EffSecShoot.java:193]: We aren't able to call the methods that build the triggers (e.g. `loadCode`) as they have restricted access (and it should probably remain that way). Unless you mean something else

**Review by Efnilite — APPROVED** [review]
