### PR TITLE
Cleanup ExprWorld and fix time state values

### LINKED ISSUE #8200: Past event-location's world don't work as expected
### Skript/Server Version

```markdown
[21:10:38 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:10:38 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:10:38 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:10:38 INFO]: [Skript] Server Version: 1.21.8-60-29c8822 (MC: 1.21.8)
[21:10:38 INFO]: [Skript] Skript Version: 2.12.2 (skriptlang-github)
[21:10:38 INFO]: [Skript] Installed Skript Addons: None
[21:10:38 INFO]: [Skript] Installed dependencies: 
[21:10:38 INFO]: [Skript]  - Vault v1.7.3-b131
[21:10:38 INFO]: [Skript]  - WorldGuard v7.0.14+2339-43997ec
```

### Bug Description

Upon sending the world of a player's location before a teleport event, it returns it's world after the teleport.

### Expected Behavior

Returns the past world.

### Steps to Reproduce

`on player teleport:
  broadcast "%former event-location's world%"`

When teleporting to the nether, it would say "world_nether" for example.

### Errors or Screenshots

_No response_

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by sovdeeth**
### Problem

`former event-location's world` was ambiguous and returning the wrong value sometimes, since `former (event-location's world)` was not properly handled.

### Solution

Cleans up ExprWorld to modern standards. Reworks the get() method so that no matter the type of the input, if timestates are used it will return the correct value.

### Testing Completed

Manual confirmation with:
```
on player teleport: 
    broadcast "%former (event-location's world)%"
    broadcast "%former (event-entity's world)%"
    broadcast "%(former event-location)'s world%"
    broadcast "%(former event-entity)'s world%" # intentionally errors
    broadcast "%former world%"
    broadcast "getFrom: %event.getFrom()%"
    broadcast "getTo: %event.getTo()%"
```

### Supporting Information

---
**Completes:** Fixes #8200 
**Related:** none 
**AI assistance:** none

### CODE REVIEW

File: src/main/java/ch/njol/skript/expressions/ExprWorld.java [hunk 1]
```diff
@@ -41,60 +34,62 @@ public class ExprWorld extends PropertyExpression<Object, World> {
...
+			// - In a PlayerTeleportEvent
+			// - the source expr was the event-value
+			// check the event anyway since it casts for us
+			if (event instanceof PlayerTeleportEvent playerTeleportEvent) {
+				if (getTime() > 0) {
+					// future
+					return playerTeleportEvent.getTo().getWorld();
+				} else if (getTime() < 0) {
+					// past
+					return playerTeleportEvent.getFrom().getWorld();
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/expressions/ExprWorld.java]:
```suggestion
				if (getTime() == TIME_FUTURE) {
					// future
					return playerTeleportEvent.getTo().getWorld();
				} else if (getTime() == TIME_PAST) {
					// past
					return playerTeleportEvent.getFrom().getWorld();
```
for extra clarity (getTime returns -1, 0, or 1 right?)

File: src/main/java/ch/njol/skript/expressions/ExprWorld.java [hunk 2]
```diff
@@ -41,60 +37,62 @@ public class ExprWorld extends PropertyExpression<Object, World> {
...
-			} else if (obj instanceof Chunk) {
-				return ((Chunk) obj).getWorld();
+	protected World[] get(Event event, Object[] source) {
+		return get(source, objInWorld -> {
+			// if getTime is not 0, we know:
+			// - Not delayed
+			// - In a PlayerTeleportEvent
+			// - the source expr was the event-value
+			// check the event anyway since it casts for us
+			if (event instanceof PlayerTeleportEvent playerTeleportEvent) {
```
Comment (Pesekjak) [inline src/main/java/ch/njol/skript/expressions/ExprWorld.java:53]: this should also support EntityTeleportEvent, PlayerChangedWorldEvent, PlayerJumpEvent and VehicleMoveEvent (all of those are supported by Skript but do not extend common class)

File: src/main/java/ch/njol/skript/expressions/ExprWorld.java [hunk 3]
```diff
@@ -41,60 +37,62 @@ public class ExprWorld extends PropertyExpression<Object, World> {
...
 		if (delta == null)
 			return;
 
-		for (Object o : getExpr().getArray(e)) {
-			if (o instanceof Location) {
-				((Location) o).setWorld((World) delta[0]);
+		// TODO: this is suspicious - test if it works in all cases + whether we should have a Location changer instead.
+		for (Object object : getExpr().getArray(event)) {
+			if (object instanceof Location location) {
+				location.setWorld((World) delta[0]);
```
Comment (Pesekjak) [inline src/main/java/ch/njol/skript/expressions/ExprWorld.java:89]: I think changing location world is poor api design by Bukkit and I am not sure we should support this but probably yes due to backwards compatibility (even if it doesn't work as users would expect)

File: src/main/java/ch/njol/skript/expressions/ExprWorld.java (hunk 2 above)
Comment (Pesekjak) [reply src/main/java/ch/njol/skript/expressions/ExprWorld.java:53]: the implementation will be a bit cumbersome as the classes don't share a parent, I suggest a helper method for this

Comment (sovdeeth) [reply src/main/java/ch/njol/skript/expressions/ExprWorld.java:53]: Timestates are only allowed for PTE currently (see setTime). I could do it here, but i'm more focused on fixing the existing impl rather than adding new. Do you think a separate pr is fine or should it be here

File: src/main/java/ch/njol/skript/expressions/ExprWorld.java (hunk 3 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/expressions/ExprWorld.java:89]: yeah this is for future work, not this pr
i agree it's a bit sketchy

File: src/main/java/ch/njol/skript/expressions/ExprWorld.java (hunk 2 above)
Comment (Pesekjak) [reply src/main/java/ch/njol/skript/expressions/ExprWorld.java:53]: I see, both is fine. :) but as you focus on fixing the impl here, separate pr I think makes more sense
