### PR TITLE
Fixed NoSuchMethodException when running tests on Spigot (Closes #7553)

### LINKED ISSUE #7553: Paper only method used without spigot safety
### Skript/Server Version

```markdown
It would be annoying to get /skript info of this so here's the relative info: this occurs when testing with dev mode ON, on spigot  1.21.4 and with Skript 2.10.0
```

### Bug Description

This line https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/Skript.java#L686 uses a paper only method (getChunkAtAsync), this causes issues when testing on spigot.

### Expected Behavior

It shouldn't use a paper method on spigot.

### Steps to Reproduce

Start a testing environment with a spigot server.

### Errors or Screenshots

```
[13:32:03] [Server thread/INFO]: Time elapsed: 775 ms
[13:32:03] [Server thread/INFO]: [Skript] Enabling Skript v2.10.0
[13:32:03] [Server thread/INFO]: [Skript] You're currently running a custom Skript version. No updates will be automatically installed.
[13:32:04] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[13:32:04] [Server thread/INFO]: [Lusk] Enabling Lusk v1.3.3
[13:32:05] [ForkJoinPool.commonPool-worker-1/INFO]: [Skript] Loaded 5440 aliases in 496ms
[13:32:05] [Server thread/INFO]: [Lusk] Loaded 283 elements:
[13:32:05] [Server thread/INFO]: [Lusk]  - 30 events
[13:32:05] [Server thread/INFO]: [Lusk]  - 27 effects
[13:32:05] [Server thread/INFO]: [Lusk]  - 143 expressions
[13:32:05] [Server thread/INFO]: [Lusk]  - 74 conditions
[13:32:05] [Server thread/INFO]: [Lusk]  - 9 sections
[13:32:05] [Server thread/INFO]: [Lusk] Checking for update...
[13:32:05] [Server thread/INFO]: [Lusk] Lusk is up to date!
[13:32:05] [Server thread/INFO]: [Lusk] Lusk 1.3.3 has been enabled! [0.93 seconds]
[13:32:05] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:32:05] [Server thread/INFO]: Done (3.791s)! For help, type "help"
[13:32:05] [Server thread/INFO]: [Skript] Preparing Skript for testing...
[13:32:05] [Server thread/INFO]: [Skript]     Missing entry 'types.testgui' in the default/english language file
[13:32:05] [Server thread/INFO]: [Skript]     Missing entry 'types.exemplus' in the default/english language file
[13:32:05] [Server thread/INFO]: [Skript]     Missing entry 'types.aardwolf' in the default/english language file
[13:32:05] [Server thread/INFO]: [Skript]     Missing entry 'types.hoof' in the default/english language file
[13:32:05] [Server thread/INFO]: [Skript] Loading variables...
[13:32:05] [Server thread/INFO]: [Skript] Loaded 0 variables in 0.0 seconds
[13:32:05] [Server thread/WARN]: [Skript] Task #4 for Skript v2.10.0 generated an exception
java.lang.NoSuchMethodError: 'java.util.concurrent.CompletableFuture org.bukkit.World.getChunkAtAsync(int, int)'
at ch.njol.skript.Skript$1.run(Skript.java:686) ~[?:?]
at org.bukkit.craftbukkit.v1_21_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4430-Spigot-d421948-d20d4c1]
at org.bukkit.craftbukkit.v1_21_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4430-Spigot-d421948-d20d4c1]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1502) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4430-Spigot-d421948-d20d4c1]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1391) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4430-Spigot-d421948-d20d4c1]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1093) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4430-Spigot-d421948-d20d4c1]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4430-Spigot-d421948-d20d4c1]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by JakeGBLP**
### Description
Added chunk-load wait before running tests (when not in DEV_MODE) that doesn't require PaperMC to Skript.class.

---
**Target Minecraft Versions:** any
**Requirements:** Spigot
**Related Issues:** #7553

### CODE REVIEW

File: src/main/java/ch/njol/skript/Skript.java [hunk 1]
```diff
@@ -683,7 +686,22 @@ protected void afterErrors() {
...
+								@EventHandler
+								public void onChunkLoad(ChunkLoadEvent event) {
+									Chunk chunk = event.getChunk();
+									if (chunk.getX() == 100 && chunk.getZ() == 100) {
+										runTests();
+										event.getHandlers().unregister(this);
+									}
+								}
+							}, Skript.getInstance());
+							world.getChunkAt(100, 100);
```
Comment (Efnilite) [inline src/main/java/ch/njol/skript/Skript.java:703]: getChunkAt loads the chunk synchronously so you can just make runTests run after this statement

**Review by Efnilite — CHANGES_REQUESTED** [review]

**Review by Pikachu920 — DISMISSED** [review]
I don't think it makes sense to add spigot support when we are about to drop spigot support.

File: src/main/java/ch/njol/skript/Skript.java [hunk 2]
```diff
@@ -680,13 +681,20 @@ protected void afterErrors() {
 				debug("Early init done");
 
 				if (TestMode.ENABLED) {
-					if (TestMode.DEV_MODE) {
+					if (!TestMode.DEV_MODE) {
```
Comment (ShaneBeee) [inline src/main/java/ch/njol/skript/Skript.java:684]: Im confused on this change, but wouldn't this make the delay only have if theyre running dev mode?!?!
Completely the opposite of that goal here.

File: src/main/java/ch/njol/skript/Skript.java [hunk 3]
```diff
@@ -680,13 +681,20 @@ protected void afterErrors() {
...
 						runTests(); // Dev mode doesn't need a delay
 					} else {
-						Bukkit.getWorlds().get(0).getChunkAtAsync(100, 100).thenRun(() -> runTests());
+						World world = Bukkit.getWorlds().get(0);
+						if (isPaper()) {
+							world.getChunkAtAsync(100, 100).thenRun(() -> runTests());
+						} else {
+							world.getChunkAt(100, 100);
```
Comment (ShaneBeee) [inline src/main/java/ch/njol/skript/Skript.java:691]: Skript shades in PaperLib, and PaperLib has a getChunkAsync method which would run asynchronous on paper, and sync on Spigot

File: src/main/java/ch/njol/skript/Skript.java (hunk 2 above)
Comment (JakeGBLP) [reply src/main/java/ch/njol/skript/Skript.java:684]: This was a mistake!

**Comment by ShaneBeee** [comment]
> It's not a high effort change, for the duration of 2.10, and perhaps 2.11 if end of spigot support is delayed, I'd like this to be fixed, but even then if nothing is reverted and the end of support simply consists in not checking if the server is running paper when adding something from it then this would be very good, it would be helpful to me and anybody else looking to support spigot EVEN if skript doesn't do that itself and assuming that it loads with no issues.

correct me if Im wrong, but tests are ONLY run on Paper.
After reading your changes and commenting on it.... I just wanted to point out here is no async chunk loading when running dev mode. Outside of dev mode, all tests are run on Paper servers.

**Comment by JakeGBLP** [comment]
> > It's not a high effort change, for the duration of 2.10, and perhaps 2.11 if end of spigot support is delayed, I'd like this to be fixed, but even then if nothing is reverted and the end of support simply consists in not checking if the server is running paper when adding something from it then this would be very good, it would be helpful to me and anybody else looking to support spigot EVEN if skript doesn't do that itself and assuming that it loads with no issues.
> 
> correct me if Im wrong, but tests are ONLY run on Paper. After reading your changes and commenting on it.... I just wanted to point out there is no async chunk loading when running dev mode. Outside of dev mode, all tests are run on Paper servers.

The goal of this PR is to handle the scenario in which an addon were to run tests on Spigot since Skript only runs them on Paper.

**Review by Efnilite — APPROVED** [review]

File: src/main/java/ch/njol/skript/Skript.java [hunk 4]
```diff
@@ -683,10 +683,11 @@ protected void afterErrors() {
 					if (TestMode.DEV_MODE) {
 						runTests(); // Dev mode doesn't need a delay
 					} else {
-						Bukkit.getWorlds().get(0).getChunkAtAsync(100, 100).thenRun(() -> runTests());
+						PaperLib.getChunkAtAsync(Bukkit.getWorlds().get(0), 100, 100).thenRun(() -> runTests());
 					}
 				}
 
+
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/Skript.java:690]:
```suggestion
```

**Review by sovdeeth — CHANGES_REQUESTED** [review]

**Comment by TheAbsolutionism** [comment]
> I don't think it makes sense to add spigot support when we are about to drop spigot support.

In my opinion, Jake's reasons are valid. Even though Skript does plan on dropping support for Spigot, nothing has been said as what version of Skript will be doing so. If the team does plan on dropping support for 2.11 or any version after, regardless, 2.10 still supports Spigot. So we should be fixing any bugs that occur before parting ways. Meaning we need to fix the test environment (this PR) in order to find and fix any bugs/errors.
For instance, both Shane and Sovde had tested on Spigot and found bugs which PRs were made to fix and have been merged for 2.10.

**Comment by TheAbsolutionism** [comment]
With that said, the labels need to be changed. Removing `enhancement` and adding back `bug` so it can appropriately be marked and merged for the next patch release.

**Comment by ShaneBeee** [comment]
> With that said, the labels need to be changed. Removing `enhancement` and adding back `bug` so it can appropriately be marked and merged for the next patch release.

Its not a bug tho.
Jake copy/pasted Skript's Test platform runner classes, and added his own environments... this isn't something Skript was meant to do.
There is no bug here, Skript's testing environment was setup to use Paper, and works as it was intended to.
Nothing is broken.

**Comment by JakeGBLP** [comment]
> > With that said, the labels need to be changed. Removing `enhancement` and adding back `bug` so it can appropriately be marked and merged for the next patch release.
> 
> Its not a bug tho. Jake copy/pasted Skript's Test platform runner classes, and added his own environments... this isn't something Skript was meant to do. There is no bug here, Skript's testing environment was setup to use Paper, and works as it was intended to. Nothing is broken.

I think it's more of something nobody wanted to be bothered to do, spigot support has almost become an optional over the last few updates, that being said I think having spigot tests is ideal for a Spigot-supporting plugin, so if that were to be the plan it would be convenient to have them; some people don't love having many testing environments, I don't mind it at all, it's very helpful since it's fully automated (once you set it up) and makes tests all the more worthwhile since we go from running a few environments to a bunch of them if not EVERY possible environment:

TL;DR: if we consider Skript as a spigot plugin then this is a bug.

**Review by sovdeeth — APPROVED** [review]

**Comment by sovdeeth** [comment]
this isn't a bug, period. That said, using paperlib to have broader support without, like, any downside seems like a fine enhancement.
