### PR TITLE
Function overloading fixes and improvements

### LINKED ISSUE #8030: Reimplement existing function type and script
### Suggestion

The [Function overloading PR](https://github.com/SkriptLang/Skript/pull/7757) removed the function type (`global`/`local`) from the error message and the script that it is located in if it already exists.

Should add those back.

### Why?

Differentiating the function type in the error message ensures the code works and provides extra information to the user.
Informs the user of which script the existing function is in.

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

### LINKED ISSUE #8031: FunctionIdentifier#toString throws NPE
### Skript/Server Version

```markdown
dev/feature
```

### Bug Description

When using  `FunctionRegistry.getRegistry.getFunction(null, "name", null)` this creates a `FunctionIdentifier` with the field `args` being `null`, but the `toString` does not  account for it being `null`

### Expected Behavior

Not to throw an NPE

### Steps to Reproduce

`FunctionRegistry.getRegistry.getFunction(null, "name", null)`

### Errors or Screenshots

Image

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by Efnilite**
### Problem
1. Fixes overloading for functions with no parameters. Previously, passing no parameters to `getFunction` or `getSignature` would match any function with the specified name. Now, passing no parameters will only match functions that also have no parameters.
2. Fixes overloading for functions with array parameters. Previously, if a function had an array as parameters, any function with the same name of the function would be matched. This would not allow for two version of, for example, `clamp` to exist. Now, instead of matching any function with the same name, the arguments are actually checked 
3. Removes outdated documentation for FunctionIdentifier (fixes #8031)
4. Adds more detailed error messages to the "function already exists" error (fixes #8030)

### Solution
1. Updates `candidates` to avoid returning any function when zero args are provided in the `provided` FunctionIdentifier.
2. First, Adds a single list value check to `candidates`, so functions like `mean` actually get matched on argument types. Second, for functions like `clamp(1, 2, 3)`, adds a check to allow `1` to pass as a list. Third, removes outdated code from SkriptParser for parsing single list value params.
3. Updated documentation.
4. Improved error message.

### Testing Completed
1. Adds a test.
2. Existing tests for functions like clamp and mean are sufficient.
3. NA
4. NA

### Supporting Information
Updates the test for StructFunction with local type hints as this part is now handled by FunctionReference.

---
**Completes:** #8030, #8031 
**Related:** none

### CODE REVIEW

File: src/main/java/ch/njol/skript/lang/function/Functions.java [hunk 1]
```diff
@@ -174,7 +174,22 @@ public static JavaFunction<?> registerFunction(JavaFunction<?> function) {
...
+				error.append("Local function ");
+			} else {
+				error.append("Function ");
+			}
+			error.append("'%s' with the same argument types already exists".formatted(signature.getName()));
+			if (existing.retrieved().isLocal()) {
+				error.append(" in script '%s'.".formatted(existing.retrieved().script));
+			} else {
+				error.append(".");
+			}
```
Comment (Absolutionism) [inline src/main/java/ch/njol/skript/lang/function/Functions.java]: Shouldn't this be reversed?

Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/function/Functions.java]: no, but now that you mention it, this can be improved to always print if there's a script available

Comment (Absolutionism) [reply src/main/java/ch/njol/skript/lang/function/Functions.java]: Well, if it's a local function, `existing.retrieved().isLocal()` then it's safe to presume that the existing local function is in the same script.
If it's a global function, then it should output the name of the script that the existing function is located in.

**Review by Absolutionism — APPROVED** [review]

File: src/main/java/ch/njol/skript/lang/function/FunctionReference.java [hunk 2]
```diff
@@ -133,12 +134,29 @@ public boolean validateFunction(boolean first) {
...
 
+		StringJoiner args = new StringJoiner(", ");
+		for (Class<?> parameterType : parameterTypes) {
+			Class<?> searchType;
+			if (parameterType.isArray()) {
+				searchType = parameterType.componentType();
+			} else {
+				searchType = parameterType;
+			}
+			ClassInfo<?> exact = Classes.getExactClassInfo(searchType);
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/function/FunctionReference.java]: You can use getSuperClassInfo instead (likely to produce better results)

**Review by sovdeeth — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]
