### PR TITLE
Replace the Visual Effect system

### LINKED ISSUE #4196: Error saving visual effect
### Skript/Server Version

[15:58:50 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[15:58:50 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[15:58:50 INFO]: [Skript] Server Version: git-Purpur-1271 (MC: 1.17.1)
[15:58:50 INFO]: [Skript] Skript Version: 2.6-beta2
[15:58:50 INFO]: [Skript] Installed Skript Addons:
[15:58:50 INFO]: [Skript]  - skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders)
[15:58:50 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[15:58:50 INFO]: [Skript]  - SkQuery v4.1.5
[15:58:50 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)

### Bug Description

Error on using virtual effect as command argument type 

### Expected Behavior

Argument to work without error

### Steps to Reproduce

command /test [<visual effect>] [<text>]

### Errors or Screenshots

java.lang.NoClassDefFoundError: ch/njol/skript/util/VisualEffect
        at net.rayfall.eyesniper2.skrayfall.effectlibsupport.EffEffectLibText.execute(EffEffectLibText.kt:54) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:258) ~[?:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1271]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1271]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1271]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2293) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2112) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2093) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1271]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! [Skript] Severe Error:
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Something went horribly wrong with Skript.
[15:54:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:54:32 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:54:32 ERROR]: #!#! Here is full list of them:
[15:54:32 ERROR]: #!#! skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.26 (https://sk.rayfall.net/) SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.5 DiscordSRV v1.23.0 (https://github.com/DiscordSRV/DiscordSRV) 
[15:54:32 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:54:32 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:54:32 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:54:32 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:54:32 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:54:32 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Stack trace:
[15:54:32 ERROR]: #!#! java.io.NotSerializableException: ch.njol.skript.util.visual.VisualEffectType
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:174)
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:199)
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:730)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:527)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:521)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:531)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:364)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:355)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Variable.set(Variable.java:441)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Variable.change(Variable.java:497)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194)
[15:54:32 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:54:32 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[15:54:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2301)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2112)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2093)
[15:54:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:54:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:54:32 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:54:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Version Information:
[15:54:32 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[15:54:32 ERROR]: #!#!     Flavor: skriptlang-github
[15:54:32 ERROR]: #!#!     Date: 08:57:41.422360
[15:54:32 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[15:54:32 ERROR]: #!#!   Minecraft: 1.17.1
[15:54:32 ERROR]: #!#!   Java: 16.0.1 (OpenJDK 64-Bit Server VM 16.0.1+9-24)
[15:54:32 ERROR]: #!#!   OS: Linux amd64 5.8.0-1036-azure
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Server platform: Paper
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Current node: null
[15:54:32 ERROR]: #!#! Current item: null
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Thread: Server thread
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Language: english
[15:54:32 ERROR]: #!#! Link parse mode: DISABLED
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! End of Error.
[15:54:32 ERROR]: #!#! 

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

### LINKED ISSUE #5146: Make visual effect more user friendly.
### Suggestion

Seen many users get unknown effect errors by simply missing/changing a few words.

https://github.com/SkriptLang/Skript/blob/aa62e8984ceb749df17f1a2d1a6f8da0cbc9c1ff/src/main/resources/lang/default.lang#L1285

`[[with] [(1¦offset (of|by) %-number%, %-number%(,| and) %-number%)][(2¦[(and|at) ]speed %-number%)]]`
this could change `(of|by)` to an optional `[(of|by)]`, and add `with` to `(and|at)` to be `(and|at|with)`
`[[with] [(1¦offset [(of|by)] %-number%, %-number%(,| and) %-number%)][(2¦[(and|at|with) ]speed %-number%)]]`

The offset could also take in a vector
`[[with] [(1¦offset [(of|by)] (%-number%, %-number%(,| and) %-number%|vector:%-vector%))][(2¦[(and|at|with) ]speed %-number%)]]`

Also add `of` to EffVisualEffect's syntax to be `%number% [of] %visualeffects%` as some visual effect names are correct with the usage of the word `of` it's also solidified in Skript users minds to use the word `of` https://github.com/SkriptLang/Skript/blob/fda4fada416b1a9283383d1b661bfb5ba381b5dd/src/main/java/ch/njol/skript/effects/EffVisualEffect.java#L51

### LINKED ISSUE #5702: Exception on playing particle infront of player
### Skript/Server Version

```markdown
1.19.4 test server of v2.7.0-beta2-nightly-20eb553c2
```

### Bug Description

using play cloud in front of player throws an exception, probably just an Assertion error which is present in test server. Shouldn't be happening.

### Steps to Reproduce

play cloud in front of player

### Errors or Screenshots

```
[21:07:47 ERROR]: Could not pass event AsyncPlayerChatEvent to Skript v2.7.0-beta2-nightly-20eb553c2
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.concurrent.Future.get()" is null
        at ch.njol.skript.command.Commands$2.onPlayerChat(Commands.java:322) ~[Skript.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-538]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2402) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2558) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2231) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:07:47 WARN]: [Skript] Task #14 for Skript v2.7.0-beta2-nightly-20eb553c2 generated an exception
java.lang.AssertionError: null
        at ch.njol.skript.util.visual.VisualEffect.play(VisualEffect.java:73) ~[Skript.jar:?]
        at ch.njol.skript.effects.EffVisualEffect.execute(EffVisualEffect.java:126) ~[Skript.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript.jar:?]
        at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:222) ~[Skript.jar:?]
        at ch.njol.skript.command.Commands$2$1.call(Commands.java:316) ~[Skript.jar:?]
        at ch.njol.skript.command.Commands$2$1.call(Commands.java:313) ~[Skript.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftFuture.run(CraftFuture.java:88) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:07:47 INFO]: <LimeGlass> \play cloud in front of player
```

### LINKED ISSUE #7932: Missing Additional Data in Visual Effect throws Exceptions
### Skript/Server Version

```markdown
I can't run any commands, because the server errors happen immediately after the server is online. But I know the server version is 1.21.5, Skript is v2.11.2 and SkBee is v3.11.3
```

### Bug Description

When I try to start my server, everything is fine so far. But after Skript and SkBee are both finished loading, an ABSOLUTE TON of errors are thrown by Skript, almost as if every single possible feature is throwing an error. It's simply endless, I have to kill my server and reload my Falix page (by the way, I'm using Falix as a server host) to stop the server.

### Expected Behavior

Both plugins are supposed to work, no errors or anything. Right now, they hate each other apparently. I didn't know whether to post this issue on Skript or SkBee, but since Skript is the one crying, I'm doing it here.

### Steps to Reproduce

I guess you can try this, although I don't know if the errors are cause of the scripts I've written.
1. Skript 2.11.2 installed
2. SkBee 3.11.3 installed (make sure it's only those two)
3. Try to start your server
4. Do you now get endless errors after they both finish loading?

### Errors or Screenshots

If you don't believe me, here's a screenshot of the start of the endless errors, where it says why it might be happening:

Image

It even says the server is online, the errors begin right after.

### Other

Other plugins I have:
1. AuthMe 5.6.0
2. worldedit-bukkit-7.3.11

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### LINKED ISSUE #8157: Missing particle BLOCK_CRUMBLE
### Skript/Server Version

```markdown
2.12.1
```

### Bug Description

Skript is missing the particle in lang [BLOCK_CRUMBLE](https://jd.papermc.io/paper/1.21.8/org/bukkit/Particle.html#BLOCK_CRUMBLE) within the visual effect system

### Expected Behavior

To be able to play a block crumble particle.

### Steps to Reproduce

show effect doesn't have block crumble

### Errors or Screenshots

_No response_

### Other

There is an existing block visual effect? But it's for the footstep of a block and doesn't signify block breaking at all like it used to. `%blockdata/itemtype% breaking`

Behavior was changed for 1.20.5 changes

What should be done is the block and block footsteps should be created, fix up the old naming and add block crumble. "block" should also equal block crumble to solve backwards compatibility. The particle doesn't outline the blocks anymore, but support for that should be added too.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by sovdeeth**
### Problem

Visual effects were on their last legs. The increase in particles requiring data and constant changes in what effects/particles existed meant that visual effects was not up to date, had problems with serializing values, was lacking functionality, and was horribly documented. Users were nearly always using SkBee's or skript-particle's particle syntaxes instead, as they featured fully functional syntax for setting offsets, data, and were reliable.

### Solution

This PR separates visual effects into three categories: Game Effects (Effect.class), Entity Effects (EntityEffect.class), and Particle Effects (Particle.class, ParticleBuilder.class).

#### Game Effects.
Game effects are rather powerful effects to display particles, play sounds, or both at once. They make it easy to replicate existing ingame effects, like waxing, dispenser activations, turtle eggs cracking, and more. Very little changes from visual effects except that effects that do not require data are automatically supported, while data-requiring effects have a specific expression with documented patterns. This should alleviate the lack of docs for visual effects, who depended entirely on lang file entries for patterns and therefore were not documented.

#### Entity Effects
Entity effects do not require data and are therefore much simpler than game or particle effects. This PR mostly maintains the system from Visual Effect, though modernised with EnumClassInfo. The separation into its own classinfo, though, allows better parse time type checking and ensures entity effects aren't played at locations and are instead played at acceptable entities.

#### Particle Effects
Particle effects are the most complex and required the most work. Simple particle effects without data are now parsed via an EnumClassInfo and the data-requiring ones are registered in an expression like game effects. The particle system is now backed by a new ParticleEffect class, though, which extends Paper's ParticleBuilder class to provide storage of type, data, offset, speed, count, recipients, and more. This allows Skript to provide an easy to use and powerful particle api to addons without each needing its own wrapper class. 

Since particles vary in behavior depending on count being 0 or 1+, ParticleEffect provides an ease of use function to set the particle distribution (the behavior of `offset` when count is 1+) which sets count to 1 if it is 0. You can also check whether it is in distribution mode. For behavior when count is 0, child classes of DirectionalEffect, ScalableEffect, and more exist to provide api to handle their behaviors, such as setting velocity or scale. These likewise set count to 0 if it is not already 0. This behavior is mirrored in the syntax, where `velocity of {particle}` is not set if count > 0, and setting it will set count to 0. This should provide the most intuitive and natural experience for the user, as setting the velocity will ensure the offset is treated as velocity, while setting the distribution will likewise ensure the offset is a distribution.

#### Drawing
Drawing all three effect types is handled through a single EffDrawEffect syntax which provides the extra options for each. This will likely be changed to a type property syntax in the future.

### Testing Completed

EffDrawEffect.sk

### Supporting Information

A helper class was added to yggsdrasil to aid in registering serializers for external classes without classinfos.

Some of the syntaxes will likely be replaced by type properties in a later PR.

Significant breaking changes as Visual Effects will be removed and patterns will change for nearly all effects.

---
**Completes:** #8157 #7932 #5702 #5146 #4196 
**Related:** none

### CODE REVIEW

File: src/main/java/ch/njol/skript/expressions/ExprVelocity.java [hunk 1]
```diff
@@ -1,68 +1,100 @@
...
+})
+@Example("set player's velocity to {_v}")
+@Example("set the velocity of {_particle} to vector(0, 1, 0)")
+@Example("""
+	if the vector length of the player's velocity is greater than 5:
+	    send "You're moving fast!" to the player
+	""")
 @Since("2.2-dev31")
-public class ExprVelocity extends SimplePropertyExpression<Entity, Vector> {
+public class ExprVelocity extends SimplePropertyExpression<Object, Vector> {
```
Comment (UnderscoreTud) [inline src/main/java/ch/njol/skript/expressions/ExprVelocity.java:30]: could this be turned into a type property?

File: src/main/java/ch/njol/skript/expressions/ExprVelocity.java [hunk 2]
```diff
@@ -1,68 +1,100 @@
...
+			return Vector.fromJOML(particleEffect.velocity());
+		return null;
 	}
 
 	@Override
-	@Nullable
-	@SuppressWarnings("null")
-	public Class<?>[] acceptChange(ChangeMode mode) {
+	public Class<?> @Nullable [] acceptChange(ChangeMode mode) {
 		if ((mode == ChangeMode.ADD || mode == ChangeMode.REMOVE || mode == ChangeMode.SET || mode == ChangeMode.DELETE || mode == ChangeMode.RESET))
```
Comment (UnderscoreTud) [inline src/main/java/ch/njol/skript/expressions/ExprVelocity.java]: use switch

File: src/main/java/ch/njol/skript/expressions/ExprXOf.java [hunk 3]
```diff
@@ -74,20 +74,27 @@ protected Object[] get(Event event, Object[] source) {
 		if (amount == null)
 			return (Object[]) Array.newInstance(getReturnType(), 0);
 
+		long absAmount = Math.abs(amount.longValue());
```
Comment (UnderscoreTud) [inline src/main/java/ch/njol/skript/expressions/ExprXOf.java]: i don't think `-10 of x` should be treated the same as `10 of x`

File: src/main/java/ch/njol/util/VectorMath.java [hunk 4]
```diff
@@ -106,6 +106,9 @@ public static float wrapAngleDeg(float angle) {
 		return ExprVectorFromYawAndPitch.wrapAngleDeg(angle);
 	}
 
+	/**
+	 * Copies vector components of {@code vector2} into {@code vector1}.
+	 */
 	public static void copyVector(Vector vector1, Vector vector2) {
 		vector1.copy(vector2);
 	}
```
Comment (UnderscoreTud) [inline src/main/java/ch/njol/util/VectorMath.java:111]: what's the point of this method? it's shorter to write `vector1.copy(vector2)` directly

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java [hunk 5]
```diff
@@ -0,0 +1,176 @@
...
+	used carefully!
+	""")
+@Example("draw 2 smoke particles at player")
+@Example("force draw 10 red dust particles of size 3 for player")
+@Example("play blue instant splash potion break effect with a view radius of 10")
+@Example("play ravager attack animation on player's target")
+public class EffPlayEffect extends Effect {
+	static {
+		Skript.registerEffect(EffPlayEffect.class,
+		"[:force] (play|show|draw) %gameeffects/particles% [%-directions% %locations%] [as %-player%]",
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java]:
```suggestion
			"[:force] (play|show|draw) %gameeffects/particles% [%-directions% %locations%] [as %-player%]",
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleDistribution.java [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+
+	@Override
+	public @Nullable Vector convert(ParticleEffect from) {
+		return from.isUsingNormalDistribution() ? Vector.fromJOML(from.distribution()) : null;
+	}
+
+	@Override
+	public Class<?> @Nullable [] acceptChange(ChangeMode mode) {
+		return switch (mode) {
+			case SET, RESET -> new Class[]{Vector.class};
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleDistribution.java]: could add support for add and remove since you do that for particle offset

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleScale.java [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+	
+	More detailed information on particle behavior can be found at \
+	<a href="https://docs.papermc.io/paper/dev/particles/#count-argument-behavior">Paper's particle documentation</a>.
+	""")
+@Example("set the scale of {_my-explosion-particle} to 2.3")
+@Since("INSERT VERSION")
+public class ExprParticleScale extends SimplePropertyExpression<ScalableEffect, Number> {
+
+	static {
+		register(ExprParticleScale.class, Number.class, "scale [value]", "scalableparticles");
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleScale.java]: type property?

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleSpeed.java [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+	
+	More detailed information on particle behavior can be found at \
+	<a href="https://docs.papermc.io/paper/dev/particles/#count-argument-behavior">Paper's particle documentation</a>.
+	""")
+@Example("set the speed of {_my-flame-particle} to 2")
+@Since("INSERT VERSION")
+public class ExprParticleSpeed extends SimplePropertyExpression<ParticleEffect, Number> {
+
+	static {
+		register(ExprParticleSpeed.class, Number.class, "(speed|extra) [value]", "particles");
```
Comment (UnderscoreTud) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleSpeed.java]: should probably make `particle` obligatory with `speed` to avoid possible conflicts as its a bit too vague

File: src/main/java/org/skriptlang/skript/bukkit/particles/ParticleUtils.java [hunk 9]
```diff
@@ -0,0 +1,213 @@
...
+				Particle.GLOW,
+				Particle.INFESTED,
+				Particle.INSTANT_EFFECT,
+				Particle.RAID_OMEN,
+				Particle.TRIAL_OMEN,
+				Particle.WITCH
+				//</editor-fold>
+			));
+	private static final RegistryKeySet<@NotNull Particle> SCALABLE_PARTICLES = RegistrySet.keySetFromValues(PARTICLE_REGISTRY_KEY,
+			List.of(
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/ParticleUtils.java]: is there a source for this set?

File: src/main/java/ch/njol/yggdrasil/SimpleClassSerializer.java [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+	public @Nullable Class<? extends T> getClass(String id) {
+		return this.id.equals(id) ? this.type : null;
+	}
+
+	@Override
+	public @Nullable String getID(Class<?> clazz) {
+		return this.type.equals(clazz) ? this.id : null;
+	}
+
+	public static abstract class NonInstantiableClassSerializer<T> extends SimpleClassSerializer<T> {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/yggdrasil/SimpleClassSerializer.java:44]: docs and maybe make some of the "restricted" methods final?

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java [hunk 11]
```diff
@@ -0,0 +1,176 @@
...
+			.append("play", toDraw)
+			.appendIf(locations != null, locations)
+			.appendIf(toPlayers != null, "for", toPlayers)
+			.toString();
+	}
+
+	@Override
+	public Node getNode() {
+		return node;
+	}
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java:182]:
```suggestion
	}

```

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java [hunk 12]
```diff
@@ -0,0 +1,176 @@
...
+		if (this.entities != null) {
+			Entity[] entities = this.entities.getArray(event);
+			EntityEffect[] effects = (EntityEffect[]) toDraw.getArray(event);
+			drawEntityEffects(effects, entities);
+			return;
+		}
+
+		// game effects / particles
+		assert this.locations != null;
+		Number radius = this.radius != null ? this.radius.getSingle(event) : null;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java]: do we need null checks for the results of these `getSingle` calls?

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java [hunk 13]
```diff
@@ -0,0 +1,86 @@
...
+		return switch (mode) {
+			case SET, ADD, REMOVE, RESET -> new Class[]{Number.class};
+			default -> null;
+		};
+	}
+
+	@Override
+	public void change(Event event, Object @Nullable [] delta, ChangeMode mode) {
+		ParticleEffect[] particleEffect = getExpr().getArray(event);
+		if (particleEffect == null) return;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java]:
```suggestion
		if (particleEffect == null)
			return;
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java [hunk 14]
```diff
@@ -0,0 +1,86 @@
...
+		int countDelta = 0;
+		if (mode != ChangeMode.RESET) {
+			assert delta != null;
+			if (delta[0] == null) return;
+			countDelta = ((Number) delta[0]).intValue();
+		}
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java]:
```suggestion
		int countDelta = delta == null ? 0 : ((Number) delta[0]).intValue();
```
delta will never contain null values

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java [hunk 15]
```diff
@@ -0,0 +1,86 @@
...
+					effect.count(Math.clamp(effect.count() + countDelta, 0, 1000));
+				break;
+			case SET:
+				for (ParticleEffect effect : particleEffect)
+					effect.count(Math.clamp(countDelta, 0, 1000)); // Limit count to 1000 to prevent unintended crashing
+				break;
+			case RESET:
+				for (ParticleEffect effect : particleEffect)
+					effect.count(0);
+				break;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java]:
```suggestion
			case SET:
			case RESET:
				countDelta = Math.clamp(countDelta, 0, 1000);
				for (ParticleEffect effect : particleEffect)
					effect.count(countDelta); // Limit count to 1000 to prevent unintended crashing
				break;
```
Save on unnecessary clamps + reduce complexity

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleDistribution.java [hunk 16]
```diff
@@ -0,0 +1,90 @@
...
+			default -> null;
+		};
+	}
+
+	@Override
+	public void change(Event event, Object @Nullable [] delta, ChangeMode mode) {
+		ParticleEffect[] particleEffect = getExpr().getArray(event);
+		if (particleEffect == null) return;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleDistribution.java]:
```suggestion
```
getArray will never return null

maybe if you want an empty check?
```suggestion
		if (particleEffect.length == 0)
			return;
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleDistribution.java [hunk 17]
```diff
@@ -0,0 +1,90 @@
...
+			case SET:
+				for (ParticleEffect effect : particleEffect)
+					effect.distribution(newVector);
+				break;
+			case RESET:
+				for (ParticleEffect effect : particleEffect)
+					effect.distribution(new Vector3d(0,0,0));
+				break;
+		}
+	}
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleDistribution.java]:
```suggestion
		Vector3d newVector = delta == null ? new Vector3d(0,0,0) : ((Vector) delta[0]).toVector3d();
		for (ParticleEffect effect : particleEffect)
			effect.distribution(newVector);
	}
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleOffset.java [hunk 18]
```diff
@@ -0,0 +1,86 @@
...
+	@Override
+	public Class<?> @Nullable [] acceptChange(ChangeMode mode) {
+		return switch (mode) {
+			case SET, ADD, REMOVE, RESET -> new Class[]{Vector.class};
+			default -> null;
+		};
+	}
+
+	@Override
+	public void change(Event event, Object @Nullable [] delta, ChangeMode mode) {
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleOffset.java:54]: can be optimized similar to other comments

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithData.java [hunk 19]
```diff
@@ -0,0 +1,105 @@
...
+	private Expression<?>[] expressions;
+	private EffectInfo<Particle, Object> effectInfo;
+	private Expression<Number> count;
+
+	@Override
+	@SuppressWarnings("unchecked")
+	public boolean init(Expression<?>[] expressions, int matchedPattern, Kleenean isDelayed, ParseResult parseResult) {
+		this.parseResult = parseResult;
+		// exclude count expr
+		this.expressions = Arrays.copyOfRange(expressions, 1,  expressions.length);
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithData.java]:
```suggestion
		this.expressions = Arrays.copyOfRange(expressions, 1, expressions.length);
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithData.java [hunk 20]
```diff
@@ -0,0 +1,105 @@
...
+		Object data = effectInfo.dataSupplier().getData(event, expressions, parseResult);
+		if (data == null) {
+			error("Could not obtain required data for " + ParticleEffect.toString(effectInfo.effect(), 0));
+			return null;
+		}
+		ParticleEffect effect = ParticleEffect.of(effectInfo.effect());
+		effect.data(data);
+		if (this.count != null) {
+			Number count = this.count.getSingle(event);
+			if (count != null) {
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithData.java:90]: do you think a warning is valuable if it is null? since the effect is built anyway

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithOffset.java [hunk 21]
```diff
@@ -0,0 +1,109 @@
...
+		Mode(BiFunction<ParticleEffect, Vector3d, ParticleEffect> apply) {
+			this.apply = apply;
+		}
+
+		public ParticleEffect apply(ParticleEffect particle, Vector3d offset) {
+			return this.apply.apply(particle, offset);
+		}
+	}
+
+	static Patterns<Mode> patterns = new Patterns<>(new Object[][]{
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithOffset.java]: `final` and/or `private`?

File: src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataGameEffects.java [hunk 22]
```diff
@@ -0,0 +1,194 @@
...
+
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+
+/**
+ * Registry and utility class for game effects that require data.
+ */
+public class DataGameEffects {
+	private static final List<EffectInfo<Effect, ?>> GAME_EFFECT_INFOS = new ArrayList<>();
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataGameEffects.java:24]:
```suggestion

	private static final List<EffectInfo<Effect, ?>> GAME_EFFECT_INFOS = new ArrayList<>();
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/registration/ToString.java [hunk 23]
```diff
@@ -0,0 +1,24 @@
...
+import org.bukkit.event.Event;
+import org.jetbrains.annotations.NotNull;
+
+/**
+ * A functional interface for converting a particle and its data to a string representation.
+ * Effectively a custom {@link ch.njol.skript.lang.Debuggable#toString(Event, boolean)} method.
+ */
+@FunctionalInterface
+public interface ToString {
+	/**
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/registration/ToString.java:16]:
```suggestion

	/**
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/registration/ToString.java [hunk 24]
```diff
@@ -0,0 +1,24 @@
...
+	 * Converts the particle and provided data to a string representation.
+	 *
+	 * @param exprs The expressions used to parse the data
+	 * @param parseResult The parse result from parsing
+	 * @param builder The {@link SyntaxStringBuilder} to append to
+	 * @return The {@link SyntaxStringBuilder} with the string representation appended
+	 */
+	SyntaxStringBuilder toString(Expression<?> @NotNull [] exprs, ParseResult parseResult, SyntaxStringBuilder builder);
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/registration/ToString.java:24]:
```suggestion
	SyntaxStringBuilder toString(Expression<?> @NotNull [] exprs, ParseResult parseResult, SyntaxStringBuilder builder);

```

File: src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataSupplier.java [hunk 25]
```diff
@@ -0,0 +1,153 @@
...
+
+/**
+ * A functional interface for supplying data to effects from parsed expressions.
+ * Effectively an {@link Expression} in disguise. Accepts the parsed context of expressions and parse result,
+ * spits out the required data value.
+ * @param <D> the data type to supply
+ */
+@FunctionalInterface
+public interface DataSupplier<D> {
+	/**
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataSupplier.java:24]:
```suggestion

	/**
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataGameEffects.java [hunk 26]
```diff
@@ -0,0 +1,194 @@
...
+			DataSupplier::getNumberDefault10,
+			(exprs, parseResult, builder) -> builder.append("bone meal effect with", exprs[0], "particles"));
+
+		registerEffect(Effect.ELECTRIC_SPARK, "(electric|lightning[ rod]|copper) spark effect [(in|using|along) the (1:x|2:y|3:z) axis]",
+			(event, expressions, parseResult) -> (parseResult.mark == 0 ? null : Axis.values()[parseResult.mark - 1]),
+			(exprs, parseResult, builder) -> builder.append("electric spark effect")
+													.appendIf(parseResult.mark != 0, "along the", Axis.values()[parseResult.mark - 1], "axis"));
+
+		registerEffect(Effect.PARTICLES_SCULK_CHARGE, "sculk (charge|spread) effect [(with|using) data %integer%]",
+			(exprs, parseResult, builder) -> builder.append("sculk charge effect with data", exprs[0])); // data explanation here https://discord.com/channels/135877399391764480/836220422223036467/1211040434852208660
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataGameEffects.java]: is it possible to copy the relevant conversion in a comment? I feel like a discord link isn't super friendly

File: src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java [hunk 27]
```diff
@@ -0,0 +1,431 @@
...
+	@Override
+	public void load(SkriptAddon addon) {
+		registerClasses();
+		registerDataSerializers();
+		DataGameEffects.getGameEffectInfos();
+		DataParticles.getParticleInfos();
+
+		// load elements!
+		try {
+			Skript.getAddonInstance().loadClasses("org.skriptlang.skript.bukkit.particles", "elements");
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java]: use class loader api

File: src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java [hunk 28]
```diff
@@ -0,0 +1,431 @@
...
+		} catch (IOException e) {
+			throw new RuntimeException(e);
+		}
+	}
+
+	/**
+	 * Registers particle and game effect related classes.
+	 */
+	private static void registerClasses() {
+		// gane effects
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java]:
```suggestion
		// game effects
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java [hunk 29]
```diff
@@ -0,0 +1,431 @@
...
+					float power = fields.getAndRemovePrimitive("power", Float.class);
+					if (color == null)
+						throw new NotSerializableException("Color cannot be null for Spell");
+					return new Particle.Spell(color, power);
+				}
+			});
+		}
+
+		if (Skript.isRunningMinecraft(1, 21, 4)) {
+			Variables.yggdrasil.registerClassResolver(new NonInstantiableClassSerializer<>(Particle.Trail.class, "particle.trail") {
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java:372]: does this need to handle upgrading from 1.21.2/3?

File: src/main/resources/lang/default.lang [hunk 30]
```diff
@@ -1616,6 +1616,9 @@ entities:
 	animal:
 		name: animal¦s
 		pattern: animal[plural:s]
+	tameable:
+		name: tameable creature¦s
+		pattern: tameable creature[1¦s]
```
Comment (APickledWalrus) [inline src/main/resources/lang/default.lang]:
```suggestion
		pattern: tameable creature[plural:s]
```

File: src/main/resources/lang/default.lang [hunk 31]
```diff
@@ -2756,6 +2127,337 @@ transform reasons:
...
+	crafter_craft: crafter craft sound effect
+	crafter_fail: crafter fail sound effect
+	particles_egg_crack: egg crack effect
+	gust_dust: gust dust effect
+	trial_spawner_eject_item: trial spawner eject item effect
+	vault_eject_item: vault eject item effect
+	spawn_cobweb: spawn cobweb effect
+	sound_with_charge_shot: charge shot sound effect
+
+	 # these effects are deprecated in 1.19, they do nothing.
```
Comment (APickledWalrus) [inline src/main/resources/lang/default.lang:2242]: do they still need to be supported?

File: src/main/resources/lang/default.lang [hunk 32]
```diff
@@ -2756,6 +2127,337 @@ transform reasons:
...
+# -- Entity Effects --
+# all patterns should include the word 'effect' or 'animation'
+# 'effect' should be used for particles, 'sound effect' for sounds, 'animation' for model animations
+entity effect:
+	arrow_particles: tipped arrow particles effect
+	rabbit_jump: rabbit jump animation
+	reset_spawner_minecart_delay: reset spawner minecart delay effect
+
+	# death was superseded by entity_death 1.12.2
+	death: death animation
```
Comment (APickledWalrus) [inline src/main/resources/lang/default.lang:2290]: does this need to be an entry then?

File: src/main/resources/lang/default.lang [hunk 33]
```diff
@@ -2756,6 +2127,337 @@ transform reasons:
...
+	iron_golen_attack: iron golem attack animation
+	ravager_attack: ravager attack animation
+	ravager_roared: ravager roared effect
+	warden_attack: warden attack animation
+	zoglin_attack: zoglin attack animation
+	entity_attack: entity attack animation
+
+	# wolf effects superseded by taming effects 1.21
+	wolf_smoke: taming failed effect
+	wolf_hearts: taming succeeded effect
```
Comment (APickledWalrus) [inline src/main/resources/lang/default.lang:2307]: same here. do these need to be listed anymore?

File: src/main/resources/lang/default.lang [hunk 34]
```diff
@@ -3133,6 +2835,13 @@ types:
 	frogvariant: frog variant¦s @a
 	itemcomponent: item component¦s @an
 	equippablecomponent: equippable component¦s @an
+	nameable: nameable thing¦s @a
+	gameeffect: game effect¦s @a
+	entityeffect: entity effect¦s @a
```
Comment (APickledWalrus) [inline src/main/resources/lang/default.lang]:
```suggestion
	entityeffect: entity effect¦s @an
```

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
This look really good! Most of my comments are around formatting/code tweaks. The design itself looks fantastic.

File: src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataGameEffects.java (hunk 26 above)
Comment (sovdeeth) [reply src/main/java/org/skriptlang/skript/bukkit/particles/registration/DataGameEffects.java]: Yeah this was intended as a note to self, I'll write a proper one

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java (hunk 12 above)
Comment (sovdeeth) [reply src/main/java/org/skriptlang/skript/bukkit/particles/elements/effects/EffPlayEffect.java]: No, a radius of null is deliberately interpreted as an infinite radius

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithData.java (hunk 20 above)
Comment (sovdeeth) [reply src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithData.java:90]: yeah, I guess none of particle is not something you do intentionally

File: src/main/resources/lang/default.lang (hunk 31 above)
Comment (sovdeeth) [reply src/main/resources/lang/default.lang:2242]: They're just here to avoid the "missing lang entry" warning

File: src/main/resources/lang/default.lang (hunk 32 above)
Comment (sovdeeth) [reply src/main/resources/lang/default.lang:2290]: likewise about the lang entry warning

File: src/main/java/ch/njol/skript/Skript.java [hunk 35]
```diff
@@ -606,7 +607,8 @@ public void onEnable() {
 				new EntityModule(),
 				new DamageSourceModule(),
 				new ItemComponentModule(),
-				new PotionModule());
+				new PotionModule(),
+        new ParticleModule());
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/Skript.java]:
```suggestion
				new ParticleModule());
```

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprGameEffectWithData.java [hunk 36]
```diff
@@ -0,0 +1,106 @@
...
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
+import org.skriptlang.skript.addon.AddonModule.ModuleOrigin;
+import org.skriptlang.skript.bukkit.particles.GameEffect;
+import org.skriptlang.skript.bukkit.particles.registration.DataGameEffects;
+import org.skriptlang.skript.bukkit.particles.registration.EffectInfo;
+import org.skriptlang.skript.registration.SyntaxInfo;
+import org.skriptlang.skript.registration.SyntaxRegistry;
+
+import static org.skriptlang.skript.registration.DefaultSyntaxInfos.Expression.builder;
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprGameEffectWithData.java]: any reason for the import?

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java [hunk 37]
```diff
@@ -0,0 +1,86 @@
...
+		return switch (mode) {
+			case SET, ADD, REMOVE, RESET -> new Class[]{Number.class};
+			default -> null;
+		};
+	}
+
+	@Override
+	public void change(Event event, Object @Nullable [] delta, ChangeMode mode) {
+		ParticleEffect[] particleEffect = getExpr().getArray(event);
+		if (particleEffect == null)
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleCount.java]: shouldn't ever be null

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleSpeed.java [hunk 38]
```diff
@@ -0,0 +1,83 @@
...
+	* acts as a multiplier to the particle's offset if the particle count is 0.
+	
+	More detailed information on particle behavior can be found at \
+	<a href="https://docs.papermc.io/paper/dev/particles/#count-argument-behavior">Paper's particle documentation</a>.
+	""")
+@Example("set the speed of {_my-flame-particle} to 2")
+@Since("INSERT VERSION")
+public class ExprParticleSpeed extends SimplePropertyExpression<ParticleEffect, Number> {
+
+	public static void register(@NotNull SyntaxRegistry registry, @NotNull AddonModule.ModuleOrigin origin) {
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleSpeed.java]: just importing Origin should suffice

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithSpeed.java [hunk 39]
```diff
@@ -0,0 +1,83 @@
...
+	@Override
+	public Class<? extends ParticleEffect> getReturnType() {
+		return getExpr().getReturnType();
+	}
+
+	@Override
+	public String toString(@Nullable Event event, boolean debug) {
+		SyntaxStringBuilder ssb = new SyntaxStringBuilder(event, debug);
+		ssb.append(getExpr(), "with a speed value of", speed);
+		return ssb.toString();
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprParticleWithSpeed.java]: could be just an expression but idk if it matters much

File: src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java [hunk 40]
```diff
@@ -0,0 +1,443 @@
...
+ * Module for particle and game effect related classes and elements.
+ */
+public class ParticleModule implements AddonModule {
+
+	@Override
+	public void load(SkriptAddon addon) {
+		registerClasses();
+		registerDataSerializers();
+		DataGameEffects.getGameEffectInfos();
+		DataParticles.getParticleInfos();
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/bukkit/particles/ParticleModule.java:48]: I might register these (at least the classes) in the `init` method.

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
Just a few minor things. I think just using `Origin` (or directly importing ModuleOrigin) for the `register` methods should be okay.

File: src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprGameEffectWithData.java (hunk 36 above)
Comment (sovdeeth) [reply src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprGameEffectWithData.java]: it was ungainly

Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/bukkit/particles/elements/expressions/ExprGameEffectWithData.java]: I think `SyntaxInfo.Expression.builder` should work

**Review by APickledWalrus — APPROVED** [review]

**Review by UnderscoreTud — APPROVED** [review]

File: src/main/java/ch/njol/util/VectorMath.java (hunk 4 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/util/VectorMath.java:111]: idk tbh vectormath is being removed anyway

File: src/main/java/ch/njol/skript/expressions/ExprVelocity.java (hunk 1 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/expressions/ExprVelocity.java:30]: i will do type properties after 2.14 since they're not making it to full release in 2.14 regardless

Comment (sovdeeth) [reply src/main/java/ch/njol/skript/expressions/ExprVelocity.java:30]: actually screw it it's not hard to add, they can be part of 2.14 testing then

Comment (sovdeeth) [reply src/main/java/ch/njol/skript/expressions/ExprVelocity.java:30]: I won't be doing it for velocity in this pr since that's messing with existing behavior but I will do it for scale
