### PR TITLE
Function package rework and named function arguments

### LINKED ISSUE #7987: Add named function arguments
### Suggestion

Skript should add named function arguments, similar to languages like Kotlin.

Example:
```applescript
function x(a: int, b: text):
  return length of {_b} * {_a} 

on load:
  set {_f::1} to x(a: 1, b: "nice")
  set {_f::2} to x(b: "nice", a: 1)
  set {_f::3} to x(1, "nice") # same behaviour as old
```

### Why?

For functions with many parameters, it improves the readability of the arguments. Seeing `x(a: 1, b: "nice")` means you instantly know which values are passed to which parameters, instead of `x(1, "nice")`, where it is not explicitly mentioned.

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

### LINKED ISSUE #8040: Improve error messages for invalid function parameters
### Skript/Server Version

```markdown
2.12
```

### Bug Description

The error message for a function with bad parameters results in a very poor explanation:

Image

### Expected Behavior

The `function(types) doesn't exist` error message should be printed instead.

### Steps to Reproduce

```

using local variable type hints
command /test:
    permission: op
    trigger:
        set {_number} to true
        type_hint_argument_test({_number})

local function type_hint_argument_test(number: number):
    stop

```

### Errors or Screenshots

_No response_

### Other

This is due to the re-parsing of the arguments specifically as an expressionlist in SkriptParser#parseFunction, lines 1129-1141.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### LINKED ISSUE #8106: Function super types still broken for same literals
### Skript/Server Version

```markdown
2.12.0 (pulled from dev/patch as of posting this, even with the assumed function super type fixes)
MC 1.21.5
```

### Bug Description

Conflict in the function parameters between damage type and block data
```
function example(blockdata: block data):
	stop

on script load:
	example(lava)
```
```
[01:32:21 INFO]: Line 5: (test.sk)
[01:32:21 INFO]:     The function 'example(damagetype)' does not exist.
[01:32:21 INFO]:     Line: example(lava)
[01:32:21 INFO]:
```

### Expected Behavior

To properly reparse the literal to be the correct type.
You need to apply the same fixes I did for comparing same literals but for the function parameters https://github.com/SkriptLang/Skript/pull/5503

### Steps to Reproduce

run the script

### Errors or Screenshots

_No response_

### Other

_No response_

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

### PR DESCRIPTION
**Pull request by Efnilite**
### Problem

Skript should add named function arguments, similar to languages like Kotlin. This increases the clarity of which argument is passed.

Example:
```applescript
function x(a: int, b: text):
  return length of {_b} * {_a} 

on load:
  set {_f::1} to x(a: 1, b: "nice")
  set {_f::2} to x(b: "nice", a: 1)
  set {_f::3} to x(1, "nice") # same behaviour as old
```

Also, the function package code is a mess.

### Solution

**Named function arguments**

Named function arguments act as you would expect. They are always usable, except for when mixing named and unnamed arguments. To avoid assigning the incorrect value to a parameter, mixing named/unnamed is only allowed when the named arguments are in the same order as the parameters of the function. An example.

```applescript
# all good since these are exclusively named arguments
x(a: 1, b: "nice", c: 2)
x(b: "nice", a: 1, c: 2)

# still allowed as they follow the order of appearance of the parameters
x(a: 1, "nice", c: 2)
x(1, "nice", c: 2)

# not allowed
x(a: 1, c: 2, "nice")
x(c: 2, a: 1, "nice")
x(2, a: 1, "nice")
```

Lists are also supported.

```applescript
# allowed
x(xs: (1, 2, 3), 2, 3)
```

**Rework changes**

<details>
<summary>Function references</summary>

Function references have had a major rework. These changes are extensive and happen predominantly in `SkriptParser.` To try and improve organization, all function parsing code has been moved to the `FunctionParser` subclass. To accommodate these changes , `njol.FunctionReference` has been deprecated and has been replaced by `skript.FunctionReference`.

Function references are now determined inside the parser by using existing function signatures, which allows it to automatically select the correct function reference based on the argument types (fixing #8106). For every signature, it will attempt to parse the given arguments to the types belonging to the signature. If this is successful, it will continue with all other signatures. Then, if only one signature is valid, an exact match has been found. If there are multiple matches, an error will be printed.  

The integration with `SkriptParser` also removes the need to fetch the signature of functions at runtime, as these can be stored directly inside the reference, which improves performance and reduces complexity.

</details>

<details>
<summary>Function arguments</summary>

Since Skript doesn't support the format to achieve named function arguments, a new function reference argument parser has been written. On receiving the input string, this parser correctly separates the arguments into arguments, and also determines whether these arguments are named or not. An example output is as follows.

image

</details>

<details>
<summary>Function execution</summary>

Since position is no longer relevant, all function execution is now handled via the abstract `Function#execute(FunctionEvent, FunctionArguments)` method. Instead of a 2D object array, functions now have access to `FunctionArguments`, which is essentially a glorified map. This map holds all the passed function arguments by name. The old execution method has been deprecated.

</details>

<details>
<summary>Parameters</summary>

`njol.Parameter` has been deprecated and has been replaced by the following classes, both of which implement the new `skript.Parameter` interface.

- `skript.ScriptParameter`: for parameters that are parsed from scripts. This class has an additional default value attribute, as well as the attributes provided by `skript.Parameter`. This default value is used in e.g. `x: int = 3`;
- `skript.DefaultParameter`: for parameters for `DefaultFunction`s. This class has no additional attributes other than those provided by `skript.Parameter`;

These new parameters use classes instead of classinfos for their types. When a parameter accepts multiple values, its type is e.g. `Integer[]` or `String[]`. When it accepts a single value, it is e.g. `Integer` or `String`. Parameters also have a set of modifiers, which dictate the behaviour of the parameter. The `Modifier` interface details the two currently used parameters: 
- `OPTIONAL`: for function parameters that are optional,
- `KEYED`: for function parameters that accept keyed values.

Furthermore, parameters are now stored as a `LinkedHashMap`, which encourages the intended use for accessing function arguments. Using names and accessing the first argument are easy, while getting a parameter by its position is now more involved. Due to Skript still supporting Java 17, `SequencedMap` cannot be used as an abstraction of `LinkedHashMap` yet.

</details>

<details>
<summary>Parameter parsing</summary>

Script parameter parsing has been relocated from the (soon-to-be-extinct) `Functions` class. Parsing a single parameter has been moved to `ScriptParameter`, and parsing the entire signature of a script function has been moved to the new subclass `StructFunction.FunctionParser`.

</details>

<details>
<summary>Adds -> as a function return prefix</summary>

Looks nicer than the others :)

```applescript
function add(x: int, y: int) -> int:
  return {_x} + {_y}

function add(x: int, y: int) :: int:
  return {_x} + {_y}

function add(x: int, y: int) returns int:
  return {_x} + {_y}
```

</details>

### Testing Completed
- Existing tests
- Added tests for literal parsing
- Added tests for providing too few or too many arguments
- Added tests for named function arguments
- Added JUnit tests for the function reference argument parser

### Supporting Information

<details>
<summary>Breaking changes</summary>

- `SkriptParser#parseFunction(Class[])` has been entirely replaced with `SkriptParser#parseFunctionReference()` 
- `Function#execute(FunctionEvent, FunctionArguments)` must be implemented by anyone extending `Function` directly
- `Signature#getParameters()` and `Signature#getParameter(int)` have had their return type changed to `skript.Parameter` instead of `njol.Parameter`
- `ExprFunctionCall` and `EffFunctionCall`'s constructors have changed from accepting `njol.FunctionReference` to now accepting `skript.FunctionReference`.
- Due to a bug in `JavaFunction#execute`, the implementation of `location` has been updated to avoid the world being null. (as described in #7969)
- All package-protected fields in `njol.Parameter` and `njol.Signature` have been changed to be private, with methods being added for access.
- Removed `ScriptFunction#setReturnValue` (deprecated since 2.9)
- Removed `SkriptParser#wildcard` (deprecated since 2.8)
- Removed `SkriptParser#listSplitPattern` (deprecated since 2.7)

</details>

---
**Completes:** #7987, #8106, #4638 
**Related:** none

### CODE REVIEW

File: src/main/java/ch/njol/skript/lang/FunctionArgumentParser.java [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+
+	private char c;
+	private boolean nameFound = false;
+	private final StringBuilder namePart = new StringBuilder();
+	private final StringBuilder exprPart = new StringBuilder();
+
+	private boolean inString = false;
+	private int nesting = 0;
+
+	private void parse() {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionArgumentParser.java]: these functions need some comprehensive docs to describe their behavior and goals

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 2]
```diff
@@ -0,0 +1,407 @@
...
+import java.util.regex.Pattern;
+import java.util.stream.Collectors;
+
+/**
+ * A class containing the methods to parse an expression to a {@link FunctionReference}.
+ *
+ * @param context The context of parsing.
+ * @param flags   The active parsing flags.
+ */
+record FunctionParser(ParseContext context, int flags) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java]: i'd prefer these new classes to go in skriptlang instead of njol

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 3]
```diff
@@ -0,0 +1,407 @@
...
+
+		String namespace;
+		if (ParserInstance.get().isActive()) {
+			namespace = ParserInstance.get().getCurrentScript().getConfig().getFileName();
+		} else {
+			namespace = null;
+		}
+
+		// try to find a matching signature to get which types to parse args with
+		Set<Signature<?>> options = FunctionRegistry.getRegistry().getSignatures(namespace, name);
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java:123]: can't we do this prior to arg parsing to save some work?

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 4]
```diff
@@ -0,0 +1,407 @@
...
+		if (options.isEmpty()) {
+			doesNotExist(name, arguments);
+			log.printError();
+			return null;
+		}
+
+		// all signatures that have no single list params
+		Set<Signature<?>> exacts = new HashSet<>();
+		// all signatures with only single list params
+		Set<Signature<?>> lists = new HashSet<>();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java]: an example in the comments would be nice

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 5]
```diff
@@ -0,0 +1,407 @@
...
+		// last, find single list functions
+		Set<FunctionReference<T>> listReferences = getListReferences(namespace, name, lists, arguments, log);
+		if (listReferences == null) { // a list error, so quit parsing
+			return null;
+		}
+
+		// if we found an exact one, return first to avoid conflict with list references
+		if (exactReferences.size() == 1) {
+			return exactReferences.stream().findAny().orElse(null);
+		}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java:158]: put this above list reference so we can exit early

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 6]
```diff
@@ -0,0 +1,407 @@
...
+	 * @return All possible exact {@link FunctionReference FunctionReferences}.
+	 */
+	private <T> Set<FunctionReference<T>> getExactReferences(
+		String namespace, String name,
+		Set<Signature<?>> signatures, Argument<String>[] arguments,
+		ParseLogHandler log
+	) {
+		Set<FunctionReference<T>> exactReferences = new HashSet<>();
+
+		exact:
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java]: a better label would be nice

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 7]
```diff
@@ -0,0 +1,407 @@
...
+		Set<FunctionReference<T>> references = new HashSet<>();
+
+		for (Signature<?> signature : signatures) {
+			Parameter<?> parameter = signature.parameters().firstEntry().getValue();
+
+			Class<?> target = parameter.type().componentType();
+			Class<?>[] targets = new Class<?>[]{target};
+
+			// join all args to a single arg
+			String joined = Arrays.stream(arguments).map(Argument::value)
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java]: does this verify all arguments are not named/only the first is named correctly? or would it try to treat `(a: b, c: d, e)` as `(a: (b,d,e))`?

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 8]
```diff
@@ -0,0 +1,407 @@
...
+				}
+
+				references.add(reference);
+			}
+		}
+
+		return references;
+	}
+
+	private <T> void ambiguousError(String name, Set<FunctionReference<T>> references) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java:368]: docs

File: src/main/java/ch/njol/skript/lang/FunctionParser.java [hunk 9]
```diff
@@ -0,0 +1,407 @@
...
+			//noinspection unchecked
+			Expression<?> expression = parser.parseExpression(targets[i]);
+
+			if (expression == null) {
+				return new FunctionArgumentParseResult(FunctionArgumentParseResultType.PARSE_FAIL, null);
+			}
+
+			if (expression instanceof ExpressionList<?> list && !list.getAnd()) {
+				Skript.error("Function arguments must be separated by commas and optionally an 'and', but not an 'or'."
+					+ " Put the 'or' into a second set of parentheses if you want to make it a single parameter, e.g. 'give(player, (sword or axe))'");
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/FunctionParser.java]: lang node

File: src/test/skript/tests/misc/function overloading.sk
Comment (sovdeeth) [inline src/test/skript/tests/misc/function overloading.sk:1]: I'd like to see more tests of the various functions reported as having issues, like bento's.

**Review by sovdeeth — CHANGES_REQUESTED** [review]
much better than using the expressionlist parser

File: src/main/java/ch/njol/skript/lang/FunctionParser.java (hunk 3 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/FunctionParser.java:123]: im not sure i understand what work would be saved by moving this prior to arg parsing. args are parsed as strings. their actual return type is only found when trying to match a signature in the `options` set.

File: src/main/java/ch/njol/skript/lang/FunctionParser.java (hunk 2 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/FunctionParser.java]: right now they're package-private to allow only SkriptParser to access them. is making them public okay?

File: src/main/java/ch/njol/skript/lang/FunctionParser.java (hunk 3 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/lang/FunctionParser.java:123]: All the work done in FunctionArgumentParser#parse()

File: src/main/java/ch/njol/skript/lang/FunctionParser.java (hunk 2 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/lang/FunctionParser.java]: I think they should be public anyway tbh

File: src/main/java/ch/njol/skript/doc/Documentation.java [hunk 10]
```diff
@@ -383,8 +378,8 @@ private static void insertClass(final PrintWriter pw, final ClassInfo<?> info) {
 
 	private static void insertFunction(final PrintWriter pw, final JavaFunction<?> func) {
 		final StringBuilder params = new StringBuilder();
```
Comment (Absolutionism) [inline src/main/java/ch/njol/skript/doc/Documentation.java]:
```suggestion
	private static void insertFunction(PrintWriter pw, JavaFunction<?> func) {
		StringBuilder params = new StringBuilder();
```

File: src/main/java/ch/njol/skript/lang/function/Parameter.java [hunk 11]
```diff
@@ -200,4 +278,24 @@ public String toString(boolean debug) {
...
+			return (Class<T>) type.getC().arrayType();
+		}
+	}
+
+	@Override
+	public @Unmodifiable @NotNull Set<Modifier> modifiers() {
+		return Collections.unmodifiableSet(modifiers);
+	}
+
+}
```
Comment (Absolutionism) [inline src/main/java/ch/njol/skript/lang/function/Parameter.java]:
```suggestion
}

```

File: src/main/java/org/skriptlang/skript/lang/function/FunctionArgumentParser.java [hunk 12]
```diff
@@ -0,0 +1,239 @@
...
+	 * Returns all arguments.
+	 *
+	 * @return All arguments.
+	 */
+	public Argument<String>[] getArguments() {
+		//noinspection unchecked
+		return (Argument<String>[]) arguments.toArray(new Argument[0]);
+	}
+
+}
```
Comment (Absolutionism) [inline src/main/java/org/skriptlang/skript/lang/function/FunctionArgumentParser.java]:
```suggestion
}

```

File: src/main/java/org/skriptlang/skript/lang/function/FunctionReference.java [hunk 13]
```diff
@@ -0,0 +1,351 @@
...
+		 */
+		NAMED,
+
+		/**
+		 * Whether this argument does not have a name.
+		 */
+		UNNAMED
+	}
+
+}
```
Comment (Absolutionism) [inline src/main/java/org/skriptlang/skript/lang/function/FunctionReference.java]:
```suggestion
}

```

File: src/main/java/org/skriptlang/skript/lang/function/ScriptParameter.java [hunk 14]
```diff
@@ -0,0 +1,89 @@
...
+		if (!Variable.isValidVariableName(name, true, false)) {
+			Skript.error("A parameter's name must be a valid variable name.");
+			return null;
+		}
+
+		Expression<?> d = null;
+		if (def != null) {
+			Class<?> target;
+			if (type.isArray()) {
+                target = type.componentType();
```
Comment (Absolutionism) [inline src/main/java/org/skriptlang/skript/lang/function/ScriptParameter.java]:
```suggestion
				target = type.componentType();
```

File: src/test/java/org/skriptlang/skript/lang/function/FunctionArgumentParserTest.java [hunk 15]
```diff
@@ -0,0 +1,59 @@
...
+	}
+
+	@Test
+	public void testStringEscape() {
+		Argument<String>[] arguments = new FunctionArgumentParser("1: \"hello \"\" %{x,y::%player's car, or not!%::*} there\"\"\"").getArguments();
+
+		assertEquals(new Argument<>(ArgumentType.NAMED, "1", "\"hello \"\" %{x,y::%player's car, or not!%::*} there\"\"\""), arguments[0]);
+	}
+
+}
```
Comment (Absolutionism) [inline src/test/java/org/skriptlang/skript/lang/function/FunctionArgumentParserTest.java]:
```suggestion
}

```

File: src/main/java/org/skriptlang/skript/lang/function/FunctionArguments.java [hunk 16]
```diff
@@ -0,0 +1,124 @@
...
+
+import java.util.Collections;
+import java.util.Map;
+import java.util.Set;
+import java.util.function.Supplier;
+
+/**
+ * A class containing all arguments in a function call.
+ */
+public final class FunctionArguments {
```
Comment (Absolutionism) [inline src/main/java/org/skriptlang/skript/lang/function/FunctionArguments.java]: Entire class infested with spaces

File: src/main/java/org/skriptlang/skript/lang/function/FunctionReference.java [hunk 17]
```diff
@@ -0,0 +1,351 @@
...
+
+	private KeyedValue<?>[] evaluateKeyed(Expression<?> expression, Event event) {
+		if (expression instanceof ExpressionList<?> list) {
+			return evaluateSingleListParameter(list.getExpressions(), event);
+		}
+		return evaluateParameter(expression, event);
+	}
+
+	private KeyedValue<?>[] evaluateSingleListParameter(Expression<?>[] parameters, Event event) {
+        List<Object> values = new ArrayList<>();
```
Comment (Absolutionism) [inline src/main/java/org/skriptlang/skript/lang/function/FunctionReference.java]:
```suggestion
		List<Object> values = new ArrayList<>();
```

File: src/main/java/org/skriptlang/skript/lang/function/FunctionReference.java [hunk 18]
```diff
@@ -0,0 +1,351 @@
...
+	}
+
+	private KeyedValue<?>[] evaluateParameter(Expression<?> parameter, Event event) {
+		Object[] values = parameter.getArray(event);
+
+		// Don't allow mutating across function boundary; same hack is applied to variables
+		for (int i = 0; i < values.length; i++)
+			values[i] = Classes.clone(values[i]);
+
+        String[] keys = KeyProviderExpression.areKeysRecommended(parameter)
```
Comment (Absolutionism) [inline src/main/java/org/skriptlang/skript/lang/function/FunctionReference.java]:
```suggestion
		String[] keys = KeyProviderExpression.areKeysRecommended(parameter)
```

**Review by Absolutionism — DISMISSED** [review]

File: src/main/java/ch/njol/skript/lang/SkriptParser.java [hunk 19]
```diff
@@ -1145,98 +1129,14 @@ private SkriptParser suppressMissingAndOrWarnings() {
...
 	/**
-	 * @param types The required return type or null if it is not used (e.g. when calling a void function)
-	 * @return The parsed function, or null if the given expression is not a function call or is an invalid function call (check for an error to differentiate these two)
+	 * Attempts to parse {@link SkriptParser#expr} as a function reference.
+	 *
+	 * @param <T> The return type of the function.
+	 * @return A {@link FunctionReference} if a function is found, or {@code null} if none is found.
 	 */
-	@SuppressWarnings("unchecked")
-	public <T> @Nullable FunctionReference<T> parseFunction(@Nullable Class<? extends T>... types) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/SkriptParser.java:1195]: back compat? deprecation?

File: src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java [hunk 20]
```diff
@@ -174,12 +175,20 @@ else if (parameters.length < signature.getMinParameters())
 
 		// Check parameter types
 		for (int i = 0; i < parameters.length; i++) {
-			Parameter<?> parameter = signature.parameters[varArgs ? 0 : i];
+			Parameter<?> parameter = signature.parameters().values().toArray(new Parameter<?>[0])[varArgs ? 0 : i];
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java]: given the existing need to get parameters by order, I think you should provide some help for that in Signature. Perhaps consider a different data structure for parameters or keeping a separate ordered list of params by name as a lookup.

File: src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java [hunk 21]
```diff
@@ -13,31 +11,37 @@
...
-	public ExprFunctionCall(FunctionReference<?> function, Class<? extends T>[] expectedReturnTypes) {
-		this.function = function;
-		Class<?> functionReturnType = function.getReturnType();
-		assert  functionReturnType != null;
-		if (CollectionUtils.containsSuperclass(expectedReturnTypes, functionReturnType)) {
+	public ExprFunctionCall(FunctionReference<?> reference, Class<? extends T>[] expectedReturnTypes) {
+		this.reference = reference;
+
+		Class<?> returnType;
+		Class<?> functionReturnType = reference.signature().returnType();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java:38]: might want to take the chance to future proof this with a possible return types-like system. supports future possible improvements like return type deduction or functions that return string or number but not player.

Optional.

File: src/main/java/ch/njol/skript/lang/function/Function.java [hunk 22]
```diff
@@ -147,8 +167,18 @@ public boolean isSingle() {
 	 * you need to manually handle default values.
 	 * @return Function return value(s).
 	 */
+	@Deprecated(since = "INSERT VERSION", forRemoval = true)
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Function.java:181]: note what to use instead

File: src/main/java/ch/njol/skript/lang/function/FunctionReference.java [hunk 23]
```diff
@@ -159,7 +164,7 @@ public boolean validateFunction(boolean first) {
 		// Validate that return types are what caller expects they are
 		Class<? extends T>[] returnTypes = this.returnTypes;
 		if (returnTypes != null) {
-			ClassInfo<?> rt = sign.returnType;
+			Class<?> rt = sign.returnType();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionReference.java]: needs better name

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 24]
```diff
@@ -43,8 +55,30 @@ public class StructFunction extends Structure {
...
+	 * The arguments that can be passed to this function.
+	 * </p>
+	 * <p>
+	 * <b>Returns</b>
+	 * The type that this function returns, if any.
+	 * Acceptable return type prefixes are as follows.
+	 * <ul>
+	 *     <li>{@code ->}</li>
+	 *     <li>{@code ::}</li>
+	 *     <li>{@code returns}</li>
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]:
```suggestion
	 *     <li>{@code returns}</li>
	 *     <li>{@code ->}</li>
	 *     <li>{@code ::}</li>
```
returns should be the option people first encounter, as it's the most self-explanatory (and honestly i think it should be the only option, but the symbols lobby is too powerful)

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 25]
```diff
@@ -134,4 +168,128 @@ public String toString(@Nullable Event event, boolean debug) {
...
+				} else {
+					returnType = returnClass.getC();
+				}
+			}
+
+			return new Signature<>(script, name, parameters, local, returnType, null);
+		}
+
+		private final static Pattern SCRIPT_PARAMETER_PATTERN =
+			Pattern.compile("^\\s*(?<name>[^:(){}\",]+?)\\s*:\\s*(?<type>[a-zA-Z ]+?)\\s*(?:\\s*=\\s*(?<def>.+))?\\s*$");
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]: comment explaining this would be great
otherwise it'll be the loch ness monster in 2 years

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 26]
```diff
@@ -134,4 +168,128 @@ public String toString(@Nullable Event event, boolean debug) {
...
+				if (i == -1) {
+					Skript.error("Invalid text/variables/parentheses in the arguments of this function");
+					return null;
+				}
+
+				if (i == args.length() || args.charAt(i) == ',') {
+					String arg = args.substring(j, i);
+
+					if (args.isEmpty()) // Zero-argument function
+						break;
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]: this should probably be a few lines higher up for clarity, rather than within the length/comma if

**Review by sovdeeth — CHANGES_REQUESTED** [review]
overall seems good
re-request once it's out of draft

**Comment by sovdeeth** [comment]
Why have the builds been failing for months? Do you need assistance?

File: src/test/skript/tests/misc/named function arguments.sk
Comment (APickledWalrus) [inline src/test/skript/tests/misc/named function arguments.sk:1]: This should just be part of StructFunction test IMO

File: src/main/resources/lang/english.lang [hunk 27]
```diff
@@ -231,3 +231,10 @@ io exceptions:
 misc:
 	namespacedutils:
 		format: A namespaced key can be formatted as 'namespace:id' or 'id'. It can only contain one ':' to separate the namespace and the id. Only alphanumeric characters, periods, underscores, and dashes can be used.
+
+# -- Functions --
+functions:
```
Comment (APickledWalrus) [inline src/main/resources/lang/english.lang:236]: I would keep single quotes around function/parameter names. It improves readability.

File: src/main/java/ch/njol/skript/util/Utils.java [hunk 28]
```diff
@@ -273,10 +274,60 @@ public static NonNullPair<String, Boolean> getEnglishPlural(String word) {
 		return new NonNullPair<>(word, false);
 	}
 
+	public record PluralResult(String updated, boolean plural) {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/util/Utils.java:261]: needs docs

File: src/main/java/ch/njol/skript/util/Utils.java [hunk 29]
```diff
@@ -243,9 +244,9 @@ public static File getFile(Plugin plugin) {
 	}
 
 	/**
-	 * @param word trimmed string
-	 * @return Pair of singular string + boolean whether it was plural
+	 * @deprecated Use {@link #isPlural(String)} instead.
 	 */
+	@Deprecated(forRemoval = true, since = "INSERT VERSION")
 	public static NonNullPair<String, Boolean> getEnglishPlural(String word) {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/util/Utils.java:250]: This should just call the new method and convert the result into a NonNullPair.

File: src/main/java/org/skriptlang/skript/common/function/Parameter.java [hunk 30]
```diff
@@ -11,6 +12,7 @@
  *
  * @param <T> The type of the function parameter.
  */
+@NonExtendable
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/Parameter.java:24]: Can this just be a sealed interface?

File: src/main/java/org/skriptlang/skript/common/function/Signature.java [hunk 31]
```diff
@@ -13,6 +19,32 @@
...
+
+	/**
+	 * @return The type of this parameter.
+	 */
+	Class<T> returnType();
+
+	/**
+	 * @return An unmodifiable view of all the parameters that this signature has.
+	 */
+	@Unmodifiable @NotNull SequencedMap<String, Parameter<?>> parameters();
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/Signature.java]: Should use UnmodifiableView annotation instead if docs are correct

File: src/main/java/org/skriptlang/skript/common/function/Signature.java [hunk 32]
```diff
@@ -13,6 +19,32 @@
 @NonExtendable
 @Internal
 @Experimental
-public interface Signature<T> {
+public interface Signature<T> extends Documentable {
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/Signature.java]: I would not force Documentable here. It should be optional.

File: src/main/java/org/skriptlang/skript/common/function/Signature.java (hunk 31 above)
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/Signature.java]: I'm not sure I fully understand why this needs to be a map. Don't parameters store their names?

Is it also critical that it be sequenced? If we can reference function parameters by name, does ordering *really* matter?

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
A couple early thoughts. Tests are still failing :(

File: src/main/java/org/skriptlang/skript/common/function/Parameter.java (hunk 30 above)
Comment (Efnilite) [reply src/main/java/org/skriptlang/skript/common/function/Parameter.java:24]: no because the old parameter class is outside of the package

File: src/main/java/org/skriptlang/skript/common/function/Signature.java (hunk 31 above)
Comment (Efnilite) [reply src/main/java/org/skriptlang/skript/common/function/Signature.java]: Parameters do store their names, but making this a map allows for easy lookup of parameters by name, something which happens often. This can of course be replaced with any sequenced non-map collection, but that would require having to loop through all parameters to get a parameter by name. This can be added as a helper method, but using a map here is probably faster (and easier).

As for it being sequenced, Signature needs to contain a method to get the order of the parameters, as function calls like `x(1, 2, 3)` should still be able to match arguments to parameters without having the arguments be named.

File: src/main/java/ch/njol/skript/lang/SkriptParser.java [hunk 33]
```diff
@@ -1157,13 +1141,27 @@ private record OrderedExprInfo(ExprInfo[] infos) { }
...
+	 *
+	 * @param <T> The return type of the function.
+	 * @return A {@link FunctionReference} if a function is found, or {@code null} if none is found.
+	 */
+	public <T> org.skriptlang.skript.common.function.FunctionReference<T> parseFunctionReference() {
+		if (context != ParseContext.DEFAULT && context != ParseContext.EVENT) {
+			return null;
+		}
+
+		return new FunctionReferenceParser(context, flags).parseFunctionReference(expr);
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/SkriptParser.java]: inverting this condition would make it easier to read

File: src/main/java/ch/njol/skript/lang/SkriptParser.java [hunk 34]
```diff
@@ -1157,13 +1141,27 @@ private record OrderedExprInfo(ExprInfo[] infos) { }
...
 	private final static Pattern FUNCTION_CALL_PATTERN = Pattern.compile("(" + Functions.functionNamePattern + ")\\((.*)\\)");
 
 	/**
-	 * @param types The required return type or null if it is not used (e.g. when calling a void function)
-	 * @return The parsed function, or null if the given expression is not a function call or is an invalid function call (check for an error to differentiate these two)
+	 * @deprecated Use {{@link #parseFunctionReference()}} instead.
 	 */
-	@SuppressWarnings("unchecked")
+	@Deprecated(forRemoval = true, since = "INSERT VERSION")
 	public <T> @Nullable FunctionReference<T> parseFunction(@Nullable Class<? extends T>... types) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/SkriptParser.java:1197]: shouldn't this just call parseFunctionReference internally so we don't have two possible paths? or is that not feasible for some reason?

File: src/main/java/ch/njol/skript/lang/SkriptParser.java [hunk 35]
```diff
@@ -1297,6 +1294,10 @@ record SignatureData(ClassInfo<?> classInfo, boolean plural) { }
 		}
 	}
 
+	/**
+	 * @deprecated Use {@link #parseFunctionReference()} instead.
+	 */
+	@Deprecated(forRemoval = true, since = "INSERT VERSION")
 	private Expression<?> @Nullable [] getFunctionArguments(Supplier<Expression<?>> parsing, String args) {
 		if (args.isEmpty()) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/SkriptParser.java]: this one's private so you can just remove it

File: src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java [hunk 36]
```diff
@@ -162,7 +163,7 @@ public String toString() {
 		this.checkedInputs.put(input, null); // failure case
 		if (signature == null)
 			return null;
-		boolean varArgs = signature.getMaxParameters() == 1 && !signature.getParameter(0).single;
+		boolean varArgs = signature.getMaxParameters() == 1 && !signature.parameters().firstEntry().getValue().single();
 		Expression<?>[] parameters = input.parameters();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java]: can you rename this to be more clear about when the input params are being used vs when the signature params are used?

File: src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java [hunk 37]
```diff
@@ -13,31 +11,38 @@
...
-	private final FunctionReference<?> function;
+	private final FunctionReference<?> reference;
 	private final Class<? extends T>[] returnTypes;
 	private final Class<T> returnType;
 	private final Map<Event, String[]> cache = Collections.synchronizedMap(new WeakHashMap<>());
 
-	public ExprFunctionCall(FunctionReference<T> function) {
-		this(function, function.returnTypes);
-	}
-
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java:31]: this was public, should probably deprecate it

File: src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java [hunk 38]
```diff
@@ -90,15 +104,23 @@ public boolean areKeysRecommended() {
...
-			return new ExprFunctionCall<>(function, to);
+
+		Class<?> returns = reference.signature().returnType();
+		Class<?> converterType;
+		if (returns != null && returns.isArray()) {
+			converterType = returns.componentType();
+		} else {
+			converterType = returns;
+		}
+
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java:108]: this seems to be a common pattern, probably worth adding a helper/util method somewhere for it

File: src/main/java/ch/njol/skript/lang/function/FunctionReference.java [hunk 39]
```diff
@@ -160,8 +166,8 @@ public boolean validateFunction(boolean first) {
 		// Validate that return types are what caller expects they are
 		Class<? extends T>[] returnTypes = this.returnTypes;
 		if (returnTypes != null) {
-			ClassInfo<?> rt = sign.returnType;
-			if (rt == null) {
+			Class<?> returnType = sign.returnType();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionReference.java]: need better name to differentiate between expected from caller and signature candidate type

File: src/main/java/ch/njol/skript/lang/function/FunctionReference.java [hunk 40]
```diff
@@ -192,7 +199,7 @@ public boolean validateFunction(boolean first) {
 		}
 
 		// Validate parameter count
-		singleListParam = sign.getMaxParameters() == 1 && !sign.getParameter(0).single;
+		singleListParam = sign.getMaxParameters() == 1 && !sign.parameters().entrySet().iterator().next().getValue().single();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionReference.java]: maybe a helper method? getFirstParam or something?
In general the parameters() method seems to not be very convenient and it's always getting sent to an array or 5 stacked calls or whatever. Perhaps a different choice of data structure would help, or a wrapper around the map that provides helper methods like this

File: src/main/java/ch/njol/skript/lang/function/FunctionReference.java [hunk 41]
```diff
@@ -262,15 +276,21 @@ public boolean validateFunction(boolean first) {
...
 				log.printLog();
 			}
 		}
 
 		//noinspection unchecked
 		signature = (Signature<? extends T>) sign;
-		sign.calls.add(this);
+
+		//noinspection unchecked
+		Argument<Expression<?>>[] stream = (Argument<Expression<?>>[]) Arrays.stream(parameters)
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionReference.java]: this isn't a stream, why call it stream?

File: src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java [hunk 42]
```diff
@@ -40,7 +42,7 @@ public static FunctionRegistry getRegistry() {
 	 * The pattern for a valid function name.
 	 * Functions must start with a letter or underscore and can only contain letters, numbers, and underscores.
 	 */
-	final static String FUNCTION_NAME_PATTERN = "[\\p{IsAlphabetic}_][\\p{IsAlphabetic}\\d_]*";
+	final static Pattern FUNCTION_NAME_PATTERN = Pattern.compile("[A-z_][A-z_0-9]*");
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java]: please stick with IsAlphabetic, it allows non-ascii characters like accented letters or chars from other langauges

A-z is also not equal to A-Za-z, it includes characters like ], [, and ` in between (see ascii table)

File: src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java [hunk 43]
```diff
@@ -709,22 +712,17 @@ static FunctionIdentifier of(@NotNull String name, boolean local, @NotNull Class
...
 
-			Parameter<?>[] signatureParams = signature.parameters;
+			Parameter<?>[] signatureParams = signature.parameters().values().toArray(new Parameter<?>[0]);
 			Class<?>[] parameters = new Class[signatureParams.length];
 
 			int optionalArgs = 0;
 			for (int i = 0; i < signatureParams.length; i++) {
 				Parameter<?> param = signatureParams[i];
-				if (param.isOptional()) {
+				if (param.modifiers().contains(Modifier.OPTIONAL)) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java]: hasModifier?

File: src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java [hunk 44]
```diff
@@ -733,7 +731,7 @@ static FunctionIdentifier of(@NotNull Signature<?> signature) {
 
 		@Override
 		public int hashCode() {
-			return Objects.hash(name, local, Arrays.hashCode(args));
+			return Objects.hash(name, Arrays.hashCode(args));
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java:722]: why remove local here? if it's for the get local/global signatures I'm a bit uncertain about using hashcode for that, and i'm pretty sure it wouldn't work without also ensuring global/local isn't considered in equals(), too. Open to arguments though

File: src/main/java/ch/njol/skript/lang/function/Functions.java [hunk 45]
```diff
@@ -218,9 +194,9 @@ public static JavaFunction<?> registerFunction(JavaFunction<?> function) {
 			} else {
 				error.append("Function ");
 			}
-			error.append("'%s' with the same argument types already exists".formatted(signature.getName()));
-			if (existing.retrieved().script != null) {
-				error.append(" in script '%s'.".formatted(existing.retrieved().script));
+			error.append("%s with the same argument types already exists".formatted(signature.getName()));
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Functions.java]: i'd prefer keeping the ''

File: src/main/java/ch/njol/skript/lang/function/JavaFunction.java [hunk 46]
```diff
@@ -46,6 +47,45 @@ public JavaFunction(String name, Parameter<?>[] parameters, ClassInfo<T> returnT
 	@Override
 	public abstract T @Nullable [] execute(FunctionEvent<?> event, Object[][] params);
 
+	@Override
+	public final T execute(@NotNull FunctionEvent<?> event, @NotNull FunctionArguments arguments) {
+		List<org.skriptlang.skript.common.function.Parameter<?>> parameters = getSignature().parameters().values().stream().toList();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/JavaFunction.java]: does this need the full qualified name

File: src/main/java/ch/njol/skript/lang/function/JavaFunction.java [hunk 47]
```diff
@@ -46,6 +47,45 @@ public JavaFunction(String name, Parameter<?>[] parameters, ClassInfo<T> returnT
...
+					return null;
+				}
+
+				if (parameter.single()) {
+					params[i] = new Object[] { defaultExpression.getSingle(event) };
+				} else {
+					params[i] = defaultExpression.getArray(event);
+				}
+			} else {
+				params[i] = new Object[] { object };
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/JavaFunction.java:79]: some basic comments would be nice

File: src/main/java/ch/njol/skript/lang/function/Parameter.java [hunk 48]
```diff
@@ -291,12 +299,21 @@ public String toString(boolean debug) {
...
 
 	@Override
 	public @Unmodifiable @NotNull Set<Modifier> modifiers() {
 		return Collections.unmodifiableSet(modifiers);
 	}
 
+	@Override
+	public boolean single() {
+		return single;
+	}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Parameter.java:328]:
```suggestion
	}

```

File: src/main/java/ch/njol/skript/lang/function/Signature.java [hunk 49]
```diff
@@ -55,163 +59,215 @@ public class Signature<T> implements org.skriptlang.skript.common.function.Signa
...
+	 * Converts a {@link org.skriptlang.skript.common.function.Parameter} to a {@link Parameter}.
+	 * @param parameter The parameter to use to convert.
+	 * @return The converted parameter.
 	 */
-	private static <T> ClassInfo<T> getClassInfo(Class<T> cls) {
-		ClassInfo<T> classInfo;
-		if (cls.isArray()) {
-			//noinspection unchecked
-			classInfo = (ClassInfo<T>) Classes.getExactClassInfo(cls.componentType());
+	private static Parameter<?> toParameter(org.skriptlang.skript.common.function.Parameter<?> parameter) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Signature.java]: toOldParameter?

File: src/main/java/ch/njol/skript/lang/function/Signature.java [hunk 50]
```diff
@@ -55,163 +59,215 @@ public class Signature<T> implements org.skriptlang.skript.common.function.Signa
...
 
-	public String getName() {
-		return name;
+	@Override
+	public Class<T> returnType() {
+		if (returns == null) {
+			return null;
+		}
+		//noinspection unchecked
+		return (Class<T>) returns;
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Signature.java]: is the null check necessary?

File: src/main/java/ch/njol/skript/lang/function/Signature.java [hunk 51]
```diff
@@ -55,163 +59,215 @@ public class Signature<T> implements org.skriptlang.skript.common.function.Signa
...
 	}
 
 	/**
-	 * @deprecated Unused and unsafe.
+	 * @deprecated Unused.
 	 */
 	@Deprecated(forRemoval = true, since = "2.13")
 	public String getOriginClassPath() {
-		return originClassPath;
+		return "";
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Signature.java]: can't change this yet

File: src/main/java/ch/njol/skript/lang/function/Signature.java [hunk 52]
```diff
@@ -232,21 +288,47 @@ public String toString(boolean includeReturnType, boolean debug) {
...
+
+	@Override
+	public @Unmodifiable @NotNull List<String> keywords() {
+		return List.of();
+	}
+
+	@Override
+	public @Unmodifiable @NotNull List<String> requires() {
+		return List.of();
+	}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Signature.java]: what's going on here?

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 53]
```diff
@@ -134,4 +169,139 @@ public String toString(@Nullable Event event, boolean debug) {
...
 
+	public static class FunctionParser {
+
+		/**
+		 * Parses the signature from the given arguments.
+		 *
+		 * @param script  Script file name (<b>might</b> be used for some checks).
+		 * @param name    The name of the function.
+		 * @param args    The parameters of the function.
+		 * @param returns The return type of the function
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]:
```suggestion
		 * @param returns The return type of the function, null if the function should not return anything.
```

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 54]
```diff
@@ -134,4 +169,139 @@ public String toString(@Nullable Event event, boolean debug) {
...
+		}
+
+		/**
+		 * Represents the pattern used for the parameter definition in a script function declaration.
+		 * <p>
+		 * The first group specifies the name of the parameter. The name may contain any characters
+		 * but a colon, parenthesis, curly braces, double quotes, or a comma. Then, after a colon,
+		 * the type is specified in the {@code type} group. If a default value is present, this is specified
+		 * with the least amount of tokens as possible.
+		 * </p>
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]:
```suggestion
		 * </p>
		 * name : type = default
		 * [^:(){}\",]+? : [a-zA-Z ]+? = .+
```
including something like this might be helpful, idk

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 55]
```diff
@@ -134,4 +169,139 @@ public String toString(@Nullable Event event, boolean debug) {
...
+				}
+
+				if (i != args.length() && args.charAt(i) != ',') {
+					continue;
+				}
+
+				String arg = args.substring(j, i);
+
+                // One or more arguments for this function
+                Matcher n = SCRIPT_PARAMETER_PATTERN.matcher(arg);
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]: need better name than `n`

File: src/main/java/ch/njol/skript/util/Utils.java [hunk 56]
```diff
@@ -243,40 +244,74 @@ public static File getFile(Plugin plugin) {
...
-					if (word.length() != ending.plural().length())
-						continue;
+		PluralResult result = isPlural(word);
+		return new NonNullPair<>(result.updated, result.plural);
+	}
+
+	/**
+	 * Stores the result of {@link #isPlural(String)}.
+	 *
+	 * @param updated The single exist of the passed word, if a single variant exists.
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/util/Utils.java]:
```suggestion
	 * @param updated The singular version of the passed word, if a single variant exists.
```

File: src/main/java/org/skriptlang/skript/common/function/DefaultFunctionImpl.java [hunk 57]
```diff
@@ -3,6 +3,7 @@
 import ch.njol.skript.lang.function.FunctionEvent;
 import ch.njol.skript.lang.function.Signature;
 import com.google.common.base.Preconditions;
+import org.enginehub.piston.converter.MapArgumentConverter;
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/common/function/DefaultFunctionImpl.java]:
```suggestion
```

File: src/main/java/org/skriptlang/skript/common/function/Function.java [hunk 58]
```diff
@@ -16,9 +18,24 @@
...
 	/**
 	 * @return The signature belonging to this function.
 	 */
 	@NotNull Signature<T> signature();
 
+	@Experimental
+	boolean resetReturnValue();
+
+	@Experimental
+	@NotNull String @Nullable [] returnedKeys();
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/common/function/Function.java:45]: docs?

**Review by sovdeeth — CHANGES_REQUESTED** [review]
reviewed up to FunctionReference and then my eyes glazed over
I'll do the rest tomorrow

File: src/main/java/ch/njol/skript/lang/SkriptParser.java (hunk 35 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/SkriptParser.java]: it's still used by deprecated public methods

File: src/main/java/ch/njol/skript/lang/function/JavaFunction.java (hunk 46 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/function/JavaFunction.java]: yes, the rest of JavaFunction still uses the old Parameter, so this would be a breaking change

File: src/main/java/ch/njol/skript/lang/SkriptParser.java [hunk 59]
```diff
@@ -879,12 +868,7 @@ private boolean checkAcceptedType(Class<?> clazz, Class<?> ... types) {
 	private final static String MULTIPLE_AND_OR = "List has multiple 'and' or 'or', will default to 'and'. Use brackets if you want to define multiple lists.";
 	private final static String MISSING_AND_OR = "List is missing 'and' or 'or', defaulting to 'and'";
 
-	private boolean suppressMissingAndOrWarnings = SkriptConfig.disableMissingAndOrWarnings.value();
-
-	private SkriptParser suppressMissingAndOrWarnings() {
-		suppressMissingAndOrWarnings = true;
-		return this;
-	}
+	private final boolean suppressMissingAndOrWarnings = SkriptConfig.disableMissingAndOrWarnings.value();
```
Comment (erenkarakal) [inline src/main/java/ch/njol/skript/lang/SkriptParser.java:906]: does this work if you reload the config while the server is running?

File: src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java [hunk 60]
```diff
@@ -40,7 +42,7 @@ public static FunctionRegistry getRegistry() {
 	 * The pattern for a valid function name.
 	 * Functions must start with a letter or underscore and can only contain letters, numbers, and underscores.
 	 */
-	final static String FUNCTION_NAME_PATTERN = "[\\p{IsAlphabetic}_][\\p{IsAlphabetic}\\d_]*";
+	final static Pattern FUNCTION_NAME_PATTERN = Pattern.compile("[\\p{IsAlphabetic}_][\\p{IsAlphabetic}\\d_]*");
```
Comment (erenkarakal) [inline src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java]:
```suggestion
	final static Pattern FUNCTION_NAME_PATTERN = Pattern.compile(Functions.functionNamePattern);
```
(or remove the field altogether)

File: src/main/java/ch/njol/skript/lang/function/Functions.java [hunk 61]
```diff
@@ -106,20 +107,28 @@ public static JavaFunction<?> registerFunction(JavaFunction<?> function) {
...
+		if (Skript.debug() || node.debug()) {
+			Class<?> returnType = signature.returnType();
+			ClassInfo<?> c;
+			if (returnType != null && returnType.isArray()) {
+				c = Classes.getExactClassInfo(returnType.componentType());
+			} else {
+				c = Classes.getExactClassInfo(returnType);
+			}
+
+			Skript.debug((signature.isLocal() ? "local " : "") + "function " + name + "(" + StringUtils.join(params, ", ") + ")"
```
Comment (erenkarakal) [inline src/main/java/ch/njol/skript/lang/function/Functions.java]: is it possible to use `signature.toString()` here?

**Review by erenkarakal — CHANGES_REQUESTED** [review]

File: src/main/java/ch/njol/skript/lang/SkriptParser.java (hunk 59 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/lang/SkriptParser.java:906]: Yes, skript parsers are not very persistent. A new one is made for each parse, so there's no concern about this value being out of date.

File: src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java (hunk 36 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java]: unresolved

File: src/main/java/ch/njol/skript/lang/function/Function.java [hunk 62]
```diff
@@ -2,22 +2,38 @@
...
 /**
  * Functions can be called using arguments.
  */
 public abstract class Function<T> implements org.skriptlang.skript.common.function.Function<T> {
 
+	/**
+	 * @param cls The class.
+	 * @return The component of cls if cls is an array, otherwise cls.
+	 */
+	static Class<?> getComponent(Class<?> cls) {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Function.java]:
```suggestion
	public static Class<?> getComponentType(Class<?> cls) {
```
May want to move this to a more general class, like Utils

File: src/main/java/ch/njol/skript/lang/function/Function.java [hunk 63]
```diff
@@ -82,38 +113,43 @@ public boolean isSingle() {
...
+		Object[][] parameterValues = params.length < parameters.size() ? Arrays.copyOf(params, parameters.size()) : params;
 
+		int i = 0;
 		// Execute parameters or default value expressions
-		for (int i = 0; i < parameters.length; i++) {
-			Parameter<?> parameter = parameters[i];
+		for (org.skriptlang.skript.common.function.Parameter<?> parameter : parameters.all()) {
 			Object[] parameterValue = parameter.hasModifier(Modifier.KEYED) ? convertToKeyed(parameterValues[i]) : parameterValues[i];
 
+			Expression<?> def;
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Function.java]:
```suggestion
			Expression<?> defaultValueExpr;
```

File: src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java [hunk 64]
```diff
@@ -529,6 +525,13 @@ private Retrieval<Signature<?>> getSignature(@NotNull NamespaceIdentifier namesp
 			// if the types of the provided arguments do not match the candidate arguments, skip
 			for (int i = 0; i < provided.args.length; i++) {
 				// allows single passed values to still match array type in candidate (e.g. clamp)
+				Class<?> providedType;
+				if (provided.args[i].isArray()) {
+					providedType = provided.args[i].componentType();
+				} else {
+					providedType = provided.args[i];
+				}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java]: use the helper method

File: src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java [hunk 65]
```diff
@@ -505,12 +500,13 @@ private Retrieval<Signature<?>> getSignature(@NotNull NamespaceIdentifier namesp
...
 				// if a function has single list value param, check all types
-
 				// make sure all types in the passed array are valid for the array parameter
 				Class<?> arrayType = candidate.args[0].componentType();
 				for (Class<?> arrayArg : provided.args) {
-					if (arrayArg.isArray())
-						arrayArg = arrayArg.getComponentType();
+					if (arrayArg.isArray()) {
+						arrayArg = arrayArg.componentType();
+					}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java]: use the helper method

File: src/main/java/ch/njol/skript/lang/function/Functions.java [hunk 66]
```diff
@@ -106,20 +107,25 @@ public static JavaFunction<?> registerFunction(JavaFunction<?> function) {
...
-		Parameter<?>[] params = signature.parameters;
-		ClassInfo<?> c = signature.returnType;
+		if (Skript.debug() || node.debug()) {
+			Class<?> returnType = signature.returnType();
+			ClassInfo<?> c;
+			if (returnType != null && returnType.isArray()) {
+				c = Classes.getExactClassInfo(returnType.componentType());
+			} else {
+				c = Classes.getExactClassInfo(returnType);
+			}
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Functions.java]: helper method!

File: src/main/java/ch/njol/skript/lang/function/Parameter.java [hunk 67]
```diff
@@ -291,12 +299,22 @@ public String toString(boolean debug) {
...
+		}
 	}
 
 	@Override
 	public @Unmodifiable @NotNull Set<Modifier> modifiers() {
 		return Collections.unmodifiableSet(modifiers);
 	}
 
+	@Override
+	public boolean single() {
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Parameter.java]: this method isn't useful, isSingleValue already fills this role.

File: src/main/java/ch/njol/skript/lang/function/Signature.java [hunk 68]
```diff
@@ -56,132 +59,170 @@ public class Signature<T> implements org.skriptlang.skript.common.function.Signa
...
+		this.parameters = initParameters(parameters);
 		this.local = local;
 		this.returnType = returnType;
+		if (returnType == null) {
+			this.returns = null;
+		} else {
+			if (single) {
+				this.returns = returnType.getC();
+			} else {
+				this.returns = returnType.getC().arrayType();
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/lang/function/Signature.java]: seen this pattern twice now so it should be pulled into a helper method of its own

File: src/main/java/ch/njol/skript/lang/SkriptParser.java (hunk 34 above)
Comment (sovdeeth) [reply src/main/java/ch/njol/skript/lang/SkriptParser.java:1197]: unresolved

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 69]
```diff
@@ -134,4 +169,144 @@ public String toString(@Nullable Event event, boolean debug) {
...
+                for (String otherName : params.keySet()) {
+                    // only force lowercase if we don't care about case in variables
+                    otherName = caseInsensitive ? otherName.toLowerCase(Locale.ENGLISH) : otherName;
+                    if (otherName.equals(caseInsensitive ? lowerParamName : paramName)) {
+                        Skript.error("Each argument's name must be unique, but the name '" + paramName + "' occurs at least twice.");
+                        return null;
+                    }
+                }
+
+                ClassInfo<?> c = Classes.getClassInfoFromUserInput(matcher.group("type"));
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]:
```suggestion
                ClassInfo<?> classInfo = Classes.getClassInfoFromUserInput(matcher.group("type"));
```

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 70]
```diff
@@ -134,4 +169,144 @@ public String toString(@Nullable Event event, boolean debug) {
...
+
+                String variableName = paramName.endsWith("*") ? paramName.substring(0, paramName.length() - 3) +
+                    (!result.plural() ? "::1" : "") : paramName;
+
+                Class<?> type;
+                if (result.plural()) {
+                    type = c.getC().arrayType();
+                } else {
+                    type = c.getC();
+                }
```
Comment (sovdeeth) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]: helper method

File: src/main/java/org/skriptlang/skript/common/function/FunctionReference.java [hunk 71]
```diff
@@ -0,0 +1,360 @@
...
+	}
+
+	private String getName(Class<?> clazz, boolean single) {
+		if (single) {
+			return Classes.getSuperClassInfo(clazz).getName().getSingular();
+		} else {
+			if (clazz.isArray()) {
+				return Classes.getSuperClassInfo(clazz.componentType()).getName().getPlural();
+			}
+			return Classes.getSuperClassInfo(clazz).getName().getPlural();
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/common/function/FunctionReference.java]: helper method

File: src/main/java/org/skriptlang/skript/common/function/Signature.java [hunk 72]
```diff
@@ -15,4 +20,37 @@
...
+	 * Adds a reference to the clearing list.
+	 * @param reference The reference.
+	 */
+	@Experimental
+	void addCall(FunctionReference<?> reference);
+
+	/**
+	 * @return Whether this signature returns single values.
+	 */
+	default boolean single() {
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/common/function/Signature.java]:
```suggestion
	default boolean isSingle() {
```
boolean getters should generally be prefixed with is

File: src/main/java/org/skriptlang/skript/common/function/ScriptParameter.java [hunk 73]
```diff
@@ -0,0 +1,85 @@
...
+		}
+
+		Expression<?> defaultValue = null;
+		if (def != null) {
+			Class<?> target;
+			if (type.isArray()) {
+				target = type.componentType();
+			} else {
+				target = type;
+			}
```
Comment (sovdeeth) [inline src/main/java/org/skriptlang/skript/common/function/ScriptParameter.java]: HELPER METHOD

**Review by sovdeeth — CHANGES_REQUESTED** [review]
ok github's stupid new review feature cleared all the comments i wrote when i switched what commits to view
But to sum up: 
- move the component type helper to Utils, name it getComponentType, add a corresponding helper for getting array type if plural.
- Actually use these helpers (i found like a half dozen places in this pr they should be used)
- and boolean getters like `single()` should be named like `isSingle()`

edit:
oh wait the comments are still here! it just didn't show them in the review preview :)

File: src/main/java/ch/njol/skript/lang/function/Parameter.java (hunk 67 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/function/Parameter.java]: it's required by the Parameter interface

File: src/main/java/ch/njol/skript/structures/StructFunction.java (hunk 70 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/structures/StructFunction.java]: this is actually a different application

File: src/main/java/ch/njol/skript/lang/function/Signature.java (hunk 68 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/function/Signature.java]: okay yeah fair enough lol

**Review by erenkarakal — APPROVED** [review]

File: src/main/java/ch/njol/skript/lang/function/Function.java [hunk 74]
```diff
@@ -47,13 +52,20 @@ public String getName() {
 		return sign.getName();
 	}
 
-	public Parameter<?>[] getParameters() {
+	/**
+	 * @deprecated Use {@link Signature#parameters()} and {@link Parameters#all()} instead.
+	 */
+	@Deprecated(forRemoval = true, since = "INSERT VERSION")
+	public org.skriptlang.skript.common.function.Parameter<?>[] getParameters() {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/function/Function.java]: Do we need to change the return types here? It seems like `Signature` converts them/returns the old type?

File: src/main/java/ch/njol/skript/lang/function/FunctionReference.java [hunk 75]
```diff
@@ -229,17 +231,19 @@ public boolean validateFunction(boolean first) {
...
-				Expression<?> e = parameters[i].getConvertedExpression(p.type());
-				if (e == null) {
+				Expression<?> expr = parameters[i].getConvertedExpression(target);
+				if (expr == null) {
 					if (first) {
 						if (LiteralUtils.hasUnparsedLiteral(parameters[i])) {
 							Skript.error("Can't understand this expression: " + parameters[i].toString());
 						} else {
-							String type = Classes.toString(getClassInfo(p.type()));
+							String type = Classes.toString(Classes.getSuperClassInfo(Utils.getComponentType(target)));
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/function/FunctionReference.java]:
```suggestion
							String type = Classes.toString(Classes.getSuperClassInfo(target));
```
Target already reflects the component type, right?

File: src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java]: this can also use the Utils method right?

File: src/main/java/ch/njol/skript/lang/function/Signature.java [hunk 76]
```diff
@@ -56,132 +59,176 @@ public class Signature<T> implements org.skriptlang.skript.common.function.Signa
...
 	 */
-	final @Nullable String originClassPath;
+	final @Nullable Contract contract;
 
 	/**
-	 * An overriding contract for this function (e.g. to base its return on its arguments).
+	 * The class path for the origin of this signature.
 	 */
-	final @Nullable Contract contract;
+	@Nullable String originClassPath;
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/lang/function/Signature.java:69]: not final?

**Review by sovdeeth — APPROVED** [review]

File: src/main/java/ch/njol/skript/structures/StructFunction.java [hunk 77]
```diff
@@ -134,4 +169,144 @@ public String toString(@Nullable Event event, boolean debug) {
 		return (local ? "local " : "") + "function";
 	}
 
+	public static class FunctionParser {
```
Comment (APickledWalrus) [inline src/main/java/ch/njol/skript/structures/StructFunction.java]: is this intended to be usable by addons? if so, i think we should move it out of this class (syntax classes are likely to move around)

File: src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java [hunk 78]
```diff
@@ -0,0 +1,530 @@
...
+			}
+
+			Skript.error(Language.get("functions.already assigned value to parameter"), argument.name());
+			log.printError();
+			return null;
+		}
+
+		String namespace;
+		if (ParserInstance.get().isActive()) {
+			namespace = ParserInstance.get().getCurrentScript().getConfig().getFileName();
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java]: I would store the result of `ParserInstance.get()` rather than call it twice

File: src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java [hunk 79]
```diff
@@ -0,0 +1,530 @@
...
+	 * @return All possible exact {@link FunctionReference FunctionReferences}.
+	 */
+	private <T> Set<FunctionReference<T>> getExactReferences(
+			String namespace, String name,
+			Set<Signature<?>> signatures, Argument<String>[] arguments
+	) {
+		Set<FunctionReference<T>> exactReferences = new HashSet<>();
+
+		signatures:
+		for (Signature<?> signature : signatures) {
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java:201]: I'm thinking we'd want to cache results for partially successful attempts? For example, if I have two signatures:
```
func(a: int, b: int)
func(a: int, b: string)
```
If I wanted the second function (with string), but the first function is attempted first, does that currently result in my passed argument for `a` being parsed twice?

File: src/main/java/org/skriptlang/skript/common/function/Parameter.java [hunk 80]
```diff
@@ -40,13 +42,13 @@ default boolean hasModifier(Modifier modifier) {
 	/**
 	 * @return Whether this parameter is for single values.
 	 */
-	default boolean single() {
+	default boolean isSingle() {
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/Parameter.java:100]: Do we want to retain the old method for compatibility? I'm not sure how widely it would have been used.

File: src/main/java/org/skriptlang/skript/common/function/ScriptParameter.java [hunk 81]
```diff
@@ -0,0 +1,81 @@
...
+/**
+ * A parameter for a {@link DefaultFunction}.
+ *
+ * @param name         The name.
+ * @param type         The type's class.
+ * @param modifiers    The modifiers.
+ * @param defaultValue The default value, or null if there is no default value.
+ * @param <T>          The type.
+ */
+public record ScriptParameter<T>(String name, Class<T> type, Set<Modifier> modifiers, Expression<?> defaultValue)
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/ScriptParameter.java]: defaultValue should probably be annotated as nullable

File: src/main/java/org/skriptlang/skript/common/function/Signature.java [hunk 82]
```diff
@@ -15,4 +18,37 @@
 @Experimental
 public interface Signature<T> {
 
+	/**
+	 * @return The type of this parameter.
+	 */
+	Class<T> returnType();
```
Comment (APickledWalrus) [inline src/main/java/org/skriptlang/skript/common/function/Signature.java]: Is this null if there is no return type? Should probably be annotated as nullable

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
Looking really good, nearly ready.

File: src/main/java/org/skriptlang/skript/common/function/Signature.java (hunk 82 above)
Comment (Efnilite) [reply src/main/java/org/skriptlang/skript/common/function/Signature.java]: yes, but Signature is implemented by ScriptFunction (where I agree it should be nullable) and in DefaultFunction (where whether null is returned can be known at compile time, thus I believe that @Nullable should not be added). wdyt?

File: src/main/java/org/skriptlang/skript/common/function/Parameter.java (hunk 80 above)
Comment (Efnilite) [reply src/main/java/org/skriptlang/skript/common/function/Parameter.java:100]: sure

File: src/main/java/ch/njol/skript/lang/function/Signature.java (hunk 76 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/lang/function/Signature.java:69]: if this is final it wouldn't allow being assigned to an actual value in the constructors that support it

File: src/main/java/ch/njol/skript/structures/StructFunction.java (hunk 77 above)
Comment (Efnilite) [reply src/main/java/ch/njol/skript/structures/StructFunction.java]: where would you suggest putting it?

File: src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java (hunk 79 above)
Comment (Efnilite) [reply src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java:201]: in order to get this PR through before the next release, would you mind if i added this in a later pr? i'll add it as a todo

File: src/main/java/org/skriptlang/skript/common/function/Signature.java (hunk 82 above)
Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/common/function/Signature.java]: I'm not sure I entirely follow. For it to be marked as Nullable for any implementations, it has to be nullable for the parent. Given that the default implementation for `isSingle` performs a null check as well, I'm inclined to believe that there is no other way to know (with just a Signature object), and thus it should be Nullable.

File: src/main/java/ch/njol/skript/structures/StructFunction.java (hunk 77 above)
Comment (APickledWalrus) [reply src/main/java/ch/njol/skript/structures/StructFunction.java]: I think in the new Functions package is probably fine.

File: src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java (hunk 79 above)
Comment (APickledWalrus) [reply src/main/java/org/skriptlang/skript/common/function/FunctionReferenceParser.java:201]: Yeah, it should be fine. We can add it in as a patch.

**Review by APickledWalrus — APPROVED** [review]
